[package]
name = "skippr-plugin-data-sink-azure-blob"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "skippr-plugin-data-sink-azure-blob"
path = "src/main.rs"

[dependencies]
clap.workspace = true
tokio.workspace = true
skippr-runtime-sdk.workspace = true
arrow.workspace = true
bytes.workspace = true
futures.workspace = true
parquet.workspace = true

async-trait = "0.1.77"
datafusion = "50.3.0"
hex = "0.4.3"
md5 = "0.7.0"
object_store = { version = "0.12.4", features = ["aws", "azure", "gcp"] }
serde.workspace = true
serde_derive = "1.0.105"
tracing = "0.1"
[package.metadata.skippr-plugin]
kind = "DataSink"
plugin_name = "AzureBlob"

[package.metadata.skippr-plugin.sink_capability]
name = "AzureBlob"
guarantee_tier = "CdcEncodedOnly"
can_manage_skippr_columns = false
can_maintain_tombstone_tables = false
can_compare_order_tokens = false
supports_transactions = false
