name: Heaptrack
description: "Run heaptrack on Skippr"
inputs:
  architecture_name:
    description: 'macos_arm64, macos-x86, linux_x86'
    required: true
    default: 'stable'
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  docker_hub_pass:
    required: true
runs:
  using: "composite"
  steps:
    - name: Discover Schemas
      shell: bash
      run: |
        chmod +x ./skipprd-${{ inputs.architecture_name }}/skipprd
        
        cp .github/actions/e2e/heaptrack/skippr.yml ./skippr.yml
        
        ls -la ./
        
        AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire
        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire"
        

#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many2
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many2"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many3
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many3"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many4
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many4"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many5
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many5"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many6
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many6"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many7
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many7"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many8
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many8"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many9
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many9"
#        SKIPPR_S3_BUCKET=skippr-e2e-sample-data-output TENANT_ID=skippr AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many10
#        ./skipprd-${{ inputs.architecture_name }}/skipprd query --sql "ENABLE PIPELINE bike_hire_many10"


    - name: Install Heaptrack
      shell: bash
      run: |
        if [[ "${{ inputs.architecture_name }}" == "linux_x86" ]]; then
        sudo apt-get update && sudo apt-get install -y heaptrack
        elif [[ "${{ inputs.architecture_name }}" == "macos_arm64" || "${{ inputs.architecture_name }}" == "macos-x86" ]]; then
        brew install heaptrack
        fi

    - name: Run Heaptrack
      shell: bash
      run: |
        if [[ "${{ inputs.architecture_name }}" == "linux_x86" || "${{ inputs.architecture_name }}" == "macos_arm64" || "${{ inputs.architecture_name }}" == "macos-x86" ]]; then
          AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 heaptrack ./skipprd-${{ inputs.architecture_name }}/skipprd sync --log --pipeline bike_hire
          mv heaptrack.*.zst heaptrack_output.zst
        fi

    - name: Upload Heaptrack Output
      uses: actions/upload-artifact@v4
      with:
        name: heaptrack-output
        path: heaptrack_output.zst