//! Reflect in-tree plugin config structs into connect CLI/Python/persist metadata.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

const GENERATED_PREAMBLE: &str = "// @generated by skippr-connect-gen. Do not edit.\n";

use syn::{Attribute, Fields, Item, Type};

pub mod python;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub enum PluginKind {
    DataSource,
    DataSink,
    SchemaSink,
}

impl PluginKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::DataSource => "DataSource",
            Self::DataSink => "DataSink",
            Self::SchemaSink => "SchemaSink",
        }
    }

    pub fn clap_role(self) -> &'static str {
        match self {
            Self::DataSource => "data-source",
            Self::DataSink => "data-sink",
            Self::SchemaSink => "schema-sink",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SecretKind {
    None,
    Secret,
    SecretPath,
    NotSecret,
}

#[derive(Clone, Debug, PartialEq)]
pub struct FieldSpec {
    pub ident: String,
    pub yaml_path: String,
    pub optional: bool,
    pub secret: SecretKind,
    pub rust_ty: String,
    pub doc: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct StructSpec {
    pub doc: String,
    pub fields: Vec<FieldSpec>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct VariantSpec {
    pub rust_name: String,
    pub wire: String,
    pub doc: String,
    /// `None` for a unit variant.
    pub fields: Option<Vec<FieldSpec>>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EnumSpec {
    pub doc: String,
    pub tag: Option<String>,
    pub untagged: bool,
    pub variants: Vec<VariantSpec>,
}

impl EnumSpec {
    /// A string enum: every variant is a unit and there is no tag.
    pub fn is_string_enum(&self) -> bool {
        self.tag.is_none() && !self.untagged && self.variants.iter().all(|v| v.fields.is_none())
    }

    /// Every variant's named fields, first occurrence wins. Used by the CLI,
    /// which flattens tagged enums into `<field>.<tag>` plus variant fields.
    fn merged_fields(&self) -> Vec<FieldSpec> {
        let mut seen = BTreeSet::new();
        let mut out = Vec::new();
        for field in self.variants.iter().flat_map(|v| v.fields.iter().flatten()) {
            if seen.insert(field.ident.clone()) {
                out.push(field.clone());
            }
        }
        out
    }
}

/// Deserializable structs and enums reflected from one set of source files.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct TypeCatalog {
    pub structs: BTreeMap<String, StructSpec>,
    pub enums: BTreeMap<String, EnumSpec>,
}

#[derive(Clone, Debug)]
pub struct PluginSpec {
    pub kind: PluginKind,
    pub plugin_name: String,
    pub crate_name: String,
    /// Doc comment on the plugin config struct.
    pub doc: String,
    /// Flattened `ident` / `yaml_path` view used by the CLI and persist metadata.
    pub fields: Vec<FieldSpec>,
    pub config_fields: Vec<FieldSpec>,
    pub types: TypeCatalog,
}

/// What Python generation reads from `src/helpers/configuration.rs`.
#[derive(Clone, Debug)]
pub struct EngineSpec {
    pub types: TypeCatalog,
    /// `PairedSink` variants: plugin names whose data and schema sink share one config.
    pub paired_sinks: Vec<String>,
}

pub fn workspace_root(from: &Path) -> PathBuf {
    from.to_path_buf()
}

pub fn discover_plugins(root: &Path) -> Result<Vec<PluginSpec>, String> {
    let mut plugins = Vec::new();
    for kind_dir in ["data_source", "data_sink", "schema_sink"] {
        let dir = root.join("plugins").join(kind_dir);
        if !dir.exists() {
            continue;
        }
        let mut crates: Vec<PathBuf> = fs::read_dir(&dir)
            .map_err(|err| format!("read {}: {err}", dir.display()))?
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .filter(|path| path.join("Cargo.toml").exists())
            .collect();
        crates.sort();
        for crate_dir in crates {
            plugins.push(load_plugin(root, &crate_dir)?);
        }
    }
    plugins.sort_by(|a, b| (a.kind, &a.plugin_name).cmp(&(b.kind, &b.plugin_name)));
    Ok(plugins)
}

fn load_plugin(root: &Path, crate_dir: &Path) -> Result<PluginSpec, String> {
    let cargo_text = fs::read_to_string(crate_dir.join("Cargo.toml"))
        .map_err(|err| format!("{}: {err}", crate_dir.display()))?;
    let cargo: toml::Value = toml::from_str(&cargo_text)
        .map_err(|err| format!("{} Cargo.toml: {err}", crate_dir.display()))?;
    let meta = cargo
        .get("package")
        .and_then(|p| p.get("metadata"))
        .and_then(|m| m.get("skippr-plugin"))
        .ok_or_else(|| {
            format!(
                "{} missing [package.metadata.skippr-plugin]",
                crate_dir.display()
            )
        })?;
    let kind = match meta.get("kind").and_then(|v| v.as_str()) {
        Some("DataSource") => PluginKind::DataSource,
        Some("DataSink") => PluginKind::DataSink,
        Some("SchemaSink") => PluginKind::SchemaSink,
        other => {
            return Err(format!(
                "{} unknown plugin kind {other:?}",
                crate_dir.display()
            ))
        }
    };
    let plugin_name = meta
        .get("plugin_name")
        .and_then(|v| v.as_str())
        .ok_or_else(|| format!("{} missing plugin_name", crate_dir.display()))?
        .to_string();
    let crate_name = cargo
        .get("package")
        .and_then(|p| p.get("name"))
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let mut reflected = reflect_crate(crate_dir)?;
    if reflected.is_none() && kind == PluginKind::SchemaSink {
        if let Some(dep_dir) = schema_sink_dep_dir(crate_dir, &cargo) {
            reflected = reflect_crate(&dep_dir)?;
        }
    }
    if reflected.is_none() && plugin_name == "Stdout" {
        reflected = Some(ReflectedConfig::default());
    }
    let mut reflected = reflected.ok_or_else(|| {
        format!(
            "{} has skippr-plugin metadata but no parseable config struct",
            crate_dir.display()
        )
    })?;
    for file in dependency_type_files(root, crate_dir, &cargo)? {
        let dep = reflect_source_file(&file)?;
        for (name, spec) in dep.structs {
            reflected.types.structs.entry(name).or_insert(spec);
        }
        for (name, spec) in dep.enums {
            reflected.types.enums.entry(name).or_insert(spec);
        }
    }
    let fields = expand_nested(reflected.fields.clone(), &reflected.types);
    validate_secrets(&crate_name, &fields)?;
    Ok(PluginSpec {
        kind,
        plugin_name,
        crate_name,
        doc: reflected.doc,
        fields,
        config_fields: reflected.fields,
        types: reflected.types,
    })
}

/// Source files whose types a plugin config may name without defining them:
/// path-dependency plugin crates, and the plugin SDK's shared config enums
/// (`SourceCdcMode`, `WritePolicy`). Local definitions win.
fn dependency_type_files(
    root: &Path,
    crate_dir: &Path,
    cargo: &toml::Value,
) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    let Some(deps) = cargo.get("dependencies").and_then(|v| v.as_table()) else {
        return Ok(files);
    };
    for (name, spec) in deps {
        if !name.starts_with("skippr-plugin-") {
            continue;
        }
        if let Some(rel) = spec.get("path").and_then(|v| v.as_str()) {
            let dep_dir = crate_dir.join(rel);
            collect_mod_graph(&dep_dir, &dep_dir.join("src/lib.rs"), &mut files)?;
        }
    }
    if deps.contains_key("skippr-runtime-sdk") {
        files.push(root.join("src/plugins/traits.rs"));
        files.push(root.join("src/plugins/source_contract.rs"));
    }
    Ok(files)
}

fn schema_sink_dep_dir(crate_dir: &Path, cargo: &toml::Value) -> Option<PathBuf> {
    let deps = cargo.get("dependencies")?.as_table()?;
    for (name, spec) in deps {
        if !name.starts_with("skippr-plugin-data-") {
            continue;
        }
        let path = spec.get("path").and_then(|v| v.as_str())?;
        return Some(crate_dir.join(path));
    }
    None
}

#[derive(Clone, Debug, Default)]
struct ReflectedConfig {
    doc: String,
    fields: Vec<FieldSpec>,
    types: TypeCatalog,
}

fn reflect_crate(crate_dir: &Path) -> Result<Option<ReflectedConfig>, String> {
    let mut plugin_files = Vec::new();
    collect_mod_graph(crate_dir, &crate_dir.join("src/lib.rs"), &mut plugin_files)?;
    if crate_dir.join("src/main.rs").exists() {
        collect_mod_graph(crate_dir, &crate_dir.join("src/main.rs"), &mut plugin_files)?;
    }
    let mut files = plugin_files.clone();
    if let Ok(cargo_text) = fs::read_to_string(crate_dir.join("Cargo.toml")) {
        if let Ok(cargo) = toml::from_str::<toml::Value>(&cargo_text) {
            if let Some(deps) = cargo.get("dependencies").and_then(|v| v.as_table()) {
                if let Some(spec) = deps.get("skippr-iceberg-catalog") {
                    if let Some(rel) = spec.get("path").and_then(|v| v.as_str()) {
                        let dep_dir = crate_dir.join(rel);
                        collect_mod_graph(&dep_dir, &dep_dir.join("src/lib.rs"), &mut files)?;
                    }
                }
            }
        }
    }
    let mut types = TypeCatalog::default();
    let mut try_from_targets = BTreeSet::new();
    let mut plugin_struct_names = BTreeSet::new();
    for file in &files {
        let plugin_local = plugin_files.iter().any(|p| p == file);
        let text = match fs::read_to_string(file) {
            Ok(text) => text,
            Err(_) => continue,
        };
        let parsed = match syn::parse_file(&text) {
            Ok(file) => file,
            Err(_) => continue,
        };
        for item in parsed.items {
            match item {
                Item::Struct(item) => {
                    if !has_deserialize(&item.attrs) && item.ident != "OtlpConfigRaw" {
                        continue;
                    }
                    if plugin_local {
                        plugin_struct_names.insert(item.ident.to_string());
                    }
                    types
                        .structs
                        .insert(item.ident.to_string(), reflect_struct(&item)?);
                }
                Item::Enum(item) => {
                    if !has_deserialize(&item.attrs) {
                        continue;
                    }
                    types
                        .enums
                        .insert(item.ident.to_string(), reflect_enum(&item)?);
                }
                Item::Impl(item) => {
                    if let Some((_, path, _)) = &item.trait_ {
                        if path_ends_with(path, "TryFrom") {
                            if let Type::Path(ty) = &*item.self_ty {
                                if let Some(ident) = ty.path.segments.last() {
                                    try_from_targets.insert(ident.ident.to_string());
                                }
                            }
                        }
                    }
                }
                _ => {}
            }
        }
    }
    if let Some(name) = pick_config_name(&types.structs, &try_from_targets, &plugin_struct_names) {
        let config = types.structs.get(&name).cloned().unwrap_or(StructSpec {
            doc: String::new(),
            fields: Vec::new(),
        });
        return Ok(Some(ReflectedConfig {
            doc: config.doc,
            fields: config.fields,
            types,
        }));
    }
    Ok(None)
}

/// Reflect every deserializable struct and enum in one source file.
pub fn reflect_source_file(path: &Path) -> Result<TypeCatalog, String> {
    let text = fs::read_to_string(path).map_err(|err| format!("read {}: {err}", path.display()))?;
    let parsed =
        syn::parse_file(&text).map_err(|err| format!("parse {}: {err}", path.display()))?;
    let mut types = TypeCatalog::default();
    for item in parsed.items {
        match item {
            Item::Struct(item) if has_deserialize(&item.attrs) => {
                types
                    .structs
                    .insert(item.ident.to_string(), reflect_struct(&item)?);
            }
            Item::Enum(item) if has_deserialize(&item.attrs) => {
                types
                    .enums
                    .insert(item.ident.to_string(), reflect_enum(&item)?);
            }
            _ => {}
        }
    }
    Ok(types)
}

fn reflect_struct(item: &syn::ItemStruct) -> Result<StructSpec, String> {
    let rename_all = serde_str(&item.attrs, "rename_all");
    let container_default = serde_flag(&item.attrs, "default");
    Ok(StructSpec {
        doc: doc_string(&item.attrs),
        fields: struct_fields(&item.fields, rename_all.as_deref(), container_default)?,
    })
}

fn reflect_enum(item: &syn::ItemEnum) -> Result<EnumSpec, String> {
    let rename_all = serde_str(&item.attrs, "rename_all");
    let mut variants = Vec::new();
    for variant in &item.variants {
        let rust_name = variant.ident.to_string();
        let wire = match serde_str(&variant.attrs, "rename") {
            Some(wire) => wire,
            None => rename_variant(rename_all.as_deref(), &rust_name)
                .map_err(|err| format!("{}::{rust_name}: {err}", item.ident))?,
        };
        let variant_rename_all = serde_str(&variant.attrs, "rename_all");
        let fields = match &variant.fields {
            Fields::Unit => None,
            fields => Some(struct_fields(fields, variant_rename_all.as_deref(), false)?),
        };
        variants.push(VariantSpec {
            rust_name,
            wire,
            doc: doc_string(&variant.attrs),
            fields,
        });
    }
    Ok(EnumSpec {
        doc: doc_string(&item.attrs),
        tag: serde_str(&item.attrs, "tag"),
        untagged: serde_flag(&item.attrs, "untagged"),
        variants,
    })
}

/// serde's `rename_all` applied to a PascalCase variant name.
fn rename_variant(rule: Option<&str>, name: &str) -> Result<String, String> {
    let snake = || {
        let mut out = String::new();
        for (i, ch) in name.char_indices() {
            if i > 0 && ch.is_uppercase() {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        }
        out
    };
    Ok(match rule {
        None | Some("PascalCase") => name.to_string(),
        Some("lowercase") => name.to_ascii_lowercase(),
        Some("UPPERCASE") => name.to_ascii_uppercase(),
        Some("snake_case") => snake(),
        Some("SCREAMING_SNAKE_CASE") => snake().to_ascii_uppercase(),
        Some("kebab-case") => snake().replace('_', "-"),
        Some("SCREAMING-KEBAB-CASE") => snake().replace('_', "-").to_ascii_uppercase(),
        Some("camelCase") => {
            let mut chars = name.chars();
            match chars.next() {
                Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        }
        Some(other) => return Err(format!("unsupported serde rename_all {other:?}")),
    })
}

/// serde's `rename_all` applied to a snake_case field name.
fn rename_field(rule: Option<&str>, name: &str) -> Result<String, String> {
    let pascal = || {
        name.split('_')
            .map(|part| {
                let mut chars = part.chars();
                match chars.next() {
                    Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                    None => String::new(),
                }
            })
            .collect::<String>()
    };
    Ok(match rule {
        None | Some("snake_case") | Some("lowercase") => name.to_string(),
        Some("UPPERCASE") | Some("SCREAMING_SNAKE_CASE") => name.to_ascii_uppercase(),
        Some("kebab-case") => name.replace('_', "-"),
        Some("SCREAMING-KEBAB-CASE") => name.replace('_', "-").to_ascii_uppercase(),
        Some("PascalCase") => pascal(),
        Some("camelCase") => {
            let pascal = pascal();
            let mut chars = pascal.chars();
            match chars.next() {
                Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        }
        Some(other) => return Err(format!("unsupported serde rename_all {other:?}")),
    })
}

fn doc_string(attrs: &[Attribute]) -> String {
    let lines: Vec<String> = attrs
        .iter()
        .filter_map(|attr| {
            let syn::Meta::NameValue(nv) = &attr.meta else {
                return None;
            };
            if !nv.path.is_ident("doc") {
                return None;
            }
            match &nv.value {
                syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(lit),
                    ..
                }) => Some(lit.value().trim().to_string()),
                _ => None,
            }
        })
        .collect();
    lines.join("\n").trim().to_string()
}

fn serde_metas(attrs: &[Attribute]) -> Vec<syn::Meta> {
    let mut out = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        if let Ok(meta) = attr.parse_args_with(
            syn::punctuated::Punctuated::<syn::Meta, syn::Token![,]>::parse_terminated,
        ) {
            out.extend(meta);
        }
    }
    out
}

/// `#[serde(name)]` or `#[serde(name = ...)]`.
fn serde_flag(attrs: &[Attribute], name: &str) -> bool {
    serde_metas(attrs)
        .iter()
        .any(|meta| meta.path().is_ident(name))
}

/// The string literal of `#[serde(name = "...")]`.
fn serde_str(attrs: &[Attribute], name: &str) -> Option<String> {
    serde_metas(attrs).into_iter().find_map(|meta| {
        let syn::Meta::NameValue(nv) = meta else {
            return None;
        };
        if !nv.path.is_ident(name) {
            return None;
        }
        match nv.value {
            syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(value),
                ..
            }) => Some(value.value()),
            _ => None,
        }
    })
}

fn rust_type_name(ty: &str) -> String {
    let ty = ty
        .trim()
        .trim_start_matches("Option<")
        .trim_end_matches('>')
        .rsplit("::")
        .next()
        .unwrap_or(ty);
    ty.to_string()
}

fn expand_nested(fields: Vec<FieldSpec>, types: &TypeCatalog) -> Vec<FieldSpec> {
    fn expand_one(
        field: FieldSpec,
        types: &TypeCatalog,
        visiting: &mut BTreeSet<String>,
    ) -> Vec<FieldSpec> {
        if !visiting.insert(field.yaml_path.clone()) {
            return Vec::new();
        }
        let ty_name = rust_type_name(&field.rust_ty);
        if let Some(nested) = types.structs.get(&ty_name) {
            let mut out = Vec::new();
            for child in &nested.fields {
                let expanded = FieldSpec {
                    ident: format!("{}_{}", field.ident, child.ident),
                    yaml_path: format!("{}.{}", field.yaml_path, child.yaml_path),
                    optional: field.optional || child.optional,
                    secret: child.secret,
                    rust_ty: child.rust_ty.clone(),
                    doc: child.doc.clone(),
                };
                out.extend(expand_one(expanded, types, visiting));
            }
            visiting.remove(&field.yaml_path);
            return out;
        }
        if let Some(spec) = types.enums.get(&ty_name) {
            if let Some(tag) = &spec.tag {
                let mut out = Vec::new();
                out.push(FieldSpec {
                    ident: format!("{}_{}", field.ident, tag.replace('-', "_")),
                    yaml_path: format!("{}.{tag}", field.yaml_path),
                    optional: field.optional,
                    secret: SecretKind::None,
                    rust_ty: "String".into(),
                    doc: spec.doc.clone(),
                });
                for child in spec.merged_fields() {
                    let expanded = FieldSpec {
                        ident: format!("{}_{}", field.ident, child.ident),
                        yaml_path: format!("{}.{}", field.yaml_path, child.yaml_path),
                        optional: true,
                        secret: child.secret,
                        rust_ty: child.rust_ty.clone(),
                        doc: child.doc.clone(),
                    };
                    out.extend(expand_one(expanded, types, visiting));
                }
                visiting.remove(&field.yaml_path);
                return out;
            }
        }
        visiting.remove(&field.yaml_path);
        vec![field]
    }
    let mut out = Vec::new();
    let mut seen = BTreeSet::new();
    for field in fields {
        for expanded in expand_one(field, types, &mut BTreeSet::new()) {
            if seen.insert(expanded.ident.clone()) {
                out.push(expanded);
            }
        }
    }
    out
}

fn pick_config_name(
    structs: &BTreeMap<String, StructSpec>,
    try_from_targets: &BTreeSet<String>,
    plugin_struct_names: &BTreeSet<String>,
) -> Option<String> {
    let plugin_configs: Vec<String> = plugin_struct_names
        .iter()
        .filter(|name| name.ends_with("PluginConfig") || name.ends_with("Config"))
        .filter(|name| {
            !name.ends_with("Checkpoint") && !name.contains("Privacy") && *name != "RetryConfig"
        })
        .cloned()
        .collect();
    if plugin_configs.len() == 1 {
        return Some(plugin_configs[0].clone());
    }
    let plugin_configs: Vec<String> = structs
        .keys()
        .filter(|name| name.ends_with("PluginConfig"))
        .cloned()
        .collect();
    if plugin_configs.len() == 1 {
        return Some(plugin_configs[0].clone());
    }
    for name in try_from_targets {
        if structs.contains_key(name) {
            return Some(name.clone());
        }
    }
    if structs.contains_key("OtlpConfigRaw") {
        return Some("OtlpConfigRaw".into());
    }
    let configs: Vec<String> = structs
        .keys()
        .filter(|name| {
            name.ends_with("Config")
                && !name.ends_with("Checkpoint")
                && !name.contains("Privacy")
                && *name != "RetryConfig"
        })
        .cloned()
        .collect();
    if configs.len() == 1 {
        return Some(configs[0].clone());
    }
    None
}

fn collect_mod_graph(crate_dir: &Path, file: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    if out.iter().any(|p| p == file) {
        return Ok(());
    }
    if !file.exists() {
        return Ok(());
    }
    out.push(file.to_path_buf());
    let text = fs::read_to_string(file).map_err(|err| format!("read {}: {err}", file.display()))?;
    let parsed = match syn::parse_file(&text) {
        Ok(file) => file,
        Err(_) => return Ok(()),
    };
    let parent = file.parent().unwrap_or(crate_dir);
    for item in parsed.items {
        let Item::Mod(module) = item else { continue };
        if module.content.is_some() {
            continue;
        }
        let name = module.ident.to_string();
        let path_attr = module.attrs.iter().find_map(|attr| {
            if let syn::Meta::NameValue(nv) = &attr.meta {
                if nv.path.is_ident("path") {
                    if let syn::Expr::Lit(syn::ExprLit {
                        lit: syn::Lit::Str(lit),
                        ..
                    }) = &nv.value
                    {
                        return Some(lit.value());
                    }
                }
            }
            None
        });
        let candidates = if let Some(rel) = path_attr {
            vec![parent.join(&rel)]
        } else {
            vec![
                parent.join(format!("{name}.rs")),
                parent.join(name).join("mod.rs"),
            ]
        };
        for candidate in candidates {
            collect_mod_graph(crate_dir, &candidate, out)?;
        }
    }
    Ok(())
}

fn has_deserialize(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        if !attr.path().is_ident("derive") {
            return false;
        }
        let Ok(meta) = attr.parse_args_with(
            syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
        ) else {
            return false;
        };
        meta.iter().any(|path| {
            path.segments
                .last()
                .map(|seg| seg.ident == "Deserialize")
                .unwrap_or(false)
        })
    })
}

fn struct_fields(
    fields: &Fields,
    rename_all: Option<&str>,
    container_default: bool,
) -> Result<Vec<FieldSpec>, String> {
    let Fields::Named(named) = fields else {
        return Ok(Vec::new());
    };
    let mut out = Vec::new();
    for field in &named.named {
        if serde_flag(&field.attrs, "skip") || serde_flag(&field.attrs, "skip_deserializing") {
            continue;
        }
        let ident = field
            .ident
            .as_ref()
            .ok_or_else(|| "unnamed plugin config field".to_string())?
            .to_string();
        let ident = ident.strip_prefix("r#").unwrap_or(&ident).to_string();
        let wire = match serde_str(&field.attrs, "rename") {
            Some(wire) => wire,
            None => rename_field(rename_all, &ident)?,
        };
        let optional =
            container_default || is_option(&field.ty) || serde_flag(&field.attrs, "default");
        out.push(FieldSpec {
            ident,
            yaml_path: wire,
            optional,
            secret: parse_secret_attr(&field.attrs),
            rust_ty: type_to_string(&field.ty),
            doc: doc_string(&field.attrs),
        });
    }
    Ok(out)
}

fn is_option(ty: &Type) -> bool {
    if let Type::Path(path) = ty {
        path.path
            .segments
            .last()
            .map(|seg| seg.ident == "Option")
            .unwrap_or(false)
    } else {
        false
    }
}

fn parse_secret_attr(attrs: &[Attribute]) -> SecretKind {
    for attr in attrs {
        if !attr.path().is_ident("skippr") {
            continue;
        }
        let tokens = quote::ToTokens::to_token_stream(attr).to_string();
        if tokens.contains("secret_path") {
            return SecretKind::SecretPath;
        }
        if tokens.contains("not_secret") {
            return SecretKind::NotSecret;
        }
        if tokens.contains("secret") {
            return SecretKind::Secret;
        }
    }
    SecretKind::None
}

fn type_to_string(ty: &Type) -> String {
    quote::ToTokens::to_token_stream(ty)
        .to_string()
        .replace(' ', "")
}

fn path_ends_with(path: &syn::Path, name: &str) -> bool {
    path.segments
        .last()
        .map(|seg| seg.ident == name)
        .unwrap_or(false)
}

pub fn heuristic_secret(ident: &str) -> Option<SecretKind> {
    if ident.ends_with("_token_url") {
        return Some(SecretKind::NotSecret);
    }
    if ident.ends_with("_path")
        && (ident.contains("private_key")
            || ident.contains("credential")
            || ident.contains("service_account")
            || ident.contains("json"))
    {
        return Some(SecretKind::SecretPath);
    }
    if ident == "password"
        || ident == "sasl_password"
        || ident == "connection_string"
        || ident == "private_key_pem"
        || ident == "credentials_json"
        || ident == "api_key"
        || ident == "account_key"
        || ident == "sas_token"
        || ident == "consumer_key"
        || ident == "oauth_consumer_key"
        || ident.ends_with("_secret")
        || ident.ends_with("_token")
        || ident == "token"
        || ident == "developer_token"
    {
        return Some(SecretKind::Secret);
    }
    None
}

fn validate_secrets(crate_name: &str, fields: &[FieldSpec]) -> Result<(), String> {
    for field in fields {
        let leaf = field
            .yaml_path
            .rsplit('.')
            .next()
            .unwrap_or(field.ident.as_str());
        if let Some(expected) = heuristic_secret(leaf) {
            match (expected, field.secret) {
                (_, SecretKind::Secret | SecretKind::SecretPath | SecretKind::NotSecret) => {}
                (
                    SecretKind::Secret | SecretKind::SecretPath | SecretKind::NotSecret,
                    SecretKind::None,
                ) => {
                    return Err(format!(
                        "{crate_name}.{} matches the secret heuristic but is unmarked; add #[skippr(secret|secret_path|not_secret)]",
                        field.ident
                    ));
                }
                _ => {}
            }
        }
    }
    Ok(())
}

pub fn to_kebab(plugin_name: &str) -> String {
    let chars: Vec<char> = plugin_name.chars().collect();
    let mut out = String::new();
    for (i, c) in chars.iter().copied().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                let prev = chars[i - 1];
                let next_lower = chars
                    .get(i + 1)
                    .copied()
                    .map(|n| n.is_lowercase())
                    .unwrap_or(false);
                if prev.is_lowercase()
                    || prev.is_ascii_digit()
                    || (prev.is_uppercase() && next_lower)
                {
                    out.push('-');
                }
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

pub fn emit_kinds_rs(plugins: &[PluginSpec]) -> String {
    let mut out = String::from(GENERATED_PREAMBLE);
    out.push('\n');
    out.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    out.push_str("pub enum ConnectPlugin {\n");
    for plugin in plugins {
        let variant = format!("{:?}{}", plugin.kind, plugin.plugin_name);
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("}\n\n");
    out.push_str("impl ConnectPlugin {\n");
    out.push_str("    pub fn role(self) -> ConnectRole {\n        match self {\n");
    for plugin in plugins {
        let variant = format!("{:?}{}", plugin.kind, plugin.plugin_name);
        let role = match plugin.kind {
            PluginKind::DataSource => "DataSource",
            PluginKind::DataSink => "DataSink",
            PluginKind::SchemaSink => "SchemaSink",
        };
        out.push_str(&format!(
            "            Self::{variant} => ConnectRole::{role},\n"
        ));
    }
    out.push_str("        }\n    }\n");
    out.push_str("    pub fn plugin_name(self) -> &'static str {\n        match self {\n");
    for plugin in plugins {
        let variant = format!("{:?}{}", plugin.kind, plugin.plugin_name);
        out.push_str(&format!(
            "            Self::{variant} => \"{}\",\n",
            plugin.plugin_name
        ));
    }
    out.push_str("        }\n    }\n");
    out.push_str(
        "    pub fn secret_fields(self) -> &'static [&'static str] {\n        match self {\n",
    );
    for plugin in plugins {
        let variant = format!("{:?}{}", plugin.kind, plugin.plugin_name);
        let secrets: Vec<String> = plugin
            .fields
            .iter()
            .filter(|f| matches!(f.secret, SecretKind::Secret))
            .map(|f| format!("\"{}\"", f.yaml_path))
            .collect();
        out.push_str(&format!(
            "            Self::{variant} => &[{}],\n",
            secrets.join(", ")
        ));
    }
    out.push_str("        }\n    }\n");
    out.push_str(
        "    pub fn yaml_path_for(self, ident: &str) -> Option<&'static str> {\n        match (self, ident) {\n",
    );
    for plugin in plugins {
        let variant = format!("{:?}{}", plugin.kind, plugin.plugin_name);
        for field in &plugin.fields {
            if clap_skip_field(&field.ident) {
                continue;
            }
            out.push_str(&format!(
                "            (Self::{variant}, \"{}\") => Some(\"{}\"),\n",
                field.ident, field.yaml_path
            ));
        }
    }
    out.push_str("            _ => None,\n        }\n    }\n}\n\n");

    fn emit_kind_enum(out: &mut String, name: &str, plugins: &[PluginSpec]) {
        out.push_str(&format!(
            "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum {name} {{\n"
        ));
        for plugin in plugins {
            out.push_str(&format!("    {},\n", ident_ok(&plugin.plugin_name)));
        }
        out.push_str("}\n\n");
        out.push_str(&format!(
            "impl {name} {{\n    pub fn plugin(self) -> ConnectPlugin {{\n        match self {{\n"
        ));
        for plugin in plugins {
            out.push_str(&format!(
                "            Self::{} => ConnectPlugin::{:?}{},\n",
                ident_ok(&plugin.plugin_name),
                plugin.kind,
                plugin.plugin_name
            ));
        }
        out.push_str("        }\n    }\n");
        out.push_str(
            "    pub fn parse(raw: &str) -> Option<Self> {\n        match raw.trim().to_ascii_lowercase().as_str() {\n",
        );
        for plugin in plugins {
            out.push_str(&format!(
                "            {:?} => Some(Self::{}),\n",
                plugin.plugin_name.to_ascii_lowercase(),
                ident_ok(&plugin.plugin_name)
            ));
        }
        out.push_str("            _ => None,\n        }\n    }\n");
        out.push_str(
            "    pub fn plugin_name(self) -> &'static str {\n        self.plugin().plugin_name()\n    }\n}\n\n",
        );
    }
    let sources: Vec<_> = plugins
        .iter()
        .filter(|p| p.kind == PluginKind::DataSource)
        .cloned()
        .collect();
    let sinks: Vec<_> = plugins
        .iter()
        .filter(|p| p.kind == PluginKind::DataSink)
        .cloned()
        .collect();
    let schemas: Vec<_> = plugins
        .iter()
        .filter(|p| p.kind == PluginKind::SchemaSink)
        .cloned()
        .collect();
    emit_kind_enum(&mut out, "DataSource", &sources);
    emit_kind_enum(&mut out, "DataSink", &sinks);
    emit_kind_enum(&mut out, "SchemaSink", &schemas);
    out
}

pub fn emit_cli_rs(plugins: &[PluginSpec]) -> String {
    let mut out = String::from(GENERATED_PREAMBLE);
    out.push_str("use clap::Parser;\n");
    out.push_str("use serde::Serialize;\n");
    out.push_str("use std::collections::BTreeMap;\n");
    out.push_str("use crate::connect::{ConnectPlugin, ConnectRole, YamlArg};\n\n");
    out.push_str("#[derive(Parser, Clone, PartialEq)]\n");
    out.push_str(
        "pub struct ConnectArgs {\n    #[command(subcommand)]\n    pub role: ConnectRoleCmd,\n}\n\n",
    );
    out.push_str("#[derive(Parser, Clone, PartialEq)]\n#[command(rename_all = \"kebab-case\")]\n");
    out.push_str("pub enum ConnectRoleCmd {\n");
    out.push_str("    DataSource {\n        #[command(subcommand)]\n        kind: DataSourceKindCmd,\n    },\n");
    out.push_str(
        "    DataSink {\n        #[command(subcommand)]\n        kind: DataSinkKindCmd,\n    },\n",
    );
    out.push_str("    SchemaSink {\n        #[command(subcommand)]\n        kind: SchemaSinkKindCmd,\n    },\n}\n\n");

    fn args_name(plugin: &PluginSpec) -> String {
        format!("{:?}{}Args", plugin.kind, plugin.plugin_name)
    }

    fn emit_kind_enum(out: &mut String, name: &str, plugins: &[PluginSpec]) {
        out.push_str(&format!(
            "#[derive(Parser, Clone, PartialEq)]\npub enum {name} {{\n"
        ));
        for plugin in plugins {
            out.push_str(&format!(
                "    #[command(name = \"{}\")]\n    {}({}),\n",
                to_kebab(&plugin.plugin_name),
                ident_ok(&plugin.plugin_name),
                args_name(plugin)
            ));
        }
        out.push_str("}\n\n");
    }

    fn emit_args_struct(out: &mut String, plugin: &PluginSpec) {
        out.push_str("#[derive(Parser, Clone, PartialEq, Default, Serialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", args_name(plugin)));
        out.push_str("    #[arg(long)]\n    #[serde(skip)]\n    pub pipeline: Option<String>,\n");
        out.push_str("    #[arg(long)]\n    #[serde(skip)]\n    pub name: Option<String>,\n");
        for field in &plugin.fields {
            if clap_skip_field(&field.ident) {
                continue;
            }
            let ident = ident_ok(&field.ident);
            if is_string_list(&field.rust_ty) {
                out.push_str(&format!(
                    "    #[arg(long)]\n    #[serde(skip_serializing_if = \"Vec::is_empty\")]\n    pub {ident}: Vec<String>,\n"
                ));
            } else if is_yaml_arg_ty(&field.rust_ty) {
                out.push_str(&format!(
                    "    #[arg(long)]\n    #[serde(skip_serializing_if = \"Option::is_none\")]\n    pub {ident}: Option<YamlArg>,\n"
                ));
            } else {
                out.push_str(&format!(
                    "    #[arg(long)]\n    #[serde(skip_serializing_if = \"Option::is_none\")]\n    pub {ident}: Option<String>,\n"
                ));
            }
        }
        out.push_str("}\n\n");
        out.push_str(&format!(
            "impl {} {{\n    pub fn to_yaml_map(&self) -> BTreeMap<String, serde_yaml::Value> {{\n        crate::connect::yaml_map_from_serialize(self)\n    }}\n}}\n\n",
            args_name(plugin)
        ));
    }

    let sources: Vec<_> = plugins
        .iter()
        .filter(|p| p.kind == PluginKind::DataSource)
        .cloned()
        .collect();
    let sinks: Vec<_> = plugins
        .iter()
        .filter(|p| p.kind == PluginKind::DataSink)
        .cloned()
        .collect();
    let schemas: Vec<_> = plugins
        .iter()
        .filter(|p| p.kind == PluginKind::SchemaSink)
        .cloned()
        .collect();
    emit_kind_enum(&mut out, "DataSourceKindCmd", &sources);
    emit_kind_enum(&mut out, "DataSinkKindCmd", &sinks);
    emit_kind_enum(&mut out, "SchemaSinkKindCmd", &schemas);
    for plugin in plugins {
        emit_args_struct(&mut out, plugin);
    }

    out.push_str(
        "impl ConnectRoleCmd {\n    pub fn role(&self) -> ConnectRole {\n        match self {\n",
    );
    out.push_str("            Self::DataSource { .. } => ConnectRole::DataSource,\n");
    out.push_str("            Self::DataSink { .. } => ConnectRole::DataSink,\n");
    out.push_str("            Self::SchemaSink { .. } => ConnectRole::SchemaSink,\n");
    out.push_str(
        "        }\n    }\n    pub fn plugin(&self) -> ConnectPlugin {\n        match self {\n",
    );
    for plugin in &sources {
        out.push_str(&format!(
            "            Self::DataSource {{ kind: DataSourceKindCmd::{}(_) }} => ConnectPlugin::DataSource{},\n",
            ident_ok(&plugin.plugin_name),
            plugin.plugin_name
        ));
    }
    for plugin in &sinks {
        out.push_str(&format!(
            "            Self::DataSink {{ kind: DataSinkKindCmd::{}(_) }} => ConnectPlugin::DataSink{},\n",
            ident_ok(&plugin.plugin_name),
            plugin.plugin_name
        ));
    }
    for plugin in &schemas {
        out.push_str(&format!(
            "            Self::SchemaSink {{ kind: SchemaSinkKindCmd::{}(_) }} => ConnectPlugin::SchemaSink{},\n",
            ident_ok(&plugin.plugin_name),
            plugin.plugin_name
        ));
    }
    out.push_str(
        "        }\n    }\n    pub fn pipeline(&self) -> Option<&str> {\n        match self {\n",
    );
    for plugin in &sources {
        out.push_str(&format!(
            "            Self::DataSource {{ kind: DataSourceKindCmd::{}(args) }} => args.pipeline.as_deref(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    for plugin in &sinks {
        out.push_str(&format!(
            "            Self::DataSink {{ kind: DataSinkKindCmd::{}(args) }} => args.pipeline.as_deref(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    for plugin in &schemas {
        out.push_str(&format!(
            "            Self::SchemaSink {{ kind: SchemaSinkKindCmd::{}(args) }} => args.pipeline.as_deref(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    out.push_str(
        "        }\n    }\n    pub fn name(&self) -> Option<&str> {\n        match self {\n",
    );
    for plugin in &sources {
        out.push_str(&format!(
            "            Self::DataSource {{ kind: DataSourceKindCmd::{}(args) }} => args.name.as_deref(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    for plugin in &sinks {
        out.push_str(&format!(
            "            Self::DataSink {{ kind: DataSinkKindCmd::{}(args) }} => args.name.as_deref(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    for plugin in &schemas {
        out.push_str(&format!(
            "            Self::SchemaSink {{ kind: SchemaSinkKindCmd::{}(args) }} => args.name.as_deref(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    out.push_str(
        "        }\n    }\n    pub fn to_yaml_map(&self) -> BTreeMap<String, serde_yaml::Value> {\n        match self {\n",
    );
    for plugin in &sources {
        out.push_str(&format!(
            "            Self::DataSource {{ kind: DataSourceKindCmd::{}(args) }} => args.to_yaml_map(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    for plugin in &sinks {
        out.push_str(&format!(
            "            Self::DataSink {{ kind: DataSinkKindCmd::{}(args) }} => args.to_yaml_map(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    for plugin in &schemas {
        out.push_str(&format!(
            "            Self::SchemaSink {{ kind: SchemaSinkKindCmd::{}(args) }} => args.to_yaml_map(),\n",
            ident_ok(&plugin.plugin_name)
        ));
    }
    out.push_str("        }\n    }\n}\n");
    out
}

fn ident_ok(name: &str) -> String {
    if name
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        format!("P{name}")
    } else if is_rust_keyword(name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn is_rust_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "box"
            | "try"
            | "union"
            | "yield"
    )
}

fn is_string_list(ty: &str) -> bool {
    let compact = ty.replace(' ', "");
    compact.contains("Vec<String>") || compact.contains("Vec<&str>")
}

fn is_yaml_arg_ty(ty: &str) -> bool {
    let name = rust_type_name(ty);
    (ty.contains("Vec<") && !is_string_list(ty))
        || ty.contains("HashMap")
        || ty.contains("BTreeMap")
        || ty.contains("BTreeSet")
        || name == "TargetEntry"
        || name == "CompetitorEntry"
}

fn clap_skip_field(ident: &str) -> bool {
    matches!(
        ident,
        "name" | "pipeline" | "save" | "data_source" | "data_sink" | "schema_sink"
    )
}

pub fn format_generated_rs(src: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|err| format!("rustfmt spawn: {err}"))?;
    child
        .stdin
        .take()
        .ok_or_else(|| "rustfmt stdin".to_string())?
        .write_all(src.as_bytes())
        .map_err(|err| format!("rustfmt stdin: {err}"))?;
    let output = child
        .wait_with_output()
        .map_err(|err| format!("rustfmt wait: {err}"))?;
    if !output.status.success() {
        return Err(format!(
            "rustfmt failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout).map_err(|err| format!("rustfmt stdout: {err}"))
}

/// Engine config structs (`Pipeline`, `Transform`, ...) and `PairedSink`.
pub fn discover_engine(root: &Path) -> Result<EngineSpec, String> {
    let path = root.join("src/helpers/configuration.rs");
    let text =
        fs::read_to_string(&path).map_err(|err| format!("read {}: {err}", path.display()))?;
    let parsed =
        syn::parse_file(&text).map_err(|err| format!("parse {}: {err}", path.display()))?;
    let paired_sinks = parsed
        .items
        .iter()
        .find_map(|item| match item {
            Item::Enum(item) if item.ident == "PairedSink" => Some(
                item.variants
                    .iter()
                    .map(|v| v.ident.to_string())
                    .collect::<Vec<_>>(),
            ),
            _ => None,
        })
        .ok_or_else(|| format!("{}: enum PairedSink not found", path.display()))?;
    Ok(EngineSpec {
        types: reflect_source_file(&path)?,
        paired_sinks,
    })
}

/// Every generated file, relative to the workspace root, with its contents.
pub struct Generated {
    pub files: Vec<(&'static str, String)>,
}

pub fn generated_sources(plugins: &[PluginSpec], engine: &EngineSpec) -> Result<Generated, String> {
    let model = python::python_model(plugins, engine)?;
    Ok(Generated {
        files: vec![
            (
                "src/connect_generated.rs",
                format_generated_rs(&emit_kinds_rs(plugins))?,
            ),
            (
                "src/cli/connect_generated.rs",
                format_generated_rs(&emit_cli_rs(plugins))?,
            ),
            (
                "python/src/connect_generated.rs",
                format_generated_rs(&python::emit_python_rs(&model))?,
            ),
            ("skippr.pyi", python::emit_python_stub(&model)),
        ],
    })
}

/// Paths whose checked-in contents differ from `generated`.
pub fn stale_files(root: &Path, generated: &Generated) -> Vec<&'static str> {
    generated
        .files
        .iter()
        .filter(|(path, text)| fs::read_to_string(root.join(path)).ok().as_deref() != Some(text))
        .map(|(path, _)| *path)
        .collect()
}

pub fn write_generated(root: &Path, generated: &Generated) -> Result<(), String> {
    for (path, text) in &generated.files {
        fs::write(root.join(path), text).map_err(|err| format!("write {path}: {err}"))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .map(PathBuf::from)
            .expect("workspace root")
    }

    #[test]
    fn generated_files_are_rustfmt_stable() {
        let plugins = discover_plugins(&root()).expect("plugins");
        let engine = discover_engine(&root()).expect("engine");
        let generated = generated_sources(&plugins, &engine).expect("format generated");
        for (path, text) in &generated.files {
            if !path.ends_with(".rs") {
                assert!(
                    text.starts_with("# @generated by skippr-connect-gen. Do not edit.\n"),
                    "{path} keeps the skippr-connect-gen banner"
                );
                continue;
            }
            assert!(
                text.starts_with("// @generated by skippr-connect-gen. Do not edit.\n"),
                "{path} keeps the skippr-connect-gen banner"
            );
            assert!(
                !text.contains("rustfmt::skip"),
                "{path} must compile on stable rustc"
            );
            let again = format_generated_rs(text).expect("reformat");
            assert_eq!(text, &again, "pinned rustfmt must be a no-op on {path}");
        }
    }

    #[test]
    fn discovers_s3_and_nested_http_auth_secrets() {
        let plugins = discover_plugins(&root()).expect("plugins");
        let s3 = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSource && p.plugin_name == "S3")
            .expect("S3");
        assert!(s3
            .fields
            .iter()
            .any(|f| f.ident == "s3_bucket" && !f.optional));
        let http = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSource && p.plugin_name == "HttpClient")
            .expect("HttpClient");
        let password = http
            .fields
            .iter()
            .find(|f| f.yaml_path == "auth.password")
            .expect("auth.password");
        assert_eq!(password.secret, SecretKind::Secret);
        let lake = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSink && p.plugin_name == "SkipprLake")
            .expect("SkipprLake");
        assert!(lake.fields.iter().any(|f| {
            f.yaml_path == "object_store.secret_access_key" && f.secret == SecretKind::Secret
        }));
    }

    #[test]
    fn kinds_map_typed_connect_plugin_not_names() {
        let plugins = discover_plugins(&root()).expect("plugins");
        let kinds = emit_kinds_rs(&plugins);
        assert!(
            !kinds.contains("from_role_and_name"),
            "ConnectPlugin identity must not be recovered from (role, name) strings"
        );
        assert!(
            kinds.contains("(Self::DataSourceOtlp, \"auth_token\") => Some(\"auth_token\")"),
            "Otlp auth_token must keep the flat yaml path"
        );
        assert!(
            kinds.contains("(Self::DataSourceHttpClient, \"auth_token\") => Some(\"auth.token\")"),
            "HttpClient auth_token must keep the nested yaml path"
        );
        assert!(
            kinds.contains("pub fn parse(raw: &str) -> Option<Self>"),
            "DataSource/DataSink/SchemaSink must parse plugin names"
        );
        assert!(
            kinds.contains("\"skipprlake\" => Some(Self::SkipprLake)"),
            "SkipprLake must parse case-insensitively"
        );
        assert!(
            kinds.contains("\"athenaiceberg\" => Some(Self::AthenaIceberg)"),
            "AthenaIceberg must parse case-insensitively"
        );
        assert!(
            !kinds.contains("\"azure\" => Some(Self::AzureBlob)"),
            "Azure is not an alias of AzureBlob"
        );
    }

    #[test]
    fn string_enums_stay_scalar_tagged_enums_expand() {
        let plugins = discover_plugins(&root()).expect("plugins");
        let stripe = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSource && p.plugin_name == "Stripe")
            .expect("Stripe");
        assert!(
            stripe
                .fields
                .iter()
                .any(|f| f.ident == "stream_profile" && f.yaml_path == "stream_profile"),
            "StreamProfile is a string enum at stream_profile"
        );
        assert!(
            !stripe
                .fields
                .iter()
                .any(|f| f.ident == "stream_profile_type" || f.yaml_path == "stream_profile.type"),
            "string enums must not invent .type maps"
        );
        let apple = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSource && p.plugin_name == "AppleAppStoreSerp")
            .expect("AppleAppStoreSerp");
        assert!(apple
            .fields
            .iter()
            .any(|f| f.ident == "entity" && f.yaml_path == "entity"));
        assert!(!apple.fields.iter().any(|f| f.ident == "entity_type"));
        let lake = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSink && p.plugin_name == "SkipprLake")
            .expect("SkipprLake");
        assert!(
            lake.fields
                .iter()
                .any(|f| f.ident == "warehouse" && f.yaml_path == "warehouse" && !f.optional),
            "SkipprLake warehouse is required and flat"
        );
        assert!(
            lake.fields.iter().any(|f| f.ident == "catalog_table"
                && f.yaml_path == "catalog_table"
                && !f.optional),
            "SkipprLake catalog_table is required and flat"
        );
        assert!(
            lake.fields
                .iter()
                .any(|f| f.ident == "object_store_type" && f.yaml_path == "object_store.type"),
            "WarehouseObjectStore must expand under object_store, not a scalar object_store"
        );
        assert!(
            lake.fields.iter().any(|f| {
                f.yaml_path == "object_store.secret_access_key" && f.secret == SecretKind::Secret
            }),
            "R2 secret_access_key must be a connect secret path"
        );
        assert!(
            !lake
                .fields
                .iter()
                .any(|f| f.ident == "object_store" && f.rust_ty.contains("WarehouseObjectStore")),
            "object_store must not remain an unexpanded WarehouseObjectStore leaf"
        );
        assert!(
            !lake
                .fields
                .iter()
                .any(|f| f.yaml_path.starts_with("catalog.")
                    || f.yaml_path == "table_prefix"
                    || f.yaml_path == "query_engine.type"),
            "removed Iceberg keys must not appear on SkipprLake"
        );
        let athena_iceberg = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSink && p.plugin_name == "AthenaIceberg")
            .expect("AthenaIceberg");
        for required in [
            "warehouse",
            "glue_database_name",
            "athena_workgroup_name",
            "athena_results_s3_bucket",
        ] {
            assert!(
                athena_iceberg
                    .fields
                    .iter()
                    .any(|f| f.ident == required && f.yaml_path == required && !f.optional),
                "AthenaIceberg {required} is required and flat"
            );
        }
        assert!(
            !athena_iceberg.fields.iter().any(|f| {
                f.yaml_path.starts_with("catalog.")
                    || f.yaml_path == "table_prefix"
                    || f.yaml_path == "query_engine.type"
                    || f.yaml_path == "table_location_prefix"
            }),
            "removed Iceberg keys must not appear on AthenaIceberg"
        );
        for plugin_name in [
            "AthenaIceberg",
            "SkipprLake",
            "Duckdb",
            "Postgres",
            "Snowflake",
            "Bigquery",
            "Clickhouse",
            "Databricks",
            "Motherduck",
            "Redshift",
            "Synapse",
        ] {
            let plugin = plugins
                .iter()
                .find(|p| p.kind == PluginKind::DataSink && p.plugin_name == plugin_name)
                .unwrap_or_else(|| panic!("{plugin_name} data sink"));
            assert!(
                !plugin.fields.iter().any(|f| f.ident == "format"),
                "{plugin_name} writes rows into tables (SQL or Iceberg), not Parquet or JSON Lines files, so it has no `format` field. Remove `format` from the plugin config struct."
            );
        }
        for plugin_name in ["Athena", "File", "S3", "Gcs", "AzureBlob", "Sftp", "Amqp"] {
            let plugin = plugins
                .iter()
                .find(|p| p.kind == PluginKind::DataSink && p.plugin_name == plugin_name)
                .unwrap_or_else(|| panic!("{plugin_name} data sink"));
            assert!(
                plugin.fields.iter().any(|f| f.ident == "format"),
                "{plugin_name} writes Parquet or JSON Lines files and must expose a `format` field so users can set parquet (default) or jsonl where supported. Add `format: Option<String>` to the plugin config struct."
            );
        }
        let kinds = emit_kinds_rs(&plugins);
        for variant in [
            "DataSinkAthenaIceberg",
            "DataSinkSkipprLake",
            "DataSinkDuckdb",
            "DataSinkPostgres",
            "DataSinkSnowflake",
            "DataSinkBigquery",
            "DataSinkClickhouse",
            "DataSinkDatabricks",
            "DataSinkMotherduck",
            "DataSinkRedshift",
            "DataSinkSynapse",
        ] {
            assert!(
                !kinds.contains(&format!("(Self::{variant}, \"format\")")),
                "{variant} writes rows into tables (SQL or Iceberg), not files, so connect must not generate `format`. Remove `format` from the plugin config struct."
            );
        }
        assert!(
            kinds.contains("(Self::DataSinkAthena, \"format\") => Some(\"format\")"),
            "Athena writes Parquet files and must map `format` so users can set parquet (jsonl is not supported yet)."
        );
        let duckdb = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSink && p.plugin_name == "Duckdb")
            .expect("Duckdb");
        for required in ["warehouse", "table_namespace"] {
            assert!(
                duckdb
                    .fields
                    .iter()
                    .any(|f| f.ident == required && f.yaml_path == required && !f.optional),
                "Duckdb {required} is required and flat"
            );
        }
        assert!(
            !duckdb.fields.iter().any(|f| {
                f.yaml_path.starts_with("catalog.")
                    || f.yaml_path == "query_engine.type"
                    || f.yaml_path == "path"
                    || f.yaml_path == "schema"
                    || f.yaml_path.starts_with("object_store")
            }),
            "Duckdb must not grow catalog, query_engine, path, schema, or object_store"
        );
    }

    #[test]
    fn connect_docs_flags_exist_on_generated_cli() {
        let plugins = discover_plugins(&root()).expect("plugins");
        let mut allowed_flags: BTreeSet<String> = [
            "pipeline",
            "name",
            "workspace",
            "storage_mode",
            "config",
            "log",
            "wal_storage",
            "wal_s3_bucket",
            "store_type",
            "store_name",
            "skippr_s3_bucket",
            "tenant",
            "help",
        ]
        .into_iter()
        .map(str::to_string)
        .collect();
        let mut allowed_kinds: BTreeSet<String> = BTreeSet::new();
        for plugin in &plugins {
            allowed_kinds.insert(to_kebab(&plugin.plugin_name));
            for field in &plugin.fields {
                if clap_skip_field(&field.ident) {
                    continue;
                }
                allowed_flags.insert(field.ident.clone());
            }
        }
        let docs = root().join("docs");
        let mut unknown = Vec::new();
        for entry in walkdir::WalkDir::new(&docs).into_iter().flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("md") {
                continue;
            }
            let text = fs::read_to_string(path).unwrap();
            if !text.contains("skipprd connect") {
                continue;
            }
            for finding in connect_doc_mismatches(&text, &allowed_flags, &allowed_kinds) {
                unknown.push(format!("{}: {finding}", path.display()));
            }
        }
        assert!(
            unknown.is_empty(),
            "connect docs invent CLI surface not on generated clap:\n{}",
            unknown.join("\n")
        );
    }

    #[test]
    fn kind_cli_names_use_to_kebab() {
        let plugins = discover_plugins(&root()).expect("plugins");
        let cli = emit_cli_rs(&plugins);
        for plugin in &plugins {
            let needle = format!("#[command(name = \"{}\")]", to_kebab(&plugin.plugin_name));
            assert!(
                cli.contains(&needle),
                "kind CLI name must be to_kebab, missing {needle}"
            );
        }
        assert!(
            !cli.contains("#[command(rename_all = \"kebab-case\")]\npub enum DataSourceKindCmd"),
            "kind enums must not derive names from clap rename_all"
        );
    }

    #[test]
    fn cli_to_yaml_map_uses_serde_and_keeps_collections() {
        let plugins = discover_plugins(&root()).expect("plugins");
        let cli = emit_cli_rs(&plugins);
        assert!(
            cli.contains("serde::Serialize"),
            "CLI args must derive Serialize so to_yaml_map is serde"
        );
        assert!(
            cli.contains("yaml_map_from_serialize"),
            "to_yaml_map must serialize, not insert per-field strings"
        );
        assert!(
            !cli.contains("fields.insert("),
            "per-field insert loops are illegal once Serialize exists"
        );
        assert!(
            cli.contains("#[serde(skip)]"),
            "pipeline/name must not appear in plugin YAML"
        );
        let postgres = plugins
            .iter()
            .find(|p| p.kind == PluginKind::DataSource && p.plugin_name == "Postgres")
            .expect("Postgres");
        assert!(
            postgres
                .fields
                .iter()
                .any(|f| f.ident == "tables" && f.rust_ty.contains("Vec<")),
            "Postgres tables is a collection connect must expose"
        );
        assert!(
            cli.contains("pub tables: Vec<String>"),
            "CLI must accept repeated --tables, not skip Vec"
        );
        assert!(
            cli.contains("pub object_store_type: Option<String>"),
            "CLI must flatten object_store.type, not Option<String> object_store"
        );
        assert!(
            !cli.contains("pub object_store: Option<String>"),
            "unexpanded WarehouseObjectStore leaf is illegal"
        );
    }

    fn python_outputs() -> (String, String) {
        let plugins = discover_plugins(&root()).expect("plugins");
        let engine = discover_engine(&root()).expect("engine");
        let model = python::python_model(&plugins, &engine).expect("python model");
        (
            python::emit_python_rs(&model),
            python::emit_python_stub(&model),
        )
    }

    #[test]
    fn python_classes_are_role_prefixed_with_one_dispatch() {
        let (rs, stub) = python_outputs();
        for class in [
            "DataSourceS3",
            "DataSinkS3",
            "DataSinkFile",
            "DataSourcePostgres",
            "SchemaSinkGlue",
        ] {
            assert!(
                rs.contains(&format!("name = \"{class}\"")),
                "{class} must be a generated pyclass"
            );
            assert!(
                stub.contains(&format!("class {class}:")),
                "{class} must be in the stub"
            );
        }
        for paired in [
            "SchemaSinkSkipprLake",
            "SchemaSinkAthenaIceberg",
            "SchemaSinkDuckdb",
        ] {
            assert!(
                !rs.contains(&format!("name = \"{paired}\"")),
                "{paired} shares its data sink's config; it registers through data_sink(schema_sink=...)"
            );
        }
        for paired in ["AthenaIceberg", "SkipprLake", "Duckdb"] {
            assert!(
                rs.contains(&format!(
                    "plugin_entry(\"{paired}\", &*config.borrow()).map(SinkConfig::Paired)"
                )),
                "{paired} data sink must dispatch as a paired sink"
            );
        }
        assert!(rs.contains("map(SinkConfig::Unpaired)"));
        for gone in [
            "enum PyDataSource",
            "enum PyDataSink",
            "enum PySchemaSink",
            "PyConnect",
            "config_yaml",
        ] {
            assert!(
                !rs.contains(gone),
                "{gone} is the deleted kind-enum dispatch"
            );
        }
        assert!(
            stub.contains("PairedDataSinkConfig: TypeAlias = DataSinkAthenaIceberg | DataSinkDuckdb | DataSinkSkipprLake\n"),
            "paired sinks get their own alias for the data_sink overload"
        );
        let kinds = emit_kinds_rs(&discover_plugins(&root()).expect("plugins"));
        assert!(
            !kinds.contains("required_fields"),
            "required_fields only served PyConnect"
        );
    }

    #[test]
    fn python_required_fields_are_not_optional() {
        let (rs, stub) = python_outputs();
        let lake = rs
            .split("pub struct PyDataSinkSkipprLake {")
            .nth(1)
            .and_then(|rest| rest.split('}').next())
            .expect("PyDataSinkSkipprLake");
        assert!(
            lake.contains("pub warehouse: String,"),
            "warehouse is required: {lake}"
        );
        assert!(lake.contains("pub catalog_table: String,"));
        assert!(
            stub.contains("class DataSinkSkipprLake:")
                && stub
                    .contains("        *,\n        warehouse: str,\n        catalog_table: str,\n"),
            "required kwargs come first and have no None default"
        );
    }

    #[test]
    fn python_secret_fields_take_env_ref() {
        let (rs, stub) = python_outputs();
        let postgres = rs
            .split("pub struct PyDataSinkPostgres {")
            .nth(1)
            .and_then(|rest| rest.split('}').next())
            .expect("PyDataSinkPostgres");
        assert!(
            postgres.contains("pub password: PyEnvRef,")
                || postgres.contains("pub password: Option<PyEnvRef>,"),
            "secret fields accept only EnvRef: {postgres}"
        );
        assert!(stub.contains("password: EnvRef"));
        assert!(
            rs.contains("pub secret_access_key: PyEnvRef,"),
            "nested R2 secret_access_key is an EnvRef"
        );
    }

    #[test]
    fn python_tagged_enums_get_one_class_per_variant() {
        let (rs, stub) = python_outputs();
        for variant in ["File", "S3", "R2"] {
            let class = format!("DataSinkSkipprLakeWarehouseObjectStore{variant}");
            assert!(
                rs.contains(&format!(
                    "#[pyclass(frozen, from_py_object, name = \"{class}\""
                )),
                "{class} must be a frozen variant class"
            );
        }
        assert!(stub.contains(
            "DataSinkSkipprLakeWarehouseObjectStore: TypeAlias = (\n    DataSinkSkipprLakeWarehouseObjectStoreFile\n    | DataSinkSkipprLakeWarehouseObjectStoreS3\n    | DataSinkSkipprLakeWarehouseObjectStoreR2\n)\n"
        ));
        assert!(rs.contains("R2(PyDataSinkSkipprLakeWarehouseObjectStoreR2) = \"r2\""));
        assert!(
            !rs.contains("object_store_type"),
            "the tag comes from the variant class, not a `type` kwarg"
        );
        assert!(rs.contains("#[pyclass(from_py_object, name = \"DataSinkSkipprLake\""));
        assert!(stub.contains("    object_store: DataSinkSkipprLakeWarehouseObjectStore | None\n"));
    }

    #[test]
    fn python_string_enums_are_literals() {
        let (rs, stub) = python_outputs();
        assert!(stub.contains("BatchTimeUnit: TypeAlias = Literal[\"year\", \"month\", \"day\", \"hour\", \"minute\"]\n"));
        assert!(stub.contains("DataSourceStripeStreamProfile: TypeAlias = Literal["));
        assert!(
            !rs.contains("name = \"DataSourceStripeStreamProfile\""),
            "string enums are validated strings, not classes"
        );
        assert!(rs.contains("config_literal!(PyDataSourceStripeStreamProfile,"));
        assert!(
            !stub.contains("DataSourceDataForSeoSeoOpportunitiesSearchEngine: TypeAlias"),
            "one-value enums are spelled inline"
        );
        assert!(stub.contains("search_engine: Literal[\"google\"] | None"));
    }

    #[test]
    fn python_emits_fields_the_cli_skips() {
        let (rs, _) = python_outputs();
        let entry = rs
            .split("pub struct PyDataSourceDataForSeoBacklinksCompetitorEntry {")
            .nth(1)
            .and_then(|rest| rest.split('}').next())
            .expect("CompetitorEntry");
        assert!(
            entry.contains("pub name: "),
            "clap_skip_field is CLI-only: {entry}"
        );
    }

    #[test]
    fn python_pipeline_takes_typed_refs_and_engine_types() {
        let (rs, stub) = python_outputs();
        assert!(rs.contains("pub data_source: PyDataSourceRef,"));
        assert!(rs.contains("pub data_sink: Option<PyDataSinkRef>,"));
        assert!(rs.contains("pub deadletter_sink: Option<PyDeadletterSinkRef>,"));
        assert!(rs.contains("#[pyclass(from_py_object, name = \"Pipeline\""));
        assert!(rs.contains("#[pyclass(frozen, from_py_object, name = \"Transform\""));
        assert!(stub.contains("    data_source: DataSourceRef\n"));
        assert!(stub.contains("cls,\n        *,\n        data_source: DataSourceRef,\n"));
        assert!(stub.contains("    def batch_time_unit(self) -> BatchTimeUnit | None:\n"));
        assert!(stub.contains("    def flatten_events(self) -> bool | None:\n"));
        assert!(stub.contains("    def inject_fields(self) -> Mapping[str, Any] | None:\n"));
        assert!(stub.contains("        inject_fields: dict[str, Any] | None = None,\n"));
        assert!(stub.contains(
            "    def keywords(self) -> Sequence[str]:\n        \"\"\"YAML key `keywords`.\"\"\"\n        ...\n    @keywords.setter\n    def keywords(self, value: list[str]) -> None: ...\n"
        ));
        for class in [
            "Stats",
            "SemanticLayerSettings",
            "CdcPipelineConfig",
            "CdcNamespaceConfig",
        ] {
            assert!(
                stub.contains(&format!("class {class}:")),
                "{class} must be generated"
            );
        }
    }

    #[test]
    fn python_docs_flow_into_stub_and_help() {
        let (rs, stub) = python_outputs();
        assert!(stub.contains("Config for the `SkipprLake` data sink and schema sink."));
        assert!(rs.contains("#[doc = \"Config for the `SkipprLake` data sink and schema sink."));
        assert!(stub.contains("YAML key `object_store`."));
    }

    #[test]
    fn python_constructor_kwargs_carry_implementor_docs() {
        let (rs, stub) = python_outputs();
        assert!(
            stub.contains("class Pipeline:\n    \"\"\"One skipprd pipeline:"),
            "Pipeline class docstring is what an editor shows on hover"
        );
        assert!(
            stub.contains("Approve schema changes without prompting"),
            "Pipeline.auto_approve must describe the behaviour, not only the YAML key"
        );
        assert!(
            stub.contains("            auto_approve: Approve schema changes without prompting"),
            "constructor Args are what editors show when hovering a keyword argument"
        );
        assert!(
            rs.contains("Approve schema changes without prompting"),
            "PyO3 field/constructor docs must match the stub"
        );
        assert!(
            stub.contains("class Transform:\n    \"\"\"How source records are namespaced"),
            "Transform class docstring is missing"
        );
        assert!(
            stub.contains("Set `skippr.workspace`."),
            "Config.workspace hover docs live in stub_core.pyi"
        );
        assert!(
            stub.contains("Bucket to read."),
            "DataSourceS3.s3_bucket must describe the field"
        );
    }

    #[test]
    fn python_unknown_types_fail_generation() {
        let types = TypeCatalog::default();
        let plugin = PluginSpec {
            kind: PluginKind::DataSource,
            plugin_name: "Odd".into(),
            crate_name: "skippr-plugin-odd".into(),
            doc: String::new(),
            fields: Vec::new(),
            config_fields: vec![FieldSpec {
                ident: "when".into(),
                yaml_path: "when".into(),
                optional: false,
                secret: SecretKind::None,
                rust_ty: "chrono::DateTime<Utc>".into(),
                doc: String::new(),
            }],
            types,
        };
        let engine = EngineSpec {
            paired_sinks: Vec::new(),
            ..discover_engine(&root()).expect("engine")
        };
        let err = python::python_model(&[plugin], &engine)
            .err()
            .expect("unknown type errors");
        assert!(err.contains("no Python mapping"), "{err}");
    }

    #[test]
    fn serde_default_is_parsed_not_substring_matched() {
        let item: syn::ItemStruct = syn::parse_quote! {
            /// A config.
            #[derive(Deserialize)]
            struct Cfg {
                #[serde(deserialize_with = "default_like_name")]
                required: String,
                #[serde(default = "five")]
                with_default: u32,
                #[serde(default)]
                plain_default: bool,
                #[serde(rename = "wireName")]
                renamed: String,
                #[serde(skip)]
                skipped: String,
            }
        };
        let spec = reflect_struct(&item).expect("reflect");
        assert_eq!(spec.doc, "A config.");
        let by_ident: BTreeMap<_, _> = spec.fields.iter().map(|f| (f.ident.as_str(), f)).collect();
        assert!(!by_ident["required"].optional);
        assert!(by_ident["with_default"].optional);
        assert!(by_ident["plain_default"].optional);
        assert_eq!(by_ident["renamed"].yaml_path, "wireName");
        assert!(!by_ident.contains_key("skipped"));
        let container: syn::ItemStruct = syn::parse_quote! {
            #[derive(Deserialize)]
            #[serde(default)]
            struct Cfg { a: String }
        };
        assert!(reflect_struct(&container).expect("reflect").fields[0].optional);
    }

    #[test]
    fn checked_in_python_stub_is_current() {
        let plugins = discover_plugins(&root()).expect("plugins");
        let engine = discover_engine(&root()).expect("engine");
        let generated = generated_sources(&plugins, &engine).expect("generate");
        assert!(
            stale_files(&root(), &generated).is_empty(),
            "run cargo run -p skippr-connect-gen"
        );
    }

    #[test]
    fn connect_docs_do_not_require_sde() {
        let docs = root().join("docs");
        let mut couplings = Vec::new();
        for entry in walkdir::WalkDir::new(&docs).into_iter().flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("md") {
                continue;
            }
            let text = fs::read_to_string(path).unwrap();
            if !text.contains("skipprd connect") {
                continue;
            }
            for needle in [
                "cargo test -p sde",
                "test in `sde`",
                "parallel SDE",
                "`sde model`",
            ] {
                if text.contains(needle) {
                    couplings.push(format!("{}: {needle}", path.display()));
                }
            }
        }
        assert!(
            couplings.is_empty(),
            "skipprd connect docs must not require SDE:\n{}",
            couplings.join("\n")
        );
    }

    fn connect_doc_mismatches(
        text: &str,
        allowed_flags: &BTreeSet<String>,
        allowed_kinds: &BTreeSet<String>,
    ) -> Vec<String> {
        let mut findings = Vec::new();
        let mut in_code = false;
        for part in text.split("```") {
            if in_code {
                for cmd in connect_doc_commands(part) {
                    let tokens: Vec<&str> = cmd.split_whitespace().collect();
                    for window in tokens.windows(2) {
                        if matches!(window[0], "data-source" | "data-sink" | "schema-sink")
                            && !window[1].starts_with('-')
                            && window[1] != "<kebab-name>"
                            && !allowed_kinds.contains(window[1])
                        {
                            findings.push(format!("{} {}", window[0], window[1]));
                        }
                    }
                    let mut rest = cmd.as_str();
                    while let Some(idx) = rest.find("--") {
                        rest = &rest[idx + 2..];
                        let ident: String = rest
                            .chars()
                            .take_while(|c| {
                                c.is_ascii_lowercase() || c.is_ascii_digit() || *c == '-'
                            })
                            .collect();
                        if ident.is_empty() {
                            continue;
                        }
                        let flag = ident.replace('-', "_");
                        if !allowed_flags.contains(&flag) {
                            findings.push(format!("--{ident}"));
                        }
                    }
                    let template = cmd.contains("--help") || cmd.contains("<kebab-name>");
                    if !template {
                        if !cmd.contains("--pipeline") {
                            findings.push("missing --pipeline".into());
                        }
                        if !cmd.contains("--name") {
                            findings.push("missing --name".into());
                        }
                    }
                    let mut rest = cmd.as_str();
                    while let Some(idx) = rest.find("${") {
                        let quoted_single = idx >= 1 && rest.as_bytes()[idx - 1] == b'\'';
                        let end = rest[idx..]
                            .find('}')
                            .map(|off| idx + off + 1)
                            .unwrap_or(rest.len());
                        let refer = &rest[idx..end.min(rest.len())];
                        if !quoted_single {
                            findings.push(format!("{refer} must be single-quoted"));
                        }
                        rest = &rest[idx + 2..];
                    }
                }
            }
            in_code = !in_code;
        }
        findings
    }

    fn connect_doc_commands(block: &str) -> Vec<String> {
        let mut out = Vec::new();
        let mut cur = String::new();
        let mut collecting = false;
        for line in block.lines() {
            let trimmed = line.trim();
            if !collecting {
                if trimmed.contains("skipprd") && trimmed.contains(" connect") {
                    collecting = true;
                    cur = trimmed.trim_end_matches('\\').trim().to_string();
                    if !line.trim_end().ends_with('\\') {
                        out.push(std::mem::take(&mut cur));
                        collecting = false;
                    }
                }
                continue;
            }
            cur.push(' ');
            cur.push_str(trimmed.trim_end_matches('\\').trim());
            if !line.trim_end().ends_with('\\') {
                out.push(std::mem::take(&mut cur));
                collecting = false;
            }
        }
        if collecting && !cur.is_empty() {
            out.push(cur);
        }
        out
    }
}
