image: rust:latest

variables:
  COMPONENT_NAME: skipprd
  CONTAINER_IMAGE: $COMPONENT_NAME:$CI_COMMIT_REF_NAME
  CONTAINER_LATEST_IMAGE: $COMPONENT_NAME:latest
  CONTAINER_RELEASE_IMAGE: $COMPONENT_NAME:v3.0.0
  DOCKER_HUB_REPO: skippr
  ECR_HOST: 536671797322.dkr.ecr.eu-west-2.amazonaws.com
  AWS_ECR_REGISTRY: $ECR_HOST/$COMPONENT_NAME

services:
  - docker:dind

stages:
#  - qa
#  - build
#  - dockerize
  - e2e
  - publish

#before_script:
#  - rustup update && cargo update
#  - alias aws='docker run --rm -v $(pwd):/aws -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY amazon/aws-cli'

#cargo_lint:
#  stage: qa
#  script:
#    - rustup component add clippy
##    - cargo clippy -- -D warnings
##    - cargo clippy -- -A warnings
#  only:
#    - master
#    - tags
#
#cargo_test:
#  stage: qa
#  script:
#    - ls
##    - cargo test
#  only:
#    - master
#    - tags

#.cargo_build:
#  stage: build
#  only:
#    - master
#    - tags

#cargo_build:
#  extends: .cargo_build
#  script:
##    - cargo install cross --git https://github.com/cross-rs/cross
##    - cross build --target x86_64-unknown-linux-musl --release
#    - cargo build --target x86_64-unknown-linux-musl --release
#  artifacts:
#    paths:
#      - ./target

#docker_build:
#  image: docker:latest
#  stage: dockerize
##  before_script:
##    - rustup update && cargo update
#  script:
#    - docker build -t $CONTAINER_IMAGE -f Dockerfile .
##    - docker build -t $CONTAINER_IMAGE -f Dockerfile.mac_arm .
##    - docker build -t $CONTAINER_IMAGE -f Dockerfile.lambda .
#  after_script:
#    # Push to Docker Hub
#    - docker login -u skippr -p "$DOCKER_HUB_PASS"
#    - docker tag $CONTAINER_IMAGE $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
#    - docker push $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
#  only:
#    - master
#    - tags

s3_plugin:
  image: docker:latest
  stage: e2e
  script:
    - docker pull $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
    - docker run --name skippre2e -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-s3_plugin -e PIPELINE_ID=gitlab_test-s3_plugin -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - if [[ "$(docker logs skippre2e >& container-logs ; cat container-logs | grep -i 'Err' | wc -l)" -gt 0 ]]; then exit 1; fi
    - if [[ "$(docker container wait skippre2e)" -eq 1 ]]; then exit 1; fi
  only:
    - master
    - tags

chaos_mode:
  image: docker:latest
  stage: e2e
  script:
    - docker pull $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
    - docker run --name skippre2e1 -e CHAOS_MODE=yes -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/chaos_mode -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-chaos_mode -e PIPELINE_ID=gitlab_test-chaos_mode -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - docker run --name skippre2e2 -e CHAOS_MODE=yes -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/chaos_mode -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-chaos_mode -e PIPELINE_ID=gitlab_test-chaos_mode -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - docker run --name skippre2e3 -e CHAOS_MODE=yes -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/chaos_mode -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-chaos_mode -e PIPELINE_ID=gitlab_test-chaos_mode -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - docker run --name skippre2e4 -e CHAOS_MODE=yes -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/chaos_mode -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-chaos_mode -e PIPELINE_ID=gitlab_test-chaos_mode -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - docker run --name skippre2e5 -e CHAOS_MODE=yes -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/chaos_mode -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-chaos_mode -e PIPELINE_ID=gitlab_test-chaos_mode -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - if [[ "$(docker logs skippre2e5 >& container-logs ; cat container-logs | grep -i 'Err' | wc -l)" -gt 0 ]]; then exit 1; fi
    - if [[ "$(docker container wait skippre2e5)" -eq 1 ]]; then exit 1; fi
  only:
    - master
    - tags

flatten:
  image: docker:latest
  stage: e2e
  script:
    - docker pull $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
    - docker run --name skippre2e -e DATA_SOURCE_FLATTEN_EVENTS=yes -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/flatten -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-flatten -e PIPELINE_ID=gitlab_test-flatten -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - if [[ "$(docker logs skippre2e >& container-logs ; cat container-logs | grep -i 'Err' | wc -l)" -gt 0 ]]; then exit 1; fi
    - if [[ "$(docker container wait skippre2e)" -eq 1 ]]; then exit 1; fi
  only:
    - master
    - tags

event_types:
  image: docker:latest
  stage: e2e
  script:
    - docker pull $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
    - docker run --name skippre2e -e DATA_SOURCE_EVENT_TYPE_FIELDS="bike_id,hardware.manufacturer" -e DATA_SOURCE_FLATTEN_EVENTS=yes -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/flatten -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-flatten -e PIPELINE_ID=gitlab_test-flatten -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - if [[ "$(docker logs skippre2e >& container-logs ; cat container-logs | grep -i 'Err' | wc -l)" -gt 0 ]]; then exit 1; fi
    - if [[ "$(docker container wait skippre2e)" -eq 1 ]]; then exit 1; fi
  only:
    - master
    - tags

time_buckets:
  image: docker:latest
  stage: e2e
  script:
    - docker pull $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
    - docker run --name skippre2e -e DATA_OUTPUT_TIME_BUCKET=day -e DATA_OUTPUT_TIME_FIELDS=metadata.sent_time -e DATA_SOURCE_FLATTEN_EVENTS=yes -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3 -e S3_BUCKET=skpr-sample-data -e S3_PREFIX=small-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/flatten -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-flatten -e PIPELINE_ID=gitlab_test-flatten -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - if [[ "$(docker logs skippre2e >& container-logs ; cat container-logs | grep -i 'Err' | wc -l)" -gt 0 ]]; then exit 1; fi
    - if [[ "$(docker container wait skippre2e)" -eq 1 ]]; then exit 1; fi
  only:
    - master
    - tags

s3_inventory_plugin:
  image: docker:latest
  stage: e2e
  script:
    - docker pull $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
    - docker run --name skippre2e -e AWS_DEFAULT_REGION=eu-west-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATA_SOURCE_PLUGIN_NAME=s3_inventory -e S3_BUCKET=skpr-sample-data-output -e S3_PREFIX=skpr-sample-data/smail-files -e DATA_SOURCE_BATCH_SIZE_BYTES=2048000 -e DATA_OUTPUT_S3_BUCKET=skpr-sample-data-output -e DATA_OUTPUT_S3_PREFIX=bikehire/s3_inventory_plugin -e GLUE_DATABASE_NAME=bikehire -e ATHENA_WORKGROUP_NAME=bikehire -e PIPELINE_NAME=bikehire-s3_inventory_plugin -e PIPELINE_ID=gitlab_test-s3_inventory_plugin -e SKIPPR_API_TOKEN=B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg -e DATA_DIR=./ -e APP_ENV=dev skippr/skipprd:latest
    - if [[ "$(docker logs skippre2e >& container-logs ; cat container-logs | grep -i 'Err' | wc -l)" -gt 0 ]]; then exit 1; fi
    - if [[ "$(docker container wait skippre2e)" -eq 1 ]]; then exit 1; fi
  only:
    - master
    - tags

docker_push:
  image: docker:latest
  stage: publish
  script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker tag $CONTAINER_IMAGE $CONTAINER_RELEASE_IMAGE
#    - docker push $CONTAINER_RELEASE_IMAGE

    # Push to Docker Hub
    - docker login -u skippr -p "$DOCKER_HUB_PASS"
    - docker pull $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE
    - docker tag $DOCKER_HUB_REPO/$CONTAINER_LATEST_IMAGE $DOCKER_HUB_REPO/$CONTAINER_RELEASE_IMAGE
    - docker push $DOCKER_HUB_REPO/$CONTAINER_RELEASE_IMAGE

    # Push to AWS ECR
#    - pip install awscli
#    - docker login --username AWS --password $(aws ecr get-login-password --region $AWS_REGION) 536671797322.dkr.ecr.eu-west-2.amazonaws.com
##    - echo $AWS_ECR_PASSWORD | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY
#    - docker tag $CONTAINER_RELEASE_IMAGE $AWS_ECR_REGISTRY/$CONTAINER_RELEASE_IMAGE
#    - docker push $AWS_ECR_REGISTRY/$CONTAINER_RELEASE_IMAGE
  only:
    - master
    - tags