---
version: "3.7"
services:
  skipprd-source:
    platform: linux/amd64
#    depends_on:
#      - newrelic-php-daemon
#    image: skipprd_with_newrelic
    image: skipprd:perf
#    image: skipprd:build
    volumes:
      - /Users/huders2000/Documents/sites/skippr/skipprd/test-tmp:/data
    networks:
      - newrelic-php
    ports:
      - 8080:80
    environment:
      DATA_SOURCE_PLUGIN_NAME: "file"
      DATA_SOURCE_PATH:  '/data/input'

      DATA_SOURCE_FORMAT: 'json'

#      DATA_SOURCE_EVENT_TYPE_FIELDS: 'detail-type'

#      DATA_SOURCE_FLATTEN_EVENTS: 'true'

#      DATA_SOURCE_POLL_INTERVAL_SECONDS: 1

      DATA_SOURCE_MUTABLE_MODE: 'evolve'

      RUN_MODE: sync

      HOST: '192.168.1.14'
#      HOST: '172.21.0.14'

#      SKIPPR_API_ENDPOINT: "https://console.skippr.io"
#      SKIPPR_API_TOKEN: "sadg"

      DATA_DIR: '/data'
      TENANT_ID: 'skippr'
      PIPELINE_NAME: 'sample'
      PIPELINE_ID: '1'
      LICENSE_KEY: '94708298-498f-4c74-802c-ff359dd56cdf'
      LOG_LEVEL: 'INFO'
      APP_ENV: dev

  skipprd-output:
    platform: linux/amd64
#    depends_on:
#      - newrelic-php-daemon
#    image: skipprd_with_newrelic
    image: skipprd:perf
#    image: skipprd:build
    volumes:
      - /Users/huders2000/Documents/sites/skippr/skipprd/test-tmp:/data
    networks:
      newrelic-php:
        ipv4_address: 192.168.1.14
#        ipv4_address: 172.21.0.14
    ports:
      - 5544:5544
      - 8081:80
    environment:
      DATA_OUTPUT_PLUGIN_NAME: "file"
      DATA_OUTPUT_PATH: '/data/output'

#      DATA_OUTPUT_FLATTEN_EVENTS: 'true'

#      DATA_OUTPUT_TIME_BUCKET: day

#      DATA_OUTPUT_TIME_FIELDS: 'detail_system_datetime_posix_utc_seconds'

#      DATA_OUTPUT_PARTITION_BY_FIELDS: 'detail_type'

      DATA_OUTPUT_FORMAT: parquet

      RUN_MODE: sync

      DATA_OUTPUT_FLUSH_BYTES: '20000000'
      DATA_OUTPUT_FLUSH_SECONDS: '600'
      DATA_OUTPUT_FLUSH_RECORDS: '1000000'

#      SKIPPR_API_ENDPOINT: "https://console.skippr.io"
#      SKIPPR_API_TOKEN: "sadg"

      DATA_DIR: '/data'
      TENANT_ID: 'skippr'
      PIPELINE_NAME: 'sample'
      PIPELINE_ID: '1'
      LICENSE_KEY: '94708298-498f-4c74-802c-ff359dd56cdf'
      LOG_LEVEL: 'INFO'
      APP_ENV: dev

      MEM: 4096

#  newrelic-php-daemon:
#    container_name: newrelic-php-daemon
#    image: newrelic/php-daemon:9.17.0
#    ports:
#      - 31339:31339
#    networks:
#      - newrelic-php
#    environment:
#      LOGLEVEL: debug


networks:
  newrelic-php:
   name: newrelic-php
   driver: bridge
   ipam:
     driver: default
     config:
       - subnet: "192.168.1.0/24"
         gateway: "192.168.1.1"
#       - subnet: 172.21.0.0/24