skippr:
  api_token: B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg
  workspace: dev


pipelines:
  cloud_trail:
#    reset_offsets: yes
#    reset_metadata: yes
    auto_approve: yes
    env: dev
    buffer_threshold_bytes: 2000000
    buffer_threshold_seconds: 600
    transform:
      batch_time_fields: eventTime
      batch_time_unit: day
#      flatten_events: yes
      record_field_path: Records
      batch_partition_fields: eventSource
    input: data_inputs.cloud_trail

  device_data:
#    reset_offsets: yes
#    reset_metadata: yes
    auto_approve: yes
    env: dev
    buffer_threshold_bytes: 200000000
    buffer_threshold_seconds: 600
    transform:
      batch_time_fields: system.datetime_posix_utc_seconds
      batch_time_unit: day
      flatten_events: yes
    input: data_inputs.s3_device_data
    output: data_outputs.ds_datalake
##    schema: schema_outputs.glue_datalake
#    deadletter: data_deadletters.ccrussbucket

#  device_data_dev:
#    auto_approve: yes
##    env: prod
#    buffer_threshold_bytes: 20000000
#    buffer_threshold_seconds: 600
#    transform:
#      batch_time_fields: system.datetime_posix_utc_seconds
#      batch_time_unit: day
#      flatten_events: yes
#      record_field_path: system
#    input: data_inputs.s3_device_data
#    output: data_outputs.ds_datalake
##    schema: schema_outputs.glue_datalake
#    deadletter: data_deadletters.ccrussbucket
#
#  hudson_latest:
#    auto_approve: yes
#    env: dev
#    buffer_threshold_bytes: 20000000
#    buffer_threshold_seconds: 300
#    transform:
#      batch_time_fields: system.datetime_posix_utc_seconds
#      batch_time_unit: day
#      flatten_events: yes
#    input: data_inputs.s3_device_data_latest
##    output: data_outputs.ds_datalake_dev
##    schema: schema_outputs.glue_datalake
##    deadletter: data_deadletters.ccrussbucket

  onebr:
#    reset_offsets: yes
#    reset_metadata: yes
    chaos_mode: no
    auto_approve: yes
    env: dev
#    data_dir: /Volumes/PaulTimemachine/data
    buffer_threshold_bytes: 50000000
    buffer_threshold_seconds: 60
    transform:
#      batch_time_fields: event_date
#      batch_time_unit: day
#      namespace_fields: message_type
#      batch_partition_fields: station
#      batch_partition_fields: event_type
    input: data_inputs.local_1br
#    output: data_outputs.test_datalake

  bike_hire:
#    reset_offsets: yes
#    reset_metadata: yes
    chaos_mode: no
    auto_approve: yes
    env: dev
#    data_dir: /Volumes/PaulTimemachine/data
    buffer_threshold_bytes: 50000000
    buffer_threshold_seconds: 60
    transform:
#      batch_time_fields: event_date
#      batch_time_unit: day
#      namespace_fields: message_type
#      batch_partition_fields: event_type,hardware.model,hardware.manufacturer
#      batch_partition_fields: event_type
    input: data_inputs.local_bike_hire
#    output: data_outputs.test_datalake

  ieu_trip:
#    reset_offsets: yes
#    reset_metadata: yes
    chaos_mode: no
    auto_approve: yes
    env: dev
    buffer_threshold_bytes: 20000000
    buffer_threshold_seconds: 600
    transform:
      batch_time_fields: time
      batch_time_unit: day
#      flatten_events: yes
      namespace_fields: message_type
      batch_partition_fields: tenant_id
#    input: data_inputs.ieu_trip
    output: data_outputs.test_datalake

  highres:
#    reset_offsets: yes
#    reset_metadata: yes
    chaos_mode: no
    auto_approve: yes
    env: dev
    buffer_threshold_bytes: 20000000
    buffer_threshold_seconds: 600
    transform:
#      record_field_path: data
      batch_time_fields: rcvd_time
      batch_time_unit: day
#      flatten_events: no
      namespace_fields: ns
#      batch_partition_fields: tenant_id,source_type
#    input: data_inputs.highres
    input: data_inputs.highres_test
#    output: data_outputs.test_datalake

  tm8_jny_speed_profile:
#    reset_offsets: yes
#    reset_metadata: yes
    chaos_mode: no
    auto_approve: yes
    env: dev
    buffer_threshold_bytes: 20000000
    buffer_threshold_seconds: 600
    transform:
#      record_field_path: data
      batch_time_fields: rcvd_time
      batch_time_unit: day
#      flatten_events: no
      namespace_fields: ns
#      batch_partition_fields: tenant_id,source_type
#    input: data_inputs.tm8_jny_speed_profile
    output: data_outputs.test_datalake

  cube_events:
#    reset_offsets: yes
#    reset_metadata: yes
    env: dev
    auto_approve: yes
    buffer_threshold_bytes: 20000000
    buffer_threshold_seconds: 600
    transform:
      batch_time_fields: time
      batch_time_unit: day
      flatten_events: yes
      namespace_fields: detail-type
    input: data_inputs.local_cube_events
    output: data_outputs.test_datalake

  drvn:
#    reset_offsets: yes
#    reset_metadata: yes
    env: dev
    auto_approve: yes
    buffer_threshold_bytes: 200000000
    buffer_threshold_seconds: 600
    input: data_inputs.drvn
#    output: data_outputs.ds_datalake

  metrics:
#    reset_offsets: yes
#    reset_metadata: yes
    env: dev
    auto_approve: yes
    buffer_threshold_bytes: 20000000
    buffer_threshold_seconds: 600
    transform:
      batch_time_fields: datetime
      batch_time_unit: day
      flatten_events: no
      namespace_fields: type
    #        batch_partition_fields: tenant_id
    input: data_inputs.metrics
#    output: data_outputs.datalake



data_inputs:
  cube_events:
    s3:
      batch_size_bytes: 5048000
      s3_bucket: production-datastorage-stack-cubeevents9ad2ae37-ots21z45kn3g
      s3_prefix: /2022/
  local_cube_events:
    file:
      batch_size_bytes: 4048000
      format: json
      path: /Users/huders2000/Documents/sites/skippr/skipprd/test-data/cube_events/01
  cloud_trail:
    s3:
      batch_size_bytes: 1000
      s3_bucket: aws-cloudtrail-logs-201015722121-1d5e4776
      s3_prefix: AWSLogs/201015722121/CloudTrail/eu-west-1/
  ieu_trip:
    s3:
      batch_size_bytes: 2048000
      s3_bucket: kafka-s3-partitioned-uat
      s3_prefix: enriched/ieu.trip/tenant_id=AAUK/source_type=IEU/year=2023/month=10/
  highres:
    s3:
      batch_size_bytes: 2048000
      s3_bucket: kafka-s3-partitioned-uat
      s3_prefix: raw/devices.tm8.highres.binary/year=2023/month=10
  tm8_jny_speed_profile:
    s3:
      batch_size_bytes: 2048000
      s3_bucket: kafka-s3-partitioned-uat
      s3_prefix: raw/devices.tm8.jny.speed.profile/year=2023/month=10
  highres_test:
    file:
      batch_size_bytes: 20048000
      path: /Users/huders2000/Desktop/test.json
  ieu_trip_inventory:
    s3:
      batch_size_bytes: 2048000
      s3_bucket: kafka-s3-partitioned-uat-inventory
      s3_prefix: enriched-ieu.trip/
  s3_bike_hire:
    s3:
      batch_size_bytes: 48000
      s3_bucket: skippr-e2e-sample-data
      s3_prefix: bike-hire/
  local_bike_hire:
    file:
      batch_size_bytes: 6048000
      format: json
      path: /Users/huders2000/Documents/sites/skippr/skipprd/test-data/bike-hire/
  local_1br:
    file:
      batch_size_bytes: 2048000
      format: csv
      path: /Users/huders2000/Documents/sites/_scratch/1brc/data/
  local_cache:
    file:
      batch_size_bytes: 4048000
      format: xml
      path: /Users/huders2000/Desktop/bar/aaa
  drvn:
    file:
      batch_size_bytes: 4048000
      format: json
      path: /Users/huders2000/Documents/sites/skippr/_v2/utils/parquet-to-json/parquet-to-json/output
  s3_device_data_dev:
    s3:
      batch_size_bytes: 4048000
      s3_bucket: dev-datastorage-stack-rawdevicejson568138dc-mupghu26386n
      s3_prefix: data/2023/10/07
  s3_device_data:
    s3:
      batch_size_bytes: 4048000
      s3_bucket: production-datastorage-stac-rawdevicejson568138dc-1djhnp70ebsko
      s3_prefix: data/2023/09/
  s3_device_data_latest:
    s3:
      batch_size_bytes: 4048000
      s3_bucket: dev-datastorage-stack-rawdevicejson568138dc-mupghu26386n
      s3_prefix: data/2023/09/21
  s3_inventory_aaa:
    s3_inventory:
      batch_size_bytes: 4048000
      s3_bucket: skippr-e2e-sample-data
      s3_prefix: inventory-topics-aaa/skippr-e2e-sample-data/topics-aaa-only-testing-end-slash
  metrics:
    s3:
      batch_size_bytes: 2048000
      s3_bucket: skippr-metric-prod
      s3_prefix: /


data_outputs:
  test_datalake:
    athena:
      athena_workgroup_name: bikehire
      glue_database_name: bikehire
      s3_bucket: skippr-e2e-sample-data-output
      s3_prefix: bikehire
  ds_datalake_dev:
    athena:
      athena_workgroup_name: ds
      glue_database_name: datalake
      s3_bucket: cloudcycle-datalake-dev
      s3_prefix: /
  ds_datalake:
    athena:
      athena_workgroup_name: ds
      glue_database_name: datalake
      s3_bucket: cloudcycle-datalake-production
      s3_prefix: /
  hudson_datalake:
    athena:
      athena_workgroup_name: ds
      glue_database_name: hudson_test
      s3_bucket: cloudcycle-datalake-production
      s3_prefix: /hudson_test
  drvn_datalake:
    athena:
      athena_workgroup_name: uat-skippr-datalake
      glue_database_name: datalake
      s3_bucket: uat-datalake
      s3_prefix: datalake

data_deadletters:
  ccrussbucket:
    s3:
      s3_bucket: cloudcycle-datalake-production
      s3_prefix: /hudson_test/deadletters
