// @generated by skippr-connect-gen. Do not edit.

#[pyclass(eq, eq_int, from_py_object, name = "DataSource", module = "skippr")]
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum PyDataSource {
    AdRollAds,
    AiCitations,
    Amqp,
    AppleAppStoreSerp,
    AppleSearchAds,
    BingWebmasterTools,
    Clickhouse,
    ContentQuality,
    DataForSeoBacklinks,
    DataForSeoSeoOpportunities,
    DeltaLake,
    Dynamodb,
    Eventbridge,
    File,
    GoogleAds,
    GoogleAnalytics,
    GooglePageSpeed,
    GoogleSearchConsole,
    GoogleSerpRanks,
    HttpClient,
    HttpServer,
    HubspotCrm,
    Kafka,
    Kinesis,
    LinkedInAds,
    MetaAds,
    MetaInstagramAds,
    Mongodb,
    Motherduck,
    Mqtt,
    Mssql,
    Mysql,
    Otlp,
    Pcap,
    Postgres,
    Redshift,
    RevolutBusiness,
    S3,
    SeoCrawl,
    Sftp,
    ShopifyAdmin,
    SiteQuality,
    SiteSecurity,
    Sns,
    Socket,
    Sqs,
    Statsd,
    Stdin,
    Stripe,
    SumUp,
    UpfoundryBacklinks,
    UpfoundryLinkGraphCompact,
    UpfoundryLinkGraphIngest,
    UpfoundryLinkGraphWatIndex,
    Websocket,
    XAds,
    XeroAccounting,
}

#[pyclass(eq, eq_int, from_py_object, name = "DataSink", module = "skippr")]
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum PyDataSink {
    Amqp,
    Athena,
    AzureBlob,
    Bigquery,
    Clickhouse,
    Databricks,
    File,
    Gcs,
    Iceberg,
    Motherduck,
    Postgres,
    Redshift,
    S3,
    Sftp,
    Snowflake,
    Stdout,
    Synapse,
}

#[pyclass(eq, eq_int, from_py_object, name = "SchemaSink", module = "skippr")]
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum PySchemaSink {
    Bigquery,
    Clickhouse,
    Glue,
    Iceberg,
    Motherduck,
    Postgres,
    Redshift,
    Snowflake,
}

pub fn connect_plugin_data_source(kind: PyDataSource) -> ConnectPlugin {
    match kind {
        PyDataSource::AdRollAds => ConnectPlugin::DataSourceAdRollAds,
        PyDataSource::AiCitations => ConnectPlugin::DataSourceAiCitations,
        PyDataSource::Amqp => ConnectPlugin::DataSourceAmqp,
        PyDataSource::AppleAppStoreSerp => ConnectPlugin::DataSourceAppleAppStoreSerp,
        PyDataSource::AppleSearchAds => ConnectPlugin::DataSourceAppleSearchAds,
        PyDataSource::BingWebmasterTools => ConnectPlugin::DataSourceBingWebmasterTools,
        PyDataSource::Clickhouse => ConnectPlugin::DataSourceClickhouse,
        PyDataSource::ContentQuality => ConnectPlugin::DataSourceContentQuality,
        PyDataSource::DataForSeoBacklinks => ConnectPlugin::DataSourceDataForSeoBacklinks,
        PyDataSource::DataForSeoSeoOpportunities => ConnectPlugin::DataSourceDataForSeoSeoOpportunities,
        PyDataSource::DeltaLake => ConnectPlugin::DataSourceDeltaLake,
        PyDataSource::Dynamodb => ConnectPlugin::DataSourceDynamodb,
        PyDataSource::Eventbridge => ConnectPlugin::DataSourceEventbridge,
        PyDataSource::File => ConnectPlugin::DataSourceFile,
        PyDataSource::GoogleAds => ConnectPlugin::DataSourceGoogleAds,
        PyDataSource::GoogleAnalytics => ConnectPlugin::DataSourceGoogleAnalytics,
        PyDataSource::GooglePageSpeed => ConnectPlugin::DataSourceGooglePageSpeed,
        PyDataSource::GoogleSearchConsole => ConnectPlugin::DataSourceGoogleSearchConsole,
        PyDataSource::GoogleSerpRanks => ConnectPlugin::DataSourceGoogleSerpRanks,
        PyDataSource::HttpClient => ConnectPlugin::DataSourceHttpClient,
        PyDataSource::HttpServer => ConnectPlugin::DataSourceHttpServer,
        PyDataSource::HubspotCrm => ConnectPlugin::DataSourceHubspotCrm,
        PyDataSource::Kafka => ConnectPlugin::DataSourceKafka,
        PyDataSource::Kinesis => ConnectPlugin::DataSourceKinesis,
        PyDataSource::LinkedInAds => ConnectPlugin::DataSourceLinkedInAds,
        PyDataSource::MetaAds => ConnectPlugin::DataSourceMetaAds,
        PyDataSource::MetaInstagramAds => ConnectPlugin::DataSourceMetaInstagramAds,
        PyDataSource::Mongodb => ConnectPlugin::DataSourceMongodb,
        PyDataSource::Motherduck => ConnectPlugin::DataSourceMotherduck,
        PyDataSource::Mqtt => ConnectPlugin::DataSourceMqtt,
        PyDataSource::Mssql => ConnectPlugin::DataSourceMssql,
        PyDataSource::Mysql => ConnectPlugin::DataSourceMysql,
        PyDataSource::Otlp => ConnectPlugin::DataSourceOtlp,
        PyDataSource::Pcap => ConnectPlugin::DataSourcePcap,
        PyDataSource::Postgres => ConnectPlugin::DataSourcePostgres,
        PyDataSource::Redshift => ConnectPlugin::DataSourceRedshift,
        PyDataSource::RevolutBusiness => ConnectPlugin::DataSourceRevolutBusiness,
        PyDataSource::S3 => ConnectPlugin::DataSourceS3,
        PyDataSource::SeoCrawl => ConnectPlugin::DataSourceSeoCrawl,
        PyDataSource::Sftp => ConnectPlugin::DataSourceSftp,
        PyDataSource::ShopifyAdmin => ConnectPlugin::DataSourceShopifyAdmin,
        PyDataSource::SiteQuality => ConnectPlugin::DataSourceSiteQuality,
        PyDataSource::SiteSecurity => ConnectPlugin::DataSourceSiteSecurity,
        PyDataSource::Sns => ConnectPlugin::DataSourceSns,
        PyDataSource::Socket => ConnectPlugin::DataSourceSocket,
        PyDataSource::Sqs => ConnectPlugin::DataSourceSqs,
        PyDataSource::Statsd => ConnectPlugin::DataSourceStatsd,
        PyDataSource::Stdin => ConnectPlugin::DataSourceStdin,
        PyDataSource::Stripe => ConnectPlugin::DataSourceStripe,
        PyDataSource::SumUp => ConnectPlugin::DataSourceSumUp,
        PyDataSource::UpfoundryBacklinks => ConnectPlugin::DataSourceUpfoundryBacklinks,
        PyDataSource::UpfoundryLinkGraphCompact => ConnectPlugin::DataSourceUpfoundryLinkGraphCompact,
        PyDataSource::UpfoundryLinkGraphIngest => ConnectPlugin::DataSourceUpfoundryLinkGraphIngest,
        PyDataSource::UpfoundryLinkGraphWatIndex => ConnectPlugin::DataSourceUpfoundryLinkGraphWatIndex,
        PyDataSource::Websocket => ConnectPlugin::DataSourceWebsocket,
        PyDataSource::XAds => ConnectPlugin::DataSourceXAds,
        PyDataSource::XeroAccounting => ConnectPlugin::DataSourceXeroAccounting,
    }
}
pub fn connect_plugin_data_sink(kind: PyDataSink) -> ConnectPlugin {
    match kind {
        PyDataSink::Amqp => ConnectPlugin::DataSinkAmqp,
        PyDataSink::Athena => ConnectPlugin::DataSinkAthena,
        PyDataSink::AzureBlob => ConnectPlugin::DataSinkAzureBlob,
        PyDataSink::Bigquery => ConnectPlugin::DataSinkBigquery,
        PyDataSink::Clickhouse => ConnectPlugin::DataSinkClickhouse,
        PyDataSink::Databricks => ConnectPlugin::DataSinkDatabricks,
        PyDataSink::File => ConnectPlugin::DataSinkFile,
        PyDataSink::Gcs => ConnectPlugin::DataSinkGcs,
        PyDataSink::Iceberg => ConnectPlugin::DataSinkIceberg,
        PyDataSink::Motherduck => ConnectPlugin::DataSinkMotherduck,
        PyDataSink::Postgres => ConnectPlugin::DataSinkPostgres,
        PyDataSink::Redshift => ConnectPlugin::DataSinkRedshift,
        PyDataSink::S3 => ConnectPlugin::DataSinkS3,
        PyDataSink::Sftp => ConnectPlugin::DataSinkSftp,
        PyDataSink::Snowflake => ConnectPlugin::DataSinkSnowflake,
        PyDataSink::Stdout => ConnectPlugin::DataSinkStdout,
        PyDataSink::Synapse => ConnectPlugin::DataSinkSynapse,
    }
}
pub fn connect_plugin_schema_sink(kind: PySchemaSink) -> ConnectPlugin {
    match kind {
        PySchemaSink::Bigquery => ConnectPlugin::SchemaSinkBigquery,
        PySchemaSink::Clickhouse => ConnectPlugin::SchemaSinkClickhouse,
        PySchemaSink::Glue => ConnectPlugin::SchemaSinkGlue,
        PySchemaSink::Iceberg => ConnectPlugin::SchemaSinkIceberg,
        PySchemaSink::Motherduck => ConnectPlugin::SchemaSinkMotherduck,
        PySchemaSink::Postgres => ConnectPlugin::SchemaSinkPostgres,
        PySchemaSink::Redshift => ConnectPlugin::SchemaSinkRedshift,
        PySchemaSink::Snowflake => ConnectPlugin::SchemaSinkSnowflake,
    }
}

#[pymethods]
impl PyConnect {
    fn data_source(slf: Bound<'_, Self>, kind: PyDataSource) -> PyResult<Py<Self>> {
        {
            let mut this = slf.borrow_mut();
            this.plugin = Some(connect_plugin_data_source(kind));
            this.maybe_persist()?;
        }
        Ok(slf.unbind())
    }
    fn data_sink(slf: Bound<'_, Self>, kind: PyDataSink) -> PyResult<Py<Self>> {
        {
            let mut this = slf.borrow_mut();
            this.plugin = Some(connect_plugin_data_sink(kind));
            this.maybe_persist()?;
        }
        Ok(slf.unbind())
    }
    fn schema_sink(slf: Bound<'_, Self>, kind: PySchemaSink) -> PyResult<Py<Self>> {
        {
            let mut this = slf.borrow_mut();
            this.plugin = Some(connect_plugin_schema_sink(kind));
            this.maybe_persist()?;
        }
        Ok(slf.unbind())
    }
    fn name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        {
            let mut this = slf.borrow_mut();
            this.name = Some(value);
            this.maybe_persist()?;
        }
        Ok(slf.unbind())
    }
    fn advertiser_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("advertiser_id", value)?;
        Ok(slf.unbind())
    }
    fn access_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("access_token", value)?;
        Ok(slf.unbind())
    }
    fn personal_access_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("personal_access_token", value)?;
        Ok(slf.unbind())
    }
    fn oauth_token_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_token_url", value)?;
        Ok(slf.unbind())
    }
    fn oauth_client_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_client_id", value)?;
        Ok(slf.unbind())
    }
    fn oauth_client_secret(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_client_secret", value)?;
        Ok(slf.unbind())
    }
    fn oauth_refresh_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_refresh_token", value)?;
        Ok(slf.unbind())
    }
    fn api_base_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("api_base_url", value)?;
        Ok(slf.unbind())
    }
    fn reporting_base_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("reporting_base_url", value)?;
        Ok(slf.unbind())
    }
    fn start_date(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("start_date", value)?;
        Ok(slf.unbind())
    }
    fn end_date(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("end_date", value)?;
        Ok(slf.unbind())
    }
    fn lookback_days(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("lookback_days", value)?;
        Ok(slf.unbind())
    }
    fn stream_profile(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("stream_profile", value)?;
        Ok(slf.unbind())
    }
    fn processing_lag_days(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("processing_lag_days", value)?;
        Ok(slf.unbind())
    }
    fn site(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("site", value)?;
        Ok(slf.unbind())
    }
    fn requests_per_minute(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("requests_per_minute", value)?;
        Ok(slf.unbind())
    }
    fn max_prompts_per_run(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_prompts_per_run", value)?;
        Ok(slf.unbind())
    }
    fn skip_unchanged_responses(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("skip_unchanged_responses", value)?;
        Ok(slf.unbind())
    }
    fn openai_base_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("openai_base_url", value)?;
        Ok(slf.unbind())
    }
    fn connection_string(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("connection_string", value)?;
        Ok(slf.unbind())
    }
    fn queue(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("queue", value)?;
        Ok(slf.unbind())
    }
    fn exchange(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("exchange", value)?;
        Ok(slf.unbind())
    }
    fn routing_key(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("routing_key", value)?;
        Ok(slf.unbind())
    }
    fn consumer_tag(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("consumer_tag", value)?;
        Ok(slf.unbind())
    }
    fn prefetch_count(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("prefetch_count", value)?;
        Ok(slf.unbind())
    }
    fn mode(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("mode", value)?;
        Ok(slf.unbind())
    }
    fn idle_timeout_seconds(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("idle_timeout_seconds", value)?;
        Ok(slf.unbind())
    }
    fn format(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("format", value)?;
        Ok(slf.unbind())
    }
    fn batch_size_bytes(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("batch_size_bytes", value)?;
        Ok(slf.unbind())
    }
    fn batch_size_seconds(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("batch_size_seconds", value)?;
        Ok(slf.unbind())
    }
    fn entity(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("entity", value)?;
        Ok(slf.unbind())
    }
    fn max_depth(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_depth", value)?;
        Ok(slf.unbind())
    }
    fn min_query_interval_ms(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("min_query_interval_ms", value)?;
        Ok(slf.unbind())
    }
    fn max_queries_per_run(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_queries_per_run", value)?;
        Ok(slf.unbind())
    }
    fn stop_after_first_target_match(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("stop_after_first_target_match", value)?;
        Ok(slf.unbind())
    }
    fn capture_results(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("capture_results", value)?;
        Ok(slf.unbind())
    }
    fn force_refresh_today(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("force_refresh_today", value)?;
        Ok(slf.unbind())
    }
    fn user_agent(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("user_agent", value)?;
        Ok(slf.unbind())
    }
    fn org_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("org_id", value)?;
        Ok(slf.unbind())
    }
    fn client_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("client_id", value)?;
        Ok(slf.unbind())
    }
    fn team_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("team_id", value)?;
        Ok(slf.unbind())
    }
    fn key_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("key_id", value)?;
        Ok(slf.unbind())
    }
    fn private_key_path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("private_key_path", value)?;
        Ok(slf.unbind())
    }
    fn private_key_pem(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("private_key_pem", value)?;
        Ok(slf.unbind())
    }
    fn time_zone(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("time_zone", value)?;
        Ok(slf.unbind())
    }
    fn return_records_with_no_metrics(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("return_records_with_no_metrics", value)?;
        Ok(slf.unbind())
    }
    fn max_concurrent_requests(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_concurrent_requests", value)?;
        Ok(slf.unbind())
    }
    fn site_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("site_url", value)?;
        Ok(slf.unbind())
    }
    fn api_key(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("api_key", value)?;
        Ok(slf.unbind())
    }
    fn window_in_days(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("window_in_days", value)?;
        Ok(slf.unbind())
    }
    fn request_interval_ms(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("request_interval_ms", value)?;
        Ok(slf.unbind())
    }
    fn max_api_retries(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_api_retries", value)?;
        Ok(slf.unbind())
    }
    fn url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("url", value)?;
        Ok(slf.unbind())
    }
    fn database(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("database", value)?;
        Ok(slf.unbind())
    }
    fn user(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("user", value)?;
        Ok(slf.unbind())
    }
    fn password(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("password", value)?;
        Ok(slf.unbind())
    }
    fn query(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("query", value)?;
        Ok(slf.unbind())
    }
    fn batch_size_rows(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("batch_size_rows", value)?;
        Ok(slf.unbind())
    }
    fn max_urls(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_urls", value)?;
        Ok(slf.unbind())
    }
    fn render_js(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("render_js", value)?;
        Ok(slf.unbind())
    }
    fn crawl_rate_per_second(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("crawl_rate_per_second", value)?;
        Ok(slf.unbind())
    }
    fn respect_robots(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("respect_robots", value)?;
        Ok(slf.unbind())
    }
    fn openai_model(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("openai_model", value)?;
        Ok(slf.unbind())
    }
    fn openai_enabled(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("openai_enabled", value)?;
        Ok(slf.unbind())
    }
    fn openai_max_blocks_per_page(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("openai_max_blocks_per_page", value)?;
        Ok(slf.unbind())
    }
    fn skip_unchanged_content(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("skip_unchanged_content", value)?;
        Ok(slf.unbind())
    }
    fn worker_node_path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("worker_node_path", value)?;
        Ok(slf.unbind())
    }
    fn render_wait_until(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("render_wait_until", value)?;
        Ok(slf.unbind())
    }
    fn render_timeout_ms(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("render_timeout_ms", value)?;
        Ok(slf.unbind())
    }
    fn playwright_executable_path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("playwright_executable_path", value)?;
        Ok(slf.unbind())
    }
    fn max_response_bytes(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_response_bytes", value)?;
        Ok(slf.unbind())
    }
    fn login(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("login", value)?;
        Ok(slf.unbind())
    }
    fn run_mode(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("run_mode", value)?;
        Ok(slf.unbind())
    }
    fn history_date_from(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("history_date_from", value)?;
        Ok(slf.unbind())
    }
    fn history_date_to(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("history_date_to", value)?;
        Ok(slf.unbind())
    }
    fn rank_scale(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("rank_scale", value)?;
        Ok(slf.unbind())
    }
    fn location_code(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("location_code", value)?;
        Ok(slf.unbind())
    }
    fn language_code(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("language_code", value)?;
        Ok(slf.unbind())
    }
    fn device(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("device", value)?;
        Ok(slf.unbind())
    }
    fn search_engine(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("search_engine", value)?;
        Ok(slf.unbind())
    }
    fn seed_queries_from_gsc(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("seed_queries_from_gsc", value)?;
        Ok(slf.unbind())
    }
    fn gsc_source(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("gsc_source", value)?;
        Ok(slf.unbind())
    }
    fn seed_urls_from_crawl(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("seed_urls_from_crawl", value)?;
        Ok(slf.unbind())
    }
    fn seo_crawl_source(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("seo_crawl_source", value)?;
        Ok(slf.unbind())
    }
    fn limits_max_seed_keywords(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("limits_max_seed_keywords", value)?;
        Ok(slf.unbind())
    }
    fn limits_max_generated_keywords(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("limits_max_generated_keywords", value)?;
        Ok(slf.unbind())
    }
    fn limits_serp_depth(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("limits_serp_depth", value)?;
        Ok(slf.unbind())
    }
    fn limits_rank_track_depth(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("limits_rank_track_depth", value)?;
        Ok(slf.unbind())
    }
    fn limits_max_competitors(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("limits_max_competitors", value)?;
        Ok(slf.unbind())
    }
    fn scoring_min_search_volume(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("scoring_min_search_volume", value)?;
        Ok(slf.unbind())
    }
    fn scoring_max_keyword_difficulty(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("scoring_max_keyword_difficulty", value)?;
        Ok(slf.unbind())
    }
    fn scoring_weak_domain_rank_threshold(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("scoring_weak_domain_rank_threshold", value)?;
        Ok(slf.unbind())
    }
    fn scoring_prefer_question_keywords(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("scoring_prefer_question_keywords", value)?;
        Ok(slf.unbind())
    }
    fn scoring_prefer_low_backlink_serps(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("scoring_prefer_low_backlink_serps", value)?;
        Ok(slf.unbind())
    }
    fn table_uri(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("table_uri", value)?;
        Ok(slf.unbind())
    }
    fn version(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("version", value)?;
        Ok(slf.unbind())
    }
    fn filter(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("filter", value)?;
        Ok(slf.unbind())
    }
    fn table_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("table_name", value)?;
        Ok(slf.unbind())
    }
    fn region(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("region", value)?;
        Ok(slf.unbind())
    }
    fn endpoint_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("endpoint_url", value)?;
        Ok(slf.unbind())
    }
    fn cdc_mode(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cdc_mode", value)?;
        Ok(slf.unbind())
    }
    fn event_bus_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("event_bus_name", value)?;
        Ok(slf.unbind())
    }
    fn rule_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("rule_name", value)?;
        Ok(slf.unbind())
    }
    fn sqs_queue_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("sqs_queue_url", value)?;
        Ok(slf.unbind())
    }
    fn path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("path", value)?;
        Ok(slf.unbind())
    }
    fn customer_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("customer_id", value)?;
        Ok(slf.unbind())
    }
    fn developer_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("developer_token", value)?;
        Ok(slf.unbind())
    }
    fn login_customer_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("login_customer_id", value)?;
        Ok(slf.unbind())
    }
    fn api_version(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("api_version", value)?;
        Ok(slf.unbind())
    }
    fn property_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("property_id", value)?;
        Ok(slf.unbind())
    }
    fn service_account_json_path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("service_account_json_path", value)?;
        Ok(slf.unbind())
    }
    fn keep_empty_rows(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("keep_empty_rows", value)?;
        Ok(slf.unbind())
    }
    fn url_mode(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("url_mode", value)?;
        Ok(slf.unbind())
    }
    fn locale(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("locale", value)?;
        Ok(slf.unbind())
    }
    fn max_requests_per_run(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_requests_per_run", value)?;
        Ok(slf.unbind())
    }
    fn top_audits_per_page(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("top_audits_per_page", value)?;
        Ok(slf.unbind())
    }
    fn search_type(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("search_type", value)?;
        Ok(slf.unbind())
    }
    fn data_state(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("data_state", value)?;
        Ok(slf.unbind())
    }
    fn row_limit(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("row_limit", value)?;
        Ok(slf.unbind())
    }
    fn url_inspection_enabled(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("url_inspection_enabled", value)?;
        Ok(slf.unbind())
    }
    fn country(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("country", value)?;
        Ok(slf.unbind())
    }
    fn language(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("language", value)?;
        Ok(slf.unbind())
    }
    fn navigation_timeout_ms(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("navigation_timeout_ms", value)?;
        Ok(slf.unbind())
    }
    fn brightdata_zone(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("brightdata_zone", value)?;
        Ok(slf.unbind())
    }
    fn brightdata_api_base(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("brightdata_api_base", value)?;
        Ok(slf.unbind())
    }
    fn include_allintitle(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("include_allintitle", value)?;
        Ok(slf.unbind())
    }
    fn allintitle_only(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("allintitle_only", value)?;
        Ok(slf.unbind())
    }
    fn max_allintitle_queries_per_run(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_allintitle_queries_per_run", value)?;
        Ok(slf.unbind())
    }
    fn method(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("method", value)?;
        Ok(slf.unbind())
    }
    fn body(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("body", value)?;
        Ok(slf.unbind())
    }
    fn auth_strategy(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("auth_strategy", value)?;
        Ok(slf.unbind())
    }
    fn auth_user(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("auth_user", value)?;
        Ok(slf.unbind())
    }
    fn auth_password(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("auth_password", value)?;
        Ok(slf.unbind())
    }
    fn auth_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("auth_token", value)?;
        Ok(slf.unbind())
    }
    fn scrape_interval_seconds(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("scrape_interval_seconds", value)?;
        Ok(slf.unbind())
    }
    fn scrape_timeout_seconds(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("scrape_timeout_seconds", value)?;
        Ok(slf.unbind())
    }
    fn listen_address(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("listen_address", value)?;
        Ok(slf.unbind())
    }
    fn hub_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("hub_id", value)?;
        Ok(slf.unbind())
    }
    fn privacy_mode(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("privacy_mode", value)?;
        Ok(slf.unbind())
    }
    fn privacy_profile(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("privacy_profile", value)?;
        Ok(slf.unbind())
    }
    fn privacy_on_violation(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("privacy_on_violation", value)?;
        Ok(slf.unbind())
    }
    fn brokers(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("brokers", value)?;
        Ok(slf.unbind())
    }
    fn topic(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("topic", value)?;
        Ok(slf.unbind())
    }
    fn group_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("group_id", value)?;
        Ok(slf.unbind())
    }
    fn auto_offset_reset(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("auto_offset_reset", value)?;
        Ok(slf.unbind())
    }
    fn security_protocol(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("security_protocol", value)?;
        Ok(slf.unbind())
    }
    fn sasl_mechanism(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("sasl_mechanism", value)?;
        Ok(slf.unbind())
    }
    fn sasl_username(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("sasl_username", value)?;
        Ok(slf.unbind())
    }
    fn sasl_password(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("sasl_password", value)?;
        Ok(slf.unbind())
    }
    fn debezium_format(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("debezium_format", value)?;
        Ok(slf.unbind())
    }
    fn stream_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("stream_name", value)?;
        Ok(slf.unbind())
    }
    fn ad_account_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("ad_account_id", value)?;
        Ok(slf.unbind())
    }
    fn rest_version(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("rest_version", value)?;
        Ok(slf.unbind())
    }
    fn instagram_filter(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("instagram_filter", value)?;
        Ok(slf.unbind())
    }
    fn collection(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("collection", value)?;
        Ok(slf.unbind())
    }
    fn motherduck_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("motherduck_token", value)?;
        Ok(slf.unbind())
    }
    fn broker_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("broker_url", value)?;
        Ok(slf.unbind())
    }
    fn port(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("port", value)?;
        Ok(slf.unbind())
    }
    fn qos(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("qos", value)?;
        Ok(slf.unbind())
    }
    fn username(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("username", value)?;
        Ok(slf.unbind())
    }
    fn query_timeout_seconds(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("query_timeout_seconds", value)?;
        Ok(slf.unbind())
    }
    fn server_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("server_id", value)?;
        Ok(slf.unbind())
    }
    fn cdc_idle_timeout_seconds(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cdc_idle_timeout_seconds", value)?;
        Ok(slf.unbind())
    }
    fn listen_address_grpc(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("listen_address_grpc", value)?;
        Ok(slf.unbind())
    }
    fn listen_address_http(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("listen_address_http", value)?;
        Ok(slf.unbind())
    }
    fn host(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("host", value)?;
        Ok(slf.unbind())
    }
    fn replication_slot_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("replication_slot_name", value)?;
        Ok(slf.unbind())
    }
    fn publication_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("publication_name", value)?;
        Ok(slf.unbind())
    }
    fn cluster_identifier(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cluster_identifier", value)?;
        Ok(slf.unbind())
    }
    fn workgroup_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("workgroup_name", value)?;
        Ok(slf.unbind())
    }
    fn db_user(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("db_user", value)?;
        Ok(slf.unbind())
    }
    fn api_base(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("api_base", value)?;
        Ok(slf.unbind())
    }
    fn refresh_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("refresh_token", value)?;
        Ok(slf.unbind())
    }
    fn issuer_domain(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("issuer_domain", value)?;
        Ok(slf.unbind())
    }
    fn s3_bucket(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("s3_bucket", value)?;
        Ok(slf.unbind())
    }
    fn s3_prefix(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("s3_prefix", value)?;
        Ok(slf.unbind())
    }
    fn s3_prefix_ordered_depth(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("s3_prefix_ordered_depth", value)?;
        Ok(slf.unbind())
    }
    fn s3_delimiter(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("s3_delimiter", value)?;
        Ok(slf.unbind())
    }
    fn openai_structure_enabled(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("openai_structure_enabled", value)?;
        Ok(slf.unbind())
    }
    fn remote_path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("remote_path", value)?;
        Ok(slf.unbind())
    }
    fn shop_domain(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("shop_domain", value)?;
        Ok(slf.unbind())
    }
    fn use_bulk_operations(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("use_bulk_operations", value)?;
        Ok(slf.unbind())
    }
    fn oauth_access_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_access_token", value)?;
        Ok(slf.unbind())
    }
    fn max_pages_per_run(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_pages_per_run", value)?;
        Ok(slf.unbind())
    }
    fn max_crawl_depth(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_crawl_depth", value)?;
        Ok(slf.unbind())
    }
    fn wait_until(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("wait_until", value)?;
        Ok(slf.unbind())
    }
    fn lighthouse_enabled(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("lighthouse_enabled", value)?;
        Ok(slf.unbind())
    }
    fn axe_enabled(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("axe_enabled", value)?;
        Ok(slf.unbind())
    }
    fn throttle_rtt_ms(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("throttle_rtt_ms", value)?;
        Ok(slf.unbind())
    }
    fn throttle_throughput_kbps(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("throttle_throughput_kbps", value)?;
        Ok(slf.unbind())
    }
    fn throttle_cpu_slowdown(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("throttle_cpu_slowdown", value)?;
        Ok(slf.unbind())
    }
    fn pages_per_minute(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("pages_per_minute", value)?;
        Ok(slf.unbind())
    }
    fn skip_heavy_when_unchanged(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("skip_heavy_when_unchanged", value)?;
        Ok(slf.unbind())
    }
    fn max_third_party_scripts(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_third_party_scripts", value)?;
        Ok(slf.unbind())
    }
    fn import_lighthouse_from_site_quality(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("import_lighthouse_from_site_quality", value)?;
        Ok(slf.unbind())
    }
    fn topic_arn(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("topic_arn", value)?;
        Ok(slf.unbind())
    }
    fn address(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("address", value)?;
        Ok(slf.unbind())
    }
    fn framing(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("framing", value)?;
        Ok(slf.unbind())
    }
    fn queue_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("queue_url", value)?;
        Ok(slf.unbind())
    }
    fn stripe_account_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("stripe_account_id", value)?;
        Ok(slf.unbind())
    }
    fn write_policy(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("write_policy", value)?;
        Ok(slf.unbind())
    }
    fn merchant_code(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("merchant_code", value)?;
        Ok(slf.unbind())
    }
    fn entity_kind(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("entity_kind", value)?;
        Ok(slf.unbind())
    }
    fn entity_domain(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("entity_domain", value)?;
        Ok(slf.unbind())
    }
    fn primary_domain(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("primary_domain", value)?;
        Ok(slf.unbind())
    }
    fn competitor_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("competitor_name", value)?;
        Ok(slf.unbind())
    }
    fn ops_bucket(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("ops_bucket", value)?;
        Ok(slf.unbind())
    }
    fn ops_prefix(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("ops_prefix", value)?;
        Ok(slf.unbind())
    }
    fn selected_snapshot_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("selected_snapshot_id", value)?;
        Ok(slf.unbind())
    }
    fn include_subdomains(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("include_subdomains", value)?;
        Ok(slf.unbind())
    }
    fn max_detail_rows(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_detail_rows", value)?;
        Ok(slf.unbind())
    }
    fn materialization_manifest_key(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("materialization_manifest_key", value)?;
        Ok(slf.unbind())
    }
    fn max_outbound_rows(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_outbound_rows", value)?;
        Ok(slf.unbind())
    }
    fn max_staging_partitions(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_staging_partitions", value)?;
        Ok(slf.unbind())
    }
    fn pagerank_damping(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("pagerank_damping", value)?;
        Ok(slf.unbind())
    }
    fn pagerank_max_iterations(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("pagerank_max_iterations", value)?;
        Ok(slf.unbind())
    }
    fn keep_complete_snapshots(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("keep_complete_snapshots", value)?;
        Ok(slf.unbind())
    }
    fn keep_failed_manifest_days(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("keep_failed_manifest_days", value)?;
        Ok(slf.unbind())
    }
    fn keep_staging_days(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("keep_staging_days", value)?;
        Ok(slf.unbind())
    }
    fn spam_model_version(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("spam_model_version", value)?;
        Ok(slf.unbind())
    }
    fn cc_crawl_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cc_crawl_id", value)?;
        Ok(slf.unbind())
    }
    fn cc_index_base_uri(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cc_index_base_uri", value)?;
        Ok(slf.unbind())
    }
    fn cc_urls_index_prefix(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cc_urls_index_prefix", value)?;
        Ok(slf.unbind())
    }
    fn cc_index_source(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cc_index_source", value)?;
        Ok(slf.unbind())
    }
    fn cc_direct_index_enabled(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cc_direct_index_enabled", value)?;
        Ok(slf.unbind())
    }
    fn max_urls_per_run(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_urls_per_run", value)?;
        Ok(slf.unbind())
    }
    fn max_links_per_page(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_links_per_page", value)?;
        Ok(slf.unbind())
    }
    fn monthly_window(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("monthly_window", value)?;
        Ok(slf.unbind())
    }
    fn cc_web_graph_uri(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cc_web_graph_uri", value)?;
        Ok(slf.unbind())
    }
    fn cc_web_graph_max_rows(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("cc_web_graph_max_rows", value)?;
        Ok(slf.unbind())
    }
    fn live_crawl_enabled(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("live_crawl_enabled", value)?;
        Ok(slf.unbind())
    }
    fn brightdata_proxy_escalation_enabled(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("brightdata_proxy_escalation_enabled", value)?;
        Ok(slf.unbind())
    }
    fn selected_referrer_page_refs_uri(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("selected_referrer_page_refs_uri", value)?;
        Ok(slf.unbind())
    }
    fn corpus_run_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("corpus_run_id", value)?;
        Ok(slf.unbind())
    }
    fn max_referrer_pages_per_run(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_referrer_pages_per_run", value)?;
        Ok(slf.unbind())
    }
    fn crawl_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("crawl_id", value)?;
        Ok(slf.unbind())
    }
    fn wat_paths_manifest_uri(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("wat_paths_manifest_uri", value)?;
        Ok(slf.unbind())
    }
    fn wat_path_start(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("wat_path_start", value)?;
        Ok(slf.unbind())
    }
    fn wat_path_end(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("wat_path_end", value)?;
        Ok(slf.unbind())
    }
    fn target_domain_bucket_count(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("target_domain_bucket_count", value)?;
        Ok(slf.unbind())
    }
    fn max_records_per_batch(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_records_per_batch", value)?;
        Ok(slf.unbind())
    }
    fn max_wat_objects_per_sync(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_wat_objects_per_sync", value)?;
        Ok(slf.unbind())
    }
    fn max_wat_object_bytes(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_wat_object_bytes", value)?;
        Ok(slf.unbind())
    }
    fn max_wat_records_per_object(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_wat_records_per_object", value)?;
        Ok(slf.unbind())
    }
    fn sqs_visibility_timeout_seconds(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("sqs_visibility_timeout_seconds", value)?;
        Ok(slf.unbind())
    }
    fn ping_interval_seconds(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("ping_interval_seconds", value)?;
        Ok(slf.unbind())
    }
    fn account_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("account_id", value)?;
        Ok(slf.unbind())
    }
    fn bearer_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("bearer_token", value)?;
        Ok(slf.unbind())
    }
    fn oauth_consumer_key(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_consumer_key", value)?;
        Ok(slf.unbind())
    }
    fn oauth_consumer_secret(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_consumer_secret", value)?;
        Ok(slf.unbind())
    }
    fn oauth_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_token", value)?;
        Ok(slf.unbind())
    }
    fn oauth_token_secret(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("oauth_token_secret", value)?;
        Ok(slf.unbind())
    }
    fn tenant_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("tenant_id", value)?;
        Ok(slf.unbind())
    }
    fn page_size(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("page_size", value)?;
        Ok(slf.unbind())
    }
    fn exchange_type(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("exchange_type", value)?;
        Ok(slf.unbind())
    }
    fn max_in_flight(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_in_flight", value)?;
        Ok(slf.unbind())
    }
    fn max_in_flight_bytes(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_in_flight_bytes", value)?;
        Ok(slf.unbind())
    }
    fn athena_workgroup_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("athena_workgroup_name", value)?;
        Ok(slf.unbind())
    }
    fn glue_database_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("glue_database_name", value)?;
        Ok(slf.unbind())
    }
    fn athena_results_s3_bucket(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("athena_results_s3_bucket", value)?;
        Ok(slf.unbind())
    }
    fn catalog(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog", value)?;
        Ok(slf.unbind())
    }
    fn max_concurrency(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("max_concurrency", value)?;
        Ok(slf.unbind())
    }
    fn discovery_cache_ttl_secs(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("discovery_cache_ttl_secs", value)?;
        Ok(slf.unbind())
    }
    fn account_name(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("account_name", value)?;
        Ok(slf.unbind())
    }
    fn account_key(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("account_key", value)?;
        Ok(slf.unbind())
    }
    fn sas_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("sas_token", value)?;
        Ok(slf.unbind())
    }
    fn container(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("container", value)?;
        Ok(slf.unbind())
    }
    fn prefix(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("prefix", value)?;
        Ok(slf.unbind())
    }
    fn project(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("project", value)?;
        Ok(slf.unbind())
    }
    fn dataset(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("dataset", value)?;
        Ok(slf.unbind())
    }
    fn location(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("location", value)?;
        Ok(slf.unbind())
    }
    fn credentials_path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("credentials_path", value)?;
        Ok(slf.unbind())
    }
    fn table(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("table", value)?;
        Ok(slf.unbind())
    }
    fn workspace_url(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("workspace_url", value)?;
        Ok(slf.unbind())
    }
    fn token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("token", value)?;
        Ok(slf.unbind())
    }
    fn warehouse_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("warehouse_id", value)?;
        Ok(slf.unbind())
    }
    fn schema(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("schema", value)?;
        Ok(slf.unbind())
    }
    fn delta_table_uri(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("delta_table_uri", value)?;
        Ok(slf.unbind())
    }
    fn output_dir(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("output_dir", value)?;
        Ok(slf.unbind())
    }
    fn bucket(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("bucket", value)?;
        Ok(slf.unbind())
    }
    fn service_account_key_path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("service_account_key_path", value)?;
        Ok(slf.unbind())
    }
    fn catalog_type(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_type", value)?;
        Ok(slf.unbind())
    }
    fn catalog_warehouse(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_warehouse", value)?;
        Ok(slf.unbind())
    }
    fn catalog_database(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_database", value)?;
        Ok(slf.unbind())
    }
    fn catalog_catalog_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_catalog_id", value)?;
        Ok(slf.unbind())
    }
    fn catalog_region(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_region", value)?;
        Ok(slf.unbind())
    }
    fn catalog_table(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_table", value)?;
        Ok(slf.unbind())
    }
    fn catalog_uri(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_uri", value)?;
        Ok(slf.unbind())
    }
    fn catalog_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_token", value)?;
        Ok(slf.unbind())
    }
    fn catalog_client_id(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_client_id", value)?;
        Ok(slf.unbind())
    }
    fn catalog_client_secret(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("catalog_client_secret", value)?;
        Ok(slf.unbind())
    }
    fn table_namespace(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("table_namespace", value)?;
        Ok(slf.unbind())
    }
    fn table_prefix(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("table_prefix", value)?;
        Ok(slf.unbind())
    }
    fn table_location_prefix(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("table_location_prefix", value)?;
        Ok(slf.unbind())
    }
    fn query_engine_type(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("query_engine_type", value)?;
        Ok(slf.unbind())
    }
    fn query_engine_workgroup(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("query_engine_workgroup", value)?;
        Ok(slf.unbind())
    }
    fn sslmode(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("sslmode", value)?;
        Ok(slf.unbind())
    }
    fn staging_s3_bucket(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("staging_s3_bucket", value)?;
        Ok(slf.unbind())
    }
    fn staging_s3_prefix(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("staging_s3_prefix", value)?;
        Ok(slf.unbind())
    }
    fn iam_role_arn(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("iam_role_arn", value)?;
        Ok(slf.unbind())
    }
    fn account(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("account", value)?;
        Ok(slf.unbind())
    }
    fn warehouse(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("warehouse", value)?;
        Ok(slf.unbind())
    }
    fn role(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("role", value)?;
        Ok(slf.unbind())
    }
    fn stage(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("stage", value)?;
        Ok(slf.unbind())
    }
    fn staging_uri(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("staging_uri", value)?;
        Ok(slf.unbind())
    }
    fn staging_storage_integration(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("staging_storage_integration", value)?;
        Ok(slf.unbind())
    }
    fn staging_azure_sas_token(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("staging_azure_sas_token", value)?;
        Ok(slf.unbind())
    }
    fn staging_azure_account_key(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("staging_azure_account_key", value)?;
        Ok(slf.unbind())
    }
    fn staging_gcs_service_account_key_path(slf: Bound<'_, Self>, value: String) -> PyResult<Py<Self>> {
        slf.borrow_mut().set_field("staging_gcs_service_account_key_path", value)?;
        Ok(slf.unbind())
    }
}
