/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionContext {
    /// Suite-defined plan kind token.
    #[serde(rename = "plan_kind", skip_serializing_if = "Option::is_none")]
    pub plan_kind: Option<models::PlanKind>,
    #[serde(rename = "plan_key", skip_serializing_if = "Option::is_none")]
    pub plan_key: Option<String>,
    #[serde(rename = "workgroup_id", skip_serializing_if = "Option::is_none")]
    pub workgroup_id: Option<String>,
    #[serde(rename = "task_id", skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,
    #[serde(rename = "checklist_item_id", skip_serializing_if = "Option::is_none")]
    pub checklist_item_id: Option<String>,
}

impl ExecutionContext {
    pub fn new() -> ExecutionContext {
        ExecutionContext {
            plan_kind: None,
            plan_key: None,
            workgroup_id: None,
            task_id: None,
            checklist_item_id: None,
        }
    }
}

