/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenRequest {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Existing thread id returned by a previous interaction
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    /// Optional nudge to resume the thread (default is \"Continue.\")
    #[serde(rename = "question", skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,
    /// Suite id to use (e.g. kb | analytics_suite)
    #[serde(rename = "suiteId")]
    pub suite_id: String,
    /// Agent to use for this message; if differs from current, a switch_agent step is recorded.
    #[serde(rename = "agentType")]
    pub agent_type: AgentType,
}

impl OpenRequest {
    pub fn new(v: i32, cid: String, r#type: Type, thread_id: String, suite_id: String, agent_type: AgentType) -> OpenRequest {
        OpenRequest {
            v,
            cid,
            r#type,
            thread_id,
            question: None,
            suite_id,
            agent_type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "open")]
    Open,
}

impl Default for Type {
    fn default() -> Type {
        Self::Open
    }
}
/// Agent to use for this message; if differs from current, a switch_agent step is recorded.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgentType {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "kb")]
    Kb,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "review")]
    Review,
}

impl Default for AgentType {
    fn default() -> AgentType {
        Self::Ask
    }
}

