/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PhaseReasonDetail : Typed wrapper for phase reason details. Suites may include additional debug information under `data`, but control metadata must stay typed. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhaseReasonDetail {
    #[serde(rename = "review_phase", skip_serializing_if = "Option::is_none")]
    pub review_phase: Option<String>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<models::ReviewDecisionMeta>,
    #[serde(rename = "answer", skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    #[serde(rename = "trigger_step_idx", skip_serializing_if = "Option::is_none")]
    pub trigger_step_idx: Option<i32>,
    #[serde(rename = "trigger_step", skip_serializing_if = "Option::is_none")]
    pub trigger_step: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl PhaseReasonDetail {
    /// Typed wrapper for phase reason details. Suites may include additional debug information under `data`, but control metadata must stay typed. 
    pub fn new() -> PhaseReasonDetail {
        PhaseReasonDetail {
            review_phase: None,
            meta: None,
            answer: None,
            trigger_step_idx: None,
            trigger_step: None,
            kind: None,
            data: None,
        }
    }
}

