/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanTask {
    #[serde(rename = "taskKind", skip_serializing_if = "Option::is_none")]
    pub task_kind: Option<String>,
    #[serde(rename = "taskId")]
    pub task_id: String,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "status")]
    pub status: models::PlanTaskStatus,
    #[serde(rename = "checklist")]
    pub checklist: Vec<models::PlanChecklistItem>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl PlanTask {
    pub fn new(task_id: String, status: models::PlanTaskStatus, checklist: Vec<models::PlanChecklistItem>) -> PlanTask {
        PlanTask {
            task_kind: None,
            task_id,
            label: None,
            status,
            checklist,
            details: None,
        }
    }
}


