/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlanWorkGroupKind {
    #[serde(rename = "author_sql")]
    AuthorSql,
    #[serde(rename = "author_schema")]
    AuthorSchema,
    #[serde(rename = "validate")]
    Validate,

}

impl std::fmt::Display for PlanWorkGroupKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AuthorSql => write!(f, "author_sql"),
            Self::AuthorSchema => write!(f, "author_schema"),
            Self::Validate => write!(f, "validate"),
        }
    }
}

impl Default for PlanWorkGroupKind {
    fn default() -> PlanWorkGroupKind {
        Self::AuthorSql
    }
}

