/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlansChangedResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "thread_seq", skip_serializing_if = "Option::is_none")]
    pub thread_seq: Option<i32>,
    #[serde(rename = "for_cid", skip_serializing_if = "Option::is_none")]
    pub for_cid: Option<String>,
    /// Which plan kinds changed. UI should fetch `plans` to get latest snapshots.
    #[serde(rename = "changed")]
    pub changed: Vec<models::PlanKind>,
    /// Plan keys that changed (same order as `changed` where available).
    #[serde(rename = "changed_plan_keys", skip_serializing_if = "Option::is_none")]
    pub changed_plan_keys: Option<Vec<String>>,
}

impl PlansChangedResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, thread_id: String, changed: Vec<models::PlanKind>) -> PlansChangedResponse {
        PlansChangedResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            thread_seq: None,
            for_cid: None,
            changed,
            changed_plan_keys: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "plans_changed")]
    PlansChanged,
}

impl Default for Type {
    fn default() -> Type {
        Self::PlansChanged
    }
}

