/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanChecklistItem {
    /// Stable identifier within the task (e.g. sql_model, schema_contract, validate).
    #[serde(rename = "checklistItemId")]
    pub checklist_item_id: String,
    /// Short UI label.
    #[serde(rename = "label")]
    pub label: String,
    /// Optional longer-form instructions/details.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "status")]
    pub status: models::PlanChecklistItemStatus,
    #[serde(rename = "origin")]
    pub origin: models::PlanChecklistOrigin,
    /// Thread step index that introduced this requirement (null for initial items).
    #[serde(rename = "originStepIdx", skip_serializing_if = "Option::is_none")]
    pub origin_step_idx: Option<i32>,
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Vec<models::PlanChecklistEvidence>>,
}

impl PlanChecklistItem {
    pub fn new(checklist_item_id: String, label: String, status: models::PlanChecklistItemStatus, origin: models::PlanChecklistOrigin) -> PlanChecklistItem {
        PlanChecklistItem {
            checklist_item_id,
            label,
            details: None,
            status,
            origin,
            origin_step_idx: None,
            evidence: None,
        }
    }
}

