/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewRef {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "sha256")]
    pub sha256: String,
    #[serde(rename = "bytes")]
    pub bytes: i64,
}

impl ReviewRef {
    pub fn new(key: String, sha256: String, bytes: i64) -> ReviewRef {
        ReviewRef {
            key,
            sha256,
            bytes,
        }
    }
}

