/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReviewDecision {
    #[serde(rename = "proceed")]
    Proceed,
    #[serde(rename = "patch_plan")]
    PatchPlan,
    #[serde(rename = "patch_impl")]
    PatchImpl,

}

impl std::fmt::Display for ReviewDecision {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Proceed => write!(f, "proceed"),
            Self::PatchPlan => write!(f, "patch_plan"),
            Self::PatchImpl => write!(f, "patch_impl"),
        }
    }
}

impl Default for ReviewDecision {
    fn default() -> ReviewDecision {
        Self::Proceed
    }
}

