skippr:
  skippr_s3_bucket: skippr-e2e-sample-data-output
  tenant: skippr
  workspace: test

pipelines:

  bike_hire_s3_wal_many:
    auto_approve: yes
    env: test
    buffer_threshold_bytes: 10000000
    buffer_threshold_seconds: 600
    data_source: data_sources.s3_bike_hire
    data_sink: data_sinks.test_datalake

data_sources:
  s3_bike_hire:
    S3:
      batch_size_bytes: 2048000
      s3_bucket: skippr-e2e-sample-data
      s3_prefix: many/bike-hire-many

data_sinks:
  test_datalake:
    Athena:
      athena_workgroup_name: bikehire
      s3_bucket: skippr-e2e-sample-data-output
      athena_results_s3_bucket: skippr-e2e-sample-data-output
      s3_prefix: bike_hire_s3_wal_many
    schema_sink: schema_sinks.glue_bikehire

schema_sinks:
  glue_bikehire:
    Glue:
      glue_database_name: bikehire
