/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteRequest : Delete a thread (removes thread JSON and any thread-scoped embeddings)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteRequest {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
}

impl DeleteRequest {
    /// Delete a thread (removes thread JSON and any thread-scoped embeddings)
    pub fn new(v: i32, cid: String, r#type: Type, thread_id: String) -> DeleteRequest {
        DeleteRequest {
            v,
            cid,
            r#type,
            thread_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "delete")]
    Delete,
}

impl Default for Type {
    fn default() -> Type {
        Self::Delete
    }
}

