/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "messages")]
    pub messages: Vec<models::HistoryResponseMessagesInner>,
    #[serde(rename = "next_before_thread_seq", skip_serializing_if = "Option::is_none")]
    pub next_before_thread_seq: Option<i32>,
}

impl HistoryResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, thread_id: String, messages: Vec<models::HistoryResponseMessagesInner>) -> HistoryResponse {
        HistoryResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            title: None,
            messages,
            next_before_thread_seq: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "history")]
    History,
}

impl Default for Type {
    fn default() -> Type {
        Self::History
    }
}

