/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeenRequest {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "up_to_thread_seq")]
    pub up_to_thread_seq: i32,
}

impl SeenRequest {
    pub fn new(v: i32, cid: String, r#type: Type, thread_id: String, up_to_thread_seq: i32) -> SeenRequest {
        SeenRequest {
            v,
            cid,
            r#type,
            thread_id,
            up_to_thread_seq,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "seen")]
    Seen,
}

impl Default for Type {
    fn default() -> Type {
        Self::Seen
    }
}

