name: Chaos Mode Test
inputs:
  architecture_name:
    description: 'macos_arm64, macos-x86, linux_x86'
    required: true
    default: 'stable'
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  docker_hub_pass:
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Skippr Tests
      shell: bash
      run: |
        chmod +x ./skippr-${{ inputs.architecture_name }}/skippr
        
        cp .github/actions/e2e/chaos_mode/skippr.yml ./skippr.yml
        
        ls -la ./
        
        AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skippr-${{ inputs.architecture_name }}/skippr discover --pipeline chaos_mode
        AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skippr-${{ inputs.architecture_name }}/skippr query --sql "ENABLE PIPELINE chaos_mode"
        
        
        SKIPPR_CHAOS_MODE=yes AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skippr-${{ inputs.architecture_name }}/skippr sync

        SKIPPR_CHAOS_MODE=no AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} AWS_DEFAULT_REGION=us-east-1 ./skippr-${{ inputs.architecture_name }}/skippr sync

    - name: Asset Athena
      shell: bash
      run: |
        pip install soda-core-athena
        AWS_DEFAULT_REGION=us-east-1 AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}  soda scan -d datalake_e2e -c ./soda/configuration.yml ./soda/chaos_mode.yml
