<?php

namespace Tests;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use legacy\src\Skipprd\Traits\Config;
use PHPUnit\Framework\TestCase as PHPUnitTestCase;
use test\Mockery\Adapter\Phpunit\MockeryPHPUnitIntegrationTest;

abstract class TestCase extends PHPUnitTestCase
//abstract class TestCase extends BaseTestCase
{
//    use CreatesApplication;
//    use DatabaseMigrations;
//    use RefreshDatabase;

    protected function setUp(): void {

//        parent::setUp();

//        $this->seed();

//        $path = database_path().'/tests/seed-db.sql';
//        $sql = file_get_contents($path);

//        DB::connection('sqlite_testing')->raw($sql);

    }

    protected function tearDown(): void
    {

        Config::$dateFieldCandidates = [];
        Config::$discoveredFieldOccurrence = [];
        Config::$timeFields = [];
//        Config::getConfig();
        
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
