[package]
name = "skippr-plugin-schema-sink-snowflake"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "skippr-plugin-schema-sink-snowflake"
path = "src/main.rs"

[dependencies]
clap.workspace = true
skippr-runtime-sdk.workspace = true
tokio.workspace = true
skippr-plugin-data-sink-snowflake = { path = "../../data_sink/snowflake" }

[package.metadata.skippr-plugin]
kind = "SchemaSink"
plugin_name = "Snowflake"
supports_schema = true
