/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, final, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwaitApprovalResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "thread_seq")]
    pub thread_seq: i32,
    /// Approval request message; clients should present Approve/Reject controls
    #[serde(rename = "prompt")]
    pub prompt: String,
}

impl AwaitApprovalResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, thread_id: String, thread_seq: i32, prompt: String) -> AwaitApprovalResponse {
        AwaitApprovalResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            thread_seq,
            prompt,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "await_approval")]
    AwaitApproval,
}

impl Default for Type {
    fn default() -> Type {
        Self::AwaitApproval
    }
}

