/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, final, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponseThreadsInner {
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "last_activity", skip_serializing_if = "Option::is_none")]
    pub last_activity: Option<String>,
    #[serde(rename = "unread_count", skip_serializing_if = "Option::is_none")]
    pub unread_count: Option<i32>,
    #[serde(rename = "last_message_preview", skip_serializing_if = "Option::is_none")]
    pub last_message_preview: Option<String>,
    /// Current suite for the thread (derived from thread history)
    #[serde(rename = "suiteId", skip_serializing_if = "Option::is_none")]
    pub suite_id: Option<String>,
    /// Current agent/mode for the thread (derived from thread history)
    #[serde(rename = "agentType", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<String>,
}

impl ListResponseThreadsInner {
    pub fn new(thread_id: String) -> ListResponseThreadsInner {
        ListResponseThreadsInner {
            thread_id,
            title: None,
            last_activity: None,
            unread_count: None,
            last_message_preview: None,
            suite_id: None,
            agent_type: None,
        }
    }
}

