/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewRequest {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// User's question to start a new thread
    #[serde(rename = "question")]
    pub question: String,
    /// Suite id to use (e.g. skippr_ask | skippr_model).
    #[serde(rename = "suiteId")]
    pub suite_id: String,
    /// Agent to use (ask | cleanse | model). Required.
    #[serde(rename = "agentType")]
    pub agent_type: AgentType,
}

impl NewRequest {
    pub fn new(v: i32, cid: String, r#type: Type, question: String, suite_id: String, agent_type: AgentType) -> NewRequest {
        NewRequest {
            v,
            cid,
            r#type,
            question,
            suite_id,
            agent_type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "new")]
    New,
}

impl Default for Type {
    fn default() -> Type {
        Self::New
    }
}
/// Agent to use (ask | cleanse | model). Defaults to ask.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgentType {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "cleanse")]
    Cleanse,
    #[serde(rename = "model")]
    Model,
}

impl Default for AgentType {
    fn default() -> AgentType {
        Self::Ask
    }
}

