/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, final, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OkResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "cid", skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
}

impl OkResponse {
    pub fn new(v: i32, r#type: Type, server_time: String) -> OkResponse {
        OkResponse {
            v,
            r#type,
            server_time,
            cid: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ok")]
    Ok,
}

impl Default for Type {
    fn default() -> Type {
        Self::Ok
    }
}

