/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenRequest {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Existing thread id returned by a previous interaction
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    /// Optional nudge to resume the thread (default is \"Continue.\")
    #[serde(rename = "question", skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,
    /// Agent to use for this message; if differs from current, a switch_agent step is recorded.
    #[serde(rename = "agentType", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<AgentType>,
}

impl OpenRequest {
    pub fn new(v: i32, cid: String, r#type: Type, thread_id: String) -> OpenRequest {
        OpenRequest {
            v,
            cid,
            r#type,
            thread_id,
            question: None,
            agent_type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "open")]
    Open,
}

impl Default for Type {
    fn default() -> Type {
        Self::Open
    }
}
/// Agent to use for this message; if differs from current, a switch_agent step is recorded.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgentType {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "cleanse")]
    Cleanse,
    #[serde(rename = "model")]
    Model,
}

impl Default for AgentType {
    fn default() -> AgentType {
        Self::Ask
    }
}

