/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessingResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "thread_seq", skip_serializing_if = "Option::is_none")]
    pub thread_seq: Option<i32>,
    #[serde(rename = "for_cid", skip_serializing_if = "Option::is_none")]
    pub for_cid: Option<String>,
    #[serde(rename = "stage", skip_serializing_if = "Option::is_none")]
    pub stage: Option<Stage>,
    #[serde(rename = "progress", skip_serializing_if = "Option::is_none")]
    pub progress: Option<f64>,
    /// Upcoming ReAct step name (e.g., run_sql, sql_schema)
    #[serde(rename = "step", skip_serializing_if = "Option::is_none")]
    pub step: Option<String>,
}

impl ProcessingResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, thread_id: String) -> ProcessingResponse {
        ProcessingResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            thread_seq: None,
            for_cid: None,
            stage: None,
            progress: None,
            step: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "processing")]
    Processing,
}

impl Default for Type {
    fn default() -> Type {
        Self::Processing
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Stage {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "retrieving")]
    Retrieving,
    #[serde(rename = "reasoning")]
    Reasoning,
    #[serde(rename = "generating")]
    Generating,
}

impl Default for Stage {
    fn default() -> Stage {
        Self::Queued
    }
}

