/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ServerMessage {
    #[serde(rename="list")]
    List(models::ListResponse),
    #[serde(rename="final")]
    Final(models::FinalResponse),
    #[serde(rename="await_user")]
    AwaitUser(models::AwaitUserResponse),
    #[serde(rename="ok")]
    Ok(models::OkResponse),
    #[serde(rename="error")]
    Error(models::ErrorResponse),
    #[serde(rename="thread_assigned")]
    ThreadAssigned(models::ThreadAssignedResponse),
    #[serde(rename="processing")]
    Processing(models::ProcessingResponse),
    #[serde(rename="token")]
    Token(models::TokenResponse),
    #[serde(rename="history")]
    History(models::HistoryResponse),
    #[serde(rename="unread")]
    Unread(models::UnreadResponse),
}

impl Default for ServerMessage {
    fn default() -> Self {
        Self::List(Default::default())
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Stage {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "retrieving")]
    Retrieving,
    #[serde(rename = "reasoning")]
    Reasoning,
    #[serde(rename = "generating")]
    Generating,
}

impl Default for Stage {
    fn default() -> Stage {
        Self::Queued
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FinishReason {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "length")]
    Length,
    #[serde(rename = "error")]
    Error,
}

impl Default for FinishReason {
    fn default() -> FinishReason {
        Self::Stop
    }
}

