/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, final, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuitesResponseSuitesInner {
    #[serde(rename = "suiteId")]
    pub suite_id: String,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "allowedAgentTypes")]
    pub allowed_agent_types: Vec<String>,
    #[serde(rename = "defaultAgentType", skip_serializing_if = "Option::is_none")]
    pub default_agent_type: Option<String>,
}

impl SuitesResponseSuitesInner {
    pub fn new(suite_id: String, allowed_agent_types: Vec<String>) -> SuitesResponseSuitesInner {
        SuitesResponseSuitesInner {
            suite_id,
            label: None,
            allowed_agent_types,
            default_agent_type: None,
        }
    }
}

