[package]
name = "react-module-provider-athena"
version = "0.0.0-git"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
aws-config = "1.5.1"
aws-sdk-athena = "1.30.0"
aws-sdk-glue = "1.38.0"
serde_json = "1.0.85"
tokio = { version = "1", features = ["sync", "time"] }
tracing = "0.1"
react-core = { path = "../../core" }
