<?php

namespace Integration\File;

use Docker\API\Endpoint\VolumeCreate;
use Docker\API\Model\HostConfig;
use Docker\API\Model\HostConfigLogConfig;
use Docker\API\Model\Volume;
use Docker\API\Model\VolumesCreatePostBody;
use PHPUnit\Framework\TestCase;
use Docker\API\Model\ContainersCreatePostBody;
use Docker\Docker;
use Skipprd\Helpers;

class JsonToJson extends TestCase
{

    private $docker;
    private $containerConfig;
    private $name;

    public function tearDown()
    {

        $path = realpath(__DIR__ . '/../../../' . $this->name);
        array_map('unlink', glob("$path/*.*"));
        array_map('rmdir', glob("$path/*"));
        rmdir($path);
        
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function setUp()
    {
        parent::setUp();

        $this->name = Helpers::randomStr(16);

        $basePath = realpath(__DIR__ . '/../../../');
        $src = $basePath. '/test-data/0.json.gz';
        $path = $basePath . '/' . $this->name;
        mkdir($path, 0777, true);
        copy($src, $path . '/0.json.gz');

        
//        \putenv('DOCKER_HOST=127.0.0.1:2375');

        $this->docker = Docker::create();

        $this->containerConfig = new ContainersCreatePostBody();
        $this->containerConfig->setImage('skippr/skipprd:latest');
//        $this->containerConfig->setCmd(['php', '../../../src/run.php']);

        $hostConfig = new HostConfig();

        // volume
        $this->containerConfig->setVolumes(new \ArrayObject([$path => (object) []]));
        $hostConfig->setBinds([$path . ':/data']);

        // logs
        $logs = new HostConfigLogConfig();
        $logs->setType('json-file');

        $hostConfig->setLogConfig($logs);

        $this->containerConfig->setHostConfig($hostConfig);

        $this->containerConfig->setAttachStdout(true);


//        $foo = $this->docker->containerList();
    }

    public function testIsSequentialArrayKeys() {

        $envs = [
            'DATA_SOURCE_PLUGIN_NAME=file',
            'DATA_SOURCE_PATH=/data',
            'DATA_SOURCE_FORMAT=json',
            'DEAD_LETTER_PLUGIN_NAME=file',
            'DEAD_LETTER_PATH=/data/deadletters',
            'DEAD_LETTER_FORMAT=json',
            'DATA_OUTPUT_PLUGIN_NAME=file',
            'DATA_OUTPUT_PATH=/data/output',
            'DATA_OUTPUT_FORMAT=json',
            'DATA_DIR=/data',
            'TENANT_ID=skippr',
            'PIPELINE_NAME=uattest',
        ];
        $this->containerConfig->setEnv($envs);

        $containerCreateResult = $this->docker->containerCreate($this->containerConfig, ['name' => $this->name]);

//        $attachStream = $this->docker->containerAttach($this->name, [
//            'stream' => true,
//            'stdout' => true,
//            'logs' => true,
//        ]);

        // analyse run
        $this->docker->containerStart($containerCreateResult->getId());

//        $attachStream->onStdout(function ($stdout) {
//            $this->assertStringNotContainsStringIgnoringCase('error', $stdout);
//            $this->assertStringNotContainsStringIgnoringCase('fatal', $stdout);
//        });
//
//        $attachStream->wait();

//        print $containerCreateResult->getId();

        $this->docker->containerWait($containerCreateResult->getId());

        $logs = (string) $this->docker->containerLogs($containerCreateResult->getId(), ['stdout' => true, 'stderr' => true, 'follow' => false], Docker::FETCH_RESPONSE)->getBody();

        $this->assertStringNotContainsStringIgnoringCase('error', $logs);
        $this->assertStringNotContainsStringIgnoringCase('fatal', $logs);

        // ingest run
        $this->docker->containerStart($containerCreateResult->getId());

        $this->docker->containerWait($containerCreateResult->getId());

        $logs = (string) $this->docker->containerLogs($containerCreateResult->getId(), ['stdout' => true, 'stderr' => true, 'follow' => false], Docker::FETCH_RESPONSE)->getBody();

        $this->assertStringNotContainsStringIgnoringCase('error', $logs);
        $this->assertStringNotContainsStringIgnoringCase('fatal', $logs);

        $this->assertStringContainsStringIgnoringCase('Ingested 100000 messages', $logs);
        $this->assertStringContainsStringIgnoringCase('Dead Letters 0 dead letters', $logs);

    }
}



