[package]
name = "skippr-plugin-data-sink-file"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "skippr-plugin-data-sink-file"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
arrow.workspace = true
bytes.workspace = true
clap.workspace = true
datafusion.workspace = true
futures.workspace = true
hex.workspace = true
md5.workspace = true
parquet.workspace = true
serde.workspace = true
serde_derive.workspace = true
tokio.workspace = true
tracing.workspace = true
skippr-object-writer.workspace = true
skippr-runtime-sdk.workspace = true

[package.metadata.skippr-plugin]
kind = "DataSink"
plugin_name = "File"

[package.metadata.skippr-plugin.sink_capability]
name = "File"
max_sessions_per_child = 4
guarantee_tier = "CdcEncodedOnly"
can_manage_skippr_columns = false
can_maintain_tombstone_tables = false
can_compare_order_tokens = false
supports_transactions = false
retry_semantics = "DeterministicOverwrite"
grouping_support = "CdcEncodedBatches"
