[package]
name = "skippr-plugin-schema-sink-redshift"
version = "0.0.0-git"
edition = "2021"

[[bin]]
name = "skippr-plugin-schema-sink-redshift"
path = "src/main.rs"

[dependencies]
clap.workspace = true
skippr = { path = "../../.." }
skippr-plugin-runtime-link = { path = "../../skippr-plugin-runtime-link", default-features = false, features = ["runtime-sink-link"] }
tokio.workspace = true
