[package]
name = "skippr-plugin-schema-sink-redshift"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "skippr-plugin-schema-sink-redshift"
path = "src/main.rs"

[dependencies]
clap.workspace = true
skippr-runtime-sdk.workspace = true
tokio.workspace = true
skippr-plugin-data-sink-redshift = { path = "../../data_sink/redshift" }

[package.metadata.skippr-plugin]
kind = "SchemaSink"
plugin_name = "Redshift"
supports_schema = true
