[package]
name = "skippr-plugin-data-source-postgres"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "skippr-plugin-data-source-postgres"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
clap.workspace = true
pgwire-replication.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tracing.workspace = true
skippr-runtime-sdk.workspace = true

[package.metadata.skippr-plugin]
kind = "DataSource"
plugin_name = "Postgres"

[package.metadata.skippr-plugin.source_capability]
name = "Postgres"
guarantee_tier = "SnapshotThenLogExactOnce"
checkpoint_style = "LogNative"
bootstrap_style = "AnchoredSnapshot"
order_model = "GlobalTotalOrder"
supports_deletes = true
event_id_semantics = "LogPosition"
