name: Chaos Mode Test
inputs:
  architecture_name:
    description: 'macos_arm64, macos-x86, linux_x86'
    required: true
    default: 'stable'
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  docker_hub_pass:
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Skippr in Docker
      shell: bash
      run: |
        ls -la `pwd`/
        ls -la `pwd`/.github/
        ls -la `pwd`/.github/actions/
        ls -la `pwd`/.github/actions/e2e-docker/
        ls -la `pwd`/.github/actions/e2e-docker/bike_hire_many/
        docker run --rm \
          -v `pwd`/.github/actions/e2e-docker/bike_hire_many/:/foo/ \
          alpine ls -la /foo/
        docker run --name skipprd \
          -e AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} \
          -e AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} \
          -e AWS_DEFAULT_REGION=us-east-1 \
          -e SKIPPR_CONFIG_FILE=/foo/skippr.yml \
          -v `pwd`/.github/actions/e2e-docker/bike_hire_many/:/foo/ \
          ./skipprd-${{ inputs.architecture_name }}/skipprd discover --pipeline bike_hire_many
         docker run --name skipprd \
          -e AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} \
          -e AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} \
          -e AWS_DEFAULT_REGION=us-east-1 \
          -e SKIPPR_CONFIG_FILE=/foo/skippr.yml \
          -v `pwd`/.github/actions/e2e-docker/bike_hire_many/:/foo/ \
          skippr/skippr:latest sync --pipeline bike_hire_many
        docker logs skipprd
        docker container wait skipprd
        docker container rm skipprd
    - name: Asset Athena
      shell: bash
      run: |
        pip install soda-core-athena
        AWS_DEFAULT_REGION=us-east-1 AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}  soda scan -d datalake_e2e -c ./soda/configuration.yml ./soda/bike_hire_many.yml
