[package]
name = "react-module-provider-redshift"
version = "0.0.0-git"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
aws-config = { version = "1.5", features = ["behavior-version-latest"] }
aws-sdk-redshiftdata = "1"
serde_json = "1.0.85"
tokio = { version = "1", features = ["sync", "time"] }
tracing = "0.1"
react-core = { workspace = true }
react-suite-data-engineer = { path = "../../.." }
