# This extends and specifies variables for the skippr-connect component.

# skippr-connect component test:
#   variables:
#     COMPONENT_NAME: skippr-connect
#     PROJECT_NAME: $COMPONENT_NAME
#     DOCKERFILE_LOCATION: app/Dockerfile${COMPONENT_NAME}
#   extends: .component-test

skippr-skipprd publish image:
  variables:
    COMPONENT_NAME: skipprd
    BUILD_VARIANT: nzt
    PROJECT_NAME: $COMPONENT_NAME
    DOCKERFILE_LOCATION: Dockerfile
    ENV_LATEST_TAG: latest
  extends: .publish-image
  stage: publish

# skippr-connect deploy:dev:
#   variables:
#     COMPONENT_NAME: skippr-connect
#     PROJECT_NAME: $COMPONENT_NAME
#     PROJECT_NAME: $CI_PROJECT_NAME-$COMPONENT_NAME
# #    ECR_URL: 536671797322.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME-$COMPONENT_NAME
#   extends: .deploy-dev

#skippr-connect deploy:preprod:
#  variables:
#    COMPONENT_NAME: skippr-connect
#    PROJECT_NAME: $CI_PROJECT_NAME-$COMPONENT_NAME
##    ECR_URL: 536671797322.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME-$COMPONENT_NAME
#  extends: .deploy-preprod
#
#skippr-connect deploy:uat:
#  variables:
#    COMPONENT_NAME: skippr-connect
#    PROJECT_NAME: $CI_PROJECT_NAME-$COMPONENT_NAME
##    ECR_URL: 536671797322.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME-$COMPONENT_NAME
#  extends: .deploy-uat

# skippr-connect deploy:prod:
#   variables:
#     COMPONENT_NAME: skippr-connect
#     PROJECT_NAME: $COMPONENT_NAME
# #    ECR_URL: 536671797322.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME-$COMPONENT_NAME
#   extends: .deploy-prod
