<?php

namespace Feature\Skipprd\Full;

use PHPUnit\Framework\TestCase;
use Skipprd\Buffers\BufferAdaptorsFactory;
use Skipprd\Commands\PipelineCommand;
use Mockery;
use Skipprd\Converters\AvroParquetSchemaConverter;
use Skipprd\Converters\SkipprAvroSchemaConverter;
use Skipprd\Helpers;
use Skipprd\Serders\SerderCsv;
use Skipprd\Serders\SerderJson;
use Skipprd\Serders\SerdersFactory;
use Skipprd\Serders\SerderXml;
use Skipprd\Traits\Config;
use Skipprd\Traits\Ingest;


class IngestTest extends TestCase
{

    use Ingest;

    private $buffer;

    public function setUp() {

        parent::setUp();

    }

    public function tearDown()
    {

        array_map('unlink', glob($this->buffer->bufferDir . '/*'));
        rmdir($this->buffer->bufferDir);

        parent::tearDown(); // TODO: Change the autogenerated stub]

    }

    public function testJsonToParquet()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->bufferDir . '/*');
    }

    public function testJsonToXml()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'xml';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertXmlOutput($this->buffer->bufferDir . '/*');
    }

    public function testJsonToCsv()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'csv';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertCsvOutput($this->buffer->bufferDir . '/*');
    }

    public function testJsonToJson()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'json';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertJsonOutput($this->buffer->bufferDir . '/*');
    }

    public function testCsvToParquet()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->bufferDir . '/*');
    }

    public function testCsvToXml()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'xml';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertXmlOutput($this->buffer->bufferDir . '/*');
    }

    public function testCsvToCsv()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'csv';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertCsvOutput($this->buffer->bufferDir . '/*');
    }

    public function testCsvToJson()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'json';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertJsonOutput($this->buffer->bufferDir . '/*');
    }

    public function testXmlToParquet()
    {

        Config::$sourceFormat = 'xml';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->bufferDir . '/*');
    }

    public function testXmlToXml()
    {

        Config::$sourceFormat = 'xml';
        Config::$outputFormat = 'xml';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertXmlOutput($this->buffer->bufferDir . '/*');
    }

    public function testXmlToCsv()
    {

        Config::$sourceFormat = 'xml';
        Config::$outputFormat = 'csv';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertCsvOutput($this->buffer->bufferDir . '/*');
    }

    public function testXmlToJson()
    {

        Config::$sourceFormat = 'xml';
        Config::$outputFormat = 'json';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertJsonOutput($this->buffer->bufferDir . '/*');
    }

//    public function testAvroToParquet()
//    {
//
//        Config::$sourceFormat = 'json';
//        Config::$outputFormat = 'json';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertTrue(true);
//    }
//
//    public function testAvroToXml()
//    {
//        Config::$sourceFormat = 'json';
//        Config::$outputFormat = 'json';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertTrue(true);
//    }
//
//    public function testAvroToCsv()
//    {
//        Config::$sourceFormat = 'json';
//        Config::$outputFormat = 'json';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertTrue(true);
//    }
//
//    public function testAvroToJson()
//    {
//        Config::$sourceFormat = 'json';
//        Config::$outputFormat = 'json';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertTrue(true);
//    }

//    public function testParquetToParquet()
//    {
//
//        Config::$sourceFormat = 'parquet';
//        Config::$outputFormat = 'parquet';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//
//        $this->assertParquetOutput($this->buffer->bufferDir . '/*');
//    }

    public function fullRun()
    {

        Config::$tenantId = 'foo';
        Config::$pipelineName = 'bar';

        Config::$schema['fields'] = [];
        Config::$avroSchema = [];

        Config::$analysing = true;
        Config::$discoveredFieldOccurrence = [];
        
        $container = Mockery::mock(PipelineCommand::class)->makePartial();
//        $container->shouldReceive('AnalyseSchema');
//        $container->shouldReceive('serder');

        $serde = SerdersFactory::factory(Config::$sourceFormat);

        $basePath = realpath(__DIR__ . '/../../../../');

        if (Config::$sourceFormat == 'parquet') {

            $filename = $basePath. '/test-data/100.' . Config::$sourceFormat;

        } else {
            $filename = $basePath. '/test-data/100.' . Config::$sourceFormat . '.gz';
        }

        $fields = [];
        $payloadString = '';

        $serde = SerdersFactory::factory(Config::$sourceFormat);

        $container->readFile($filename, function ($payload) use ($serde, &$fields, &$payloadString) {

            if (Config::$sourceFormat == 'parquet') {

                $fields = $payload;

            } elseif (in_array(Config::$sourceFormat, Config::$batchFormats)) {

                $payloadString .= $payload;

            } else {

                $fields = $serde->deserialize($payload);
//                $msgs = $serde->deserialize($payload);
//
//                foreach ($msgs as $msg) {
//
//                    array_push($fields, $msg);
//                }

            }

        });

        if (empty($fields) && in_array(Config::$sourceFormat, Config::$batchFormats)) {

            $msgs = $serde->deserialize($payloadString);

            foreach ($msgs as $msg) {

                array_push($fields, $msg);

            }
        }

        foreach ($fields as $field) {
            $container->analysePayload($field, Config::$discoveredFieldOccurrence);
        }

        $container->determineFieldTypes(Config::$discoveredFieldOccurrence);

        $avroFieldSchema = $this->buildSchema($fields[0]);
        Config::$schema['fields'] = Config::schemaMerge(Config::$specialFieldsMapping, $avroFieldSchema);
        Config::$avroSchema = Config::buildAvroSchema();

        Config::$analysing = false;

        $container->defaultMsg = $this->defaultMessage(Config::$schema['fields']);

        // Ingest messages
        $this->buffer = BufferAdaptorsFactory::getAdaptor('output', 'file');
        
        foreach ($fields as $field) {

            $message = $container->ingestPayload($field, Config::$discoveredFieldOccurrence);

            $this->buffer->append($message, false);

        }

        $this->buffer->flush('output');

        $this->buffer->finalise(true);

    }

    public function buildSchema($record) {

        $avroFieldSchema = [];

        $sub_field_count = [];

        foreach ($record as $field => $value) {

            $field = Helpers::cleanFieldName($field);

//            if (!array_key_exists($field, Config::$specialFields)) {

                $avroType = Config::$discoveredFieldOccurrence[$field]['determined_type'];

                SkipprAvroSchemaConverter::buildAvroFields($avroFieldSchema, $field, $avroType, Config::$discoveredFieldOccurrence, [], $sub_field_count);

//            }

        }

        return $avroFieldSchema;
    }

    public function assertParquetOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

            $parquet = new \Parquet();
            $parquet->create_reader($file, 0);
            $info = $parquet->getInfo();
            $parquet->close_reader();

            // stdClass to array
            $info = json_decode(json_encode($info), true);
            
            $fileSchema = $info['schema']['schema'];

            $parCon = new AvroParquetSchemaConverter();
            $parquetSchema = $parCon->convert(Config::$avroSchema);

            foreach ($parquetSchema as $field => $attr) {

                $this->assertArrayHasKey($field, $fileSchema);

                if (key_exists('type', $fileSchema[$field])) { // @todo - recurse into nested
                    $this->assertEqualsIgnoringCase($fileSchema[$field]['type'], $parquetSchema[$field]['type']);
                }

                if (key_exists('optional', $fileSchema[$field])) { // @todo - recurse into nested
                    $this->assertEqualsIgnoringCase($fileSchema[$field]['optional'],
                        $parquetSchema[$field]['repeat']);
                }
            }

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertXmlOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {
            
            $content = file_get_contents($file);

            $serde = new SerderXml();
            $data = $serde->deserialize($content);

            $this->assertIsArray($data);

            $defaultMsg = $this->defaultMessage(Config::$schema['fields']);

            $missingFields = array_diff_key($data[0], $defaultMsg);

            $this->assertEmpty($missingFields);

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertCsvOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

            $content = file_get_contents($file);

            $serde = new SerderCsv();
            $data = $serde->deserialize($content);

            $this->assertIsArray($data);

            $defaultMsg = $this->defaultMessage(Config::$schema['fields']);

            $missingFields = array_diff_key($data[0], $defaultMsg);

            $this->assertEmpty($missingFields);

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertJsonOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

            $content = file_get_contents($file);

            $serde = new SerderJson();
            $data = $serde->deserialize($content);

            $this->assertIsArray($data);

            $defaultMsg = $this->defaultMessage(Config::$schema['fields']);

            $missingFields = array_diff_key($data[0], $defaultMsg);

            $this->assertEmpty($missingFields);

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }
}
