<?php

namespace Feature\Skipprd\Full;

use PHPUnit\Framework\TestCase;
use Skipprd\Buffers\BufferAdaptorsFactory;
use Skipprd\Commands\PipelineCommand;
use Mockery;
use Skipprd\Converters\AvroParquetSchemaConverter;
use Skipprd\Converters\SkipprAvroSchemaConverter;
use Skipprd\Helpers;
use Skipprd\Serders\SerderAvroFile;
use Skipprd\Serders\SerderAvroRecord;
use Skipprd\Serders\SerderCsv;
use Skipprd\Serders\SerderJson;
use Skipprd\Serders\SerdersFactory;
use Skipprd\Serders\SerderXml;
use Skipprd\Traits\Config;
use Skipprd\Traits\Ingest;


class IngestTest extends TestCase
{

    use Ingest;

    private $buffer;

    public function setUp() {

        parent::setUp();

    }

    public function tearDown()
    {

        array_map('unlink', glob($this->buffer->driver->bufferDir . '/*'));
        rmdir($this->buffer->driver->bufferDir);

        parent::tearDown(); // TODO: Change the autogenerated stub]

    }

    public function testJsonToParquet()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testJsonToXml()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'xml';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertXmlOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testJsonToCsv()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'csv';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertCsvOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testJsonToJson()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'json';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertJsonOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testJsonToAvroFile()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'avro_file';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertAvroFileOutput($this->buffer->driver->bufferDir . '/*');
    }

//    public function testJsonToAvroRecord()
//    {
//
//        Config::$sourceFormat = 'json';
//        Config::$outputFormat = 'avro_record';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//
//        $this->assertAvroRecordOutput($this->buffer->driver->bufferDir . '/*');
//    }

    public function testCsvToParquet()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testCsvToXml()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'xml';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertXmlOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testCsvToCsv()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'csv';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertCsvOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testCsvToJson()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'json';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertJsonOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testCsvToAvroFile()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'avro_file';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertAvroFileOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testXmlToParquet()
    {

        Config::$sourceFormat = 'xml';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testXmlToXml()
    {

        Config::$sourceFormat = 'xml';
        Config::$outputFormat = 'xml';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertXmlOutput($this->buffer->driver->bufferDir . '/*');
    }

//    public function testXmlToCsv()
//    {
//
//        Config::$sourceFormat = 'xml';
//        Config::$outputFormat = 'csv';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//
//        $this->assertCsvOutput($this->buffer->driver->bufferDir . '/*');
//    }

//    public function testXmlToJson()
//    {
//
//        Config::$sourceFormat = 'xml';
//        Config::$outputFormat = 'json';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//
//        $this->assertJsonOutput($this->buffer->driver->bufferDir . '/*');
//    }
//
//    public function testXmlToAvroFile()
//    {
//
//        Config::$sourceFormat = 'xml';
//        Config::$outputFormat = 'avro_file';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//
//        $this->assertAvroFileOutput($this->buffer->driver->bufferDir . '/*');
//    }

    public function testAvroFileToParquet()
    {

        Config::$sourceFormat = 'avro_file';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();
        $this->assertParquetOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testAvroFileToXml()
    {
        Config::$sourceFormat = 'avro_file';
        Config::$outputFormat = 'xml';

        Config::$dataDir = '/tmp';

        $this->fullRun();
        $this->assertXmlOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testAvroFileToCsv()
    {
        Config::$sourceFormat = 'avro_file';
        Config::$outputFormat = 'csv';

        Config::$dataDir = '/tmp';

        $this->fullRun();
        $this->assertCsvOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testAvroFileToJson()
    {
        Config::$sourceFormat = 'avro_file';
        Config::$outputFormat = 'json';

        Config::$dataDir = '/tmp';

        $this->fullRun();
        $this->assertJsonOutput($this->buffer->driver->bufferDir . '/*');
    }

    public function testAvroFileToAvroFile()
    {

        Config::$sourceFormat = 'avro_file';
        Config::$outputFormat = 'avro_file';

        Config::$dataDir = '/tmp';

        $this->fullRun();
        $this->assertAvroFileOutput($this->buffer->driver->bufferDir . '/*');
    }

    //////////////////

//    public function testAvroRecordToParquet()
//    {
//
//        Config::$sourceFormat = 'avro_record';
//        Config::$outputFormat = 'parquet';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertParquetOutput($this->buffer->driver->bufferDir . '/*');
//    }
//
//    public function testAvroRecordToXml()
//    {
//        Config::$sourceFormat = 'avro_record';
//        Config::$outputFormat = 'xml';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertXmlOutput($this->buffer->driver->bufferDir . '/*');
//    }
//
//    public function testAvroRecordToCsv()
//    {
//        Config::$sourceFormat = 'avro_record';
//        Config::$outputFormat = 'csv';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertCsvOutput($this->buffer->driver->bufferDir . '/*');
//    }
//
//    public function testAvroRecordToJson()
//    {
//        Config::$sourceFormat = 'avro_record';
//        Config::$outputFormat = 'json';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertJsonOutput($this->buffer->driver->bufferDir . '/*');
//    }
//
//    public function testAvroRecordToAvroFile()
//    {
//
//        Config::$sourceFormat = 'avro_record';
//        Config::$outputFormat = 'avro_file';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertAvroFileOutput($this->buffer->driver->bufferDir . '/*');
//    }
//
//    public function testAvroRecordToAvroRecord()
//    {
//
//        Config::$sourceFormat = 'avro_record';
//        Config::$outputFormat = 'avro_record';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//        $this->assertAvroRecordOutput($this->buffer->driver->bufferDir . '/*');
//    }


//    public function testParquetToParquet()
//    {
//
//        Config::$sourceFormat = 'parquet';
//        Config::$outputFormat = 'parquet';
//
//        Config::$dataDir = '/tmp';
//
//        $this->fullRun();
//
//        $this->assertParquetOutput($this->buffer->driver->bufferDir . '/*');
//    }

    public function fullRun()
    {

        Config::$tenantId = 'foo';
        Config::$pipelineName = 'bar';

        Config::$schema['foo_partition'] = [];
        Config::$avroSchemas['foo_partition'] = [];

        Config::$analysing = true;
        Config::$discoveredFieldOccurrence['foo_partition'] = [];
        
        $container = Mockery::mock(PipelineCommand::class)->makePartial();
//        $container->shouldReceive('AnalyseSchema');
//        $container->shouldReceive('serder');

        $serde = SerdersFactory::factory(Config::$sourceFormat);

        $basePath = realpath(__DIR__ . '/../../../../');

        if (Config::$sourceFormat == 'parquet') {

            $filename = $basePath. '/test-data/100.' . Config::$sourceFormat;

        } else {
            $filename = $basePath. '/test-data/100.' . Config::$sourceFormat . '.gz';
        }

        $fields = [];
        $payloadString = '';

        $serde = SerdersFactory::factory(Config::$sourceFormat);

        $container->readFile($filename, 'foo_partition', function ($payload) use ($serde, &$fields, &$payloadString) {

            if (Config::$sourceFormat == 'parquet') {

                $fields = $payload;

            } elseif (in_array(Config::$sourceFormat, Config::$batchFormats)) {

                $payloadString .= $payload;

            } else {

                $fields = array_merge($fields, $serde->deserialize($payload));
//                $msgs = $serde->deserialize($payload);
//
//                foreach ($msgs as $msg) {
//
//                    array_push($fields, $msg);
//                }

            }

        });

        if (empty($fields) && in_array(Config::$sourceFormat, Config::$batchFormats)) {

            $msgs = $serde->deserialize($payloadString);

            foreach ($msgs as $msg) {

                array_push($fields, $msg);

            }
        }

        foreach ($fields as $field) {
            $container->analysePayload($field, Config::$discoveredFieldOccurrence['foo_partition']);
        }

        $container->determineFieldTypes(Config::$discoveredFieldOccurrence['foo_partition']);

        $avroFieldSchema = $this->buildSchema($fields[0]);
        Config::$schema['foo_partition'] = Config::schemaMerge(Config::$specialFieldsMapping, $avroFieldSchema);
        Config::$avroSchemas['foo_partition'] = Config::buildAvroSchema(Config::$schema['foo_partition']);

        Config::$analysing = false;

        $container->defaultMsgs['foo_partition'] = $this->defaultMessage(Config::$schema['foo_partition']);

        Config::$outputSchemas = [];

        $outputFormat = ucfirst(Config::$outputFormat);
        $converterClass = 'Skipprd\Converters\Avro' . $outputFormat . 'SchemaConverter';

        if (class_exists($converterClass)) {

            $converter = new $converterClass();

            Config::$outputSchemas['foo_partition'] = $converter->convert(Config::$avroSchemas['foo_partition']);

        } else {

            Config::$outputSchemas['foo_partition'] = Config::$avroSchemas['foo_partition'];
        }

        // Ingest messages
        $this->buffer = BufferAdaptorsFactory::getAdaptor('output', 'file');

        if (Config::$outputFormat == 'avro_record') {
            $this->buffer->flushLength = 1;
        }
        
        foreach ($fields as $field) {

            $message = $container->ingestPayload($field, Config::$discoveredFieldOccurrence['foo_partition'], 'foo_partition');

//            if (!empty($message)) {
                $this->buffer->append($message, false, 0, 'foo_partition');
//            }
            
//            break;

        }

        $timeBucket = $this->buffer->eventTimeBucket(0);

        $chunkName = $this->buffer->encodeChunkName('foo_partition', $timeBucket);

//        $this->buffer->flush($this->buffer->memBuffs, $chunkName, 'foo_partition');
        $this->buffer->flushAll(true);

        $this->buffer->driver->finalise(true);

    }

    public function buildSchema($record) {

        $avroFieldSchema = [];

        $sub_field_count = [];

        foreach ($record as $field => $value) {

            $field = Helpers::cleanFieldName($field);

//            if (!array_key_exists($field, Config::$specialFields)) {

                $avroType = Config::$discoveredFieldOccurrence['foo_partition'][$field]['determined_type'];

                SkipprAvroSchemaConverter::buildAvroFields($avroFieldSchema, $field, $avroType, Config::$discoveredFieldOccurrence['foo_partition'], [], $sub_field_count);

//            }

        }

        return $avroFieldSchema;
    }

    public function assertParquetOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

            $parquet = new \Parquet();
            $parquet->create_reader($file, 0);
            $info = $parquet->getInfo();
            $parquet->close_reader();

            // stdClass to array
            $info = json_decode(json_encode($info), true);
            
            $fileSchema = $info['schema']['schema'];

            $parCon = new AvroParquetSchemaConverter();
            $parquetSchema = $parCon->convert(Config::$avroSchemas['foo_partition']);

            foreach ($parquetSchema as $field => $attr) {

                $this->assertArrayHasKey($field, $fileSchema);

                if (key_exists('type', $fileSchema[$field])) { // @todo - recurse into nested
                    $this->assertEqualsIgnoringCase($fileSchema[$field]['type'], $parquetSchema[$field]['type']);
                }

                if (key_exists('optional', $fileSchema[$field])) { // @todo - recurse into nested
                    $this->assertEqualsIgnoringCase($fileSchema[$field]['optional'],
                        $parquetSchema[$field]['repeat']);
                }
            }

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertXmlOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {
            
            $content = file_get_contents($file);

            $serde = new SerderXml();
            $data = $serde->deserialize($content);

            $this->assertIsArray($data);

            $defaultMsg = $this->defaultMessage(Config::$schema['foo_partition']);

            $missingFields = array_diff_key($data[0], $defaultMsg);

            $this->assertEmpty($missingFields);

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertCsvOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

            $content = file_get_contents($file);

            $serde = new SerderCsv();
            $data = $serde->deserialize($content);

            $this->assertIsArray($data);

            $defaultMsg = $this->defaultMessage(Config::$schema['foo_partition']);

            $missingFields = array_diff_key($data[0], $defaultMsg);

            $this->assertEmpty($missingFields);

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertJsonOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

            $content = file_get_contents($file);

            $serde = new SerderJson();
            $data = $serde->deserialize($content);

            $this->assertIsArray($data);

            $defaultMsg = $this->defaultMessage(Config::$schema['foo_partition']);

            $missingFields = array_diff_key($data[0], $defaultMsg);

            $this->assertEmpty($missingFields);

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertAvroFileOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

            $content = file_get_contents($file);

            $serde = new SerderAvroFile();
            $data = $serde->deserialize($content);

            $this->assertIsArray($data);

            $defaultMsg = $this->defaultMessage(Config::$schema['foo_partition']);

            $missingFields = array_diff_key($data[0], $defaultMsg);

            $this->assertEmpty($missingFields);

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertAvroRecordOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

//            $serde = new SerderAvroRecord();

            $line = file_get_contents($file);

//            $fp = fopen($file, 'rb');
//            while ( $line = fread($fp, filesize($file))) {

//            foreach ($lines as $line) {

                $data = $this->buffer->serde->deserialize($line);

                $this->assertIsArray($data);

                $defaultMsg = $this->defaultMessage(Config::$schema['foo_partition']);

                $missingFields = array_diff_key($data[0], $defaultMsg);

                $this->assertEmpty($missingFields);
//            }

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }
}
