<?php

namespace Feature\Skipprd\Full;

use PHPUnit\Framework\TestCase;
use Skipprd\Buffers\BufferAdaptorsFactory;
use Skipprd\Commands\PipelineCommand;
use Mockery;
use Skipprd\Converters\AvroParquetSchemaConverter;
use Skipprd\Converters\SkipprAvroSchemaConverter;
use Skipprd\Helpers;
use Skipprd\Serders\SerderCsv;
use Skipprd\Serders\SerdersFactory;
use Skipprd\Serders\SerderXml;
use Skipprd\Traits\AnalyseSchema;
use Skipprd\Traits\Config;
use Skipprd\Traits\Ingest;
use Tests\Integration\DockerRun;


class IngestToParquetTest extends TestCase
{

    use Ingest;

    private $buffer;

    public function setUp() {

        Config::$schema['fields'] = [];
        Config::$avroSchema = [];

        Config::$analysing = true;
        Config::$discoveredFieldOccurrence = [];

        parent::setUp();
    }

    public function tearDown()
    {

        array_map('unlink', glob($this->buffer->bufferDir . '/*'));
        rmdir($this->buffer->bufferDir);

        parent::tearDown(); // TODO: Change the autogenerated stub]
    }

    public function testJsonToParquet()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->bufferDir . '/*');
    }

    public function testCsvToParquet()
    {

        Config::$sourceFormat = 'csv';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->bufferDir . '/*');
    }

    public function testJsonToXml()
    {

        Config::$sourceFormat = 'json';
        Config::$outputFormat = 'xml';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertXmlOutput($this->buffer->bufferDir . '/*');
    }

    public function testXmlToParquet()
    {

        Config::$sourceFormat = 'xml';
        Config::$outputFormat = 'parquet';

        Config::$dataDir = '/tmp';

        $this->fullRun();

        $this->assertParquetOutput($this->buffer->bufferDir . '/*');
    }

    public function fullRun()
    {

        Config::$tenantId = 'foo';
        Config::$pipelineName = 'bar';

        $container = Mockery::mock(PipelineCommand::class)->makePartial();
        $container->shouldReceive('AnalyseSchema');
        $container->shouldReceive('serder');

        $serde = SerdersFactory::factory(Config::$sourceFormat);

        $basePath = realpath(__DIR__ . '/../../../../');
        $src = $basePath. '/test-data/100.' . Config::$sourceFormat . '.gz';

        $fields = [];
        $payloadString = '';

        $this->readFile($src, function ($string) use ($serde, $container, &$fields, &$payloadString) {

            if (in_array(Config::$sourceFormat, Config::$batchFormats)) {

                $payloadString .= $string;

            } else {

                $msgs = $serde->deserialize($string);

                foreach ($msgs as $msg) {

                    array_push($fields, $msg);
                }

            }


        });

        if (empty($fields)) {

            $msgs = $serde->deserialize($payloadString);

            foreach ($msgs as $msg) {

                array_push($fields, $msg);

            }
        }

        foreach ($fields as $field) {
            $container->analysePayload($field, Config::$discoveredFieldOccurrence);
        }

        $container->determineFieldTypes(Config::$discoveredFieldOccurrence);

        $avroFieldSchema = $this->buildSchema($fields[0]);
        Config::$schema['fields'] = Config::schemaMerge(Config::$specialFieldsMapping, $avroFieldSchema);
        Config::$avroSchema = Config::buildAvroSchema();

        Config::$analysing = false;

        // Test default message values (empty array, maps and records
        // Particularly relevant for serder to parquet
        $container->defaultMsg = $this->defaultMessage(Config::$schema['fields']);

//        $this->assertArrayHasKey('foo', $container->defaultMsg);
//
//        $this->assertequals([], $container->defaultMsg['foo']['abc1']);
//        $this->assertequals([], $container->defaultMsg['foo']['abc2']);
//        $this->assertequals([], $container->defaultMsg['foo']['abc3']);
//        $this->assertequals([], $container->defaultMsg['foo']['abc4']);
//        $this->assertequals(['' => null], $container->defaultMsg['foo']['abc5']);
//
//        $recordDefault = [
//            'a0' => NULL,
//            'a1' => NULL,
//            'a2' => NULL,
//            'a3' => NULL,
//        ];
//        $this->assertequals($recordDefault, $container->defaultMsg['foo']['abc6']);

        // Ingest messages
        $this->buffer = BufferAdaptorsFactory::getAdaptor('output', 'file');
        
        foreach ($fields as $field) {

            $message = $container->ingestPayload($field, Config::$discoveredFieldOccurrence);

            $this->buffer->append($message, false);

        }

        $this->buffer->flush('output');

        $this->buffer->finalise(true);

//        $dockerrun = new DockerRun();
//
//        $path = Config::$dataDir . '/buffer';
//        $dockerrun->assertParquetOutput($this->buffer->serde->parquetSchema, $path);

    }

    public function buildSchema($record) {

        $avroFieldSchema = [];

        $sub_field_count = [];

        foreach ($record as $field => $value) {

            $field = Helpers::cleanFieldName($field);

//            if (!array_key_exists($field, Config::$specialFields)) {

                $avroType = Config::$discoveredFieldOccurrence[$field]['determined_type'];

                SkipprAvroSchemaConverter::buildAvroFields($avroFieldSchema, $field, $avroType, Config::$discoveredFieldOccurrence, [], $sub_field_count);

//            }

        }

        return $avroFieldSchema;
    }

    public function readFile($filename, callable $callback)
    {

        // open gz file for reading
        $sfp = gzopen($filename, 'rb');

        // read and decode chunks into string stream
        while (!gzeof($sfp)) {

            $string = gzgets($sfp);

            call_user_func($callback, $string);

        }

        gzclose($sfp);

    }

    public function assertParquetOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {

            $parquet = new \Parquet();
            $parquet->create_reader($file, 0);
            $info = $parquet->getInfo();

            // stdClass to array
            $info = json_decode(json_encode($info), true);
            
            $fileSchema = $info['schema']['schema'];

            $parCon = new AvroParquetSchemaConverter();
            $parquetSchema = $parCon->convert(Config::$avroSchema);

            foreach ($parquetSchema as $field => $attr) {

                $this->assertArrayHasKey($field, $fileSchema);

                if (key_exists('type', $fileSchema[$field])) { // @todo - recurse into nested
                    $this->assertEqualsIgnoringCase($fileSchema[$field]['type'], $parquetSchema[$field]['type']);
                }

                if (key_exists('optional', $fileSchema[$field])) { // @todo - recurse into nested
                    $this->assertEqualsIgnoringCase($fileSchema[$field]['optional'],
                        $parquetSchema[$field]['repeat']);
                }
            }

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }

    public function assertXmlOutput($dir) {

        $foundFiles = false;

        array_map(function ($file) use (&$foundFiles) {
            
            $content = file_get_contents($file);

            $serde = new SerderXml();
            $data = $serde->deserialize($content);

            $this->assertIsArray($data);

            $defaultMsg = $this->defaultMessage(Config::$schema['fields']);

            $missingFields = array_diff_key($data[0], $defaultMsg);

            $this->assertEmpty($missingFields);

            $foundFiles = true;

        }, glob($dir));

        $this->assertTrue($foundFiles);

    }
}
