[package]
name = "skippr-plugin-data-source-upfoundry-link-graph-wat-index"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "skippr-plugin-data-source-upfoundry-link-graph-wat-index"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
aws-config = "1.5.1"
aws-sdk-s3 = "1.32.0"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
flate2 = "1.0.25"
serde.workspace = true
serde_json.workspace = true
skippr-plugin-shared-link-graph = { path = "../../shared/link_graph" }
skippr-runtime-sdk.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
tokio-util = { version = "0.7", features = ["io", "io-util", "compat"], default-features = false }
futures.workspace = true
tracing.workspace = true
reqwest.workspace = true

[package.metadata.skippr-plugin]
kind = "DataSource"
plugin_name = "UpfoundryLinkGraphWatIndex"

[package.metadata.skippr-plugin.source_capability]
name = "UpfoundryLinkGraphWatIndex"
guarantee_tier = "IncrementalOnly"
checkpoint_style = "CursorBased"
bootstrap_style = "FullScan"
order_model = "UnsupportedForFinalState"
supports_deletes = false
event_id_semantics = "None"
declares_namespace_contracts = true
