skippr:
  api_token: B8ib6S3wa9nSq5wAwxkO9dceUIg04d4uTYUHBDg
  workspace: test

pipelines:

  offsets_db_rollup:
    auto_approve: yes
    env: test
    buffer_threshold_bytes: 20000000
    buffer_threshold_seconds: 600
    input: data_inputs.s3_bike_hire

data_inputs:
  s3_bike_hire:
    s3:
      batch_size_bytes: 2048000
      s3_bucket: skippr-e2e-sample-data
      s3_prefix: very-small-files

data_outputs:
