[package]
name = "skippr-plugin-schema-sink-bigquery"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "skippr-plugin-schema-sink-bigquery"
path = "src/main.rs"

[dependencies]
clap.workspace = true
skippr-runtime-sdk.workspace = true
tokio.workspace = true

skippr-plugin-data-sink-bigquery = { path = "../../data_sink/bigquery" }
[package.metadata.skippr-plugin]
kind = "SchemaSink"
plugin_name = "Bigquery"
supports_schema = true
