[package]
name = "react-module-provider-snowflake"
version = "0.0.0-git"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
serde_json = "1.0.85"
snowflake-connector-rs = "0.9"
tokio = { version = "1", features = ["sync", "time"] }
tracing = "0.1"
react-core = { workspace = true }
react-suite-data-engineer = { path = "../../.." }
