[package]
name = "react-module-provider-postgres"
version = "0.0.0-git"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
futures = "0.3.25"
serde_json = "1.0.85"
tokio = { version = "1", features = ["rt", "macros", "sync"] }
tokio-postgres = "0.7"
react-core = { workspace = true }
react-suite-data-engineer = { path = "../../.." }
