[package]
name = "skippr-plugin-schema-sink-duckdb"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "skippr-plugin-schema-sink-duckdb"
path = "src/main.rs"

[dependencies]
clap.workspace = true
skippr-runtime-sdk.workspace = true
tokio.workspace = true
skippr-plugin-data-sink-duckdb = { path = "../../data_sink/duckdb" }

[package.metadata.skippr-plugin]
kind = "SchemaSink"
plugin_name = "Duckdb"
supports_schema = true
