[package]
name = "skippr-plugin-data-sink-sftp"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "skippr-plugin-data-sink-sftp"
path = "src/main.rs"

[dependencies]
clap.workspace = true
tokio.workspace = true
skippr-object-writer.workspace = true
skippr-runtime-sdk.workspace = true
arrow.workspace = true
bytes.workspace = true
futures.workspace = true
parquet.workspace = true

async-trait = "0.1.77"
datafusion.workspace = true
hex = "0.4.3"
md5 = "0.7.0"
serde.workspace = true
serde_derive = "1.0.105"
ssh2 = { version = "0.9" }
tracing = "0.1"
[package.metadata.skippr-plugin]
kind = "DataSink"
plugin_name = "Sftp"

[package.metadata.skippr-plugin.sink_capability]
name = "Sftp"
guarantee_tier = "CdcEncodedOnly"
can_manage_skippr_columns = false
can_maintain_tombstone_tables = false
can_compare_order_tokens = false
supports_transactions = false
retry_semantics = "DeterministicOverwrite"
grouping_support = "CdcEncodedBatches"
