pub use skippr_plugin_shared_backlinks::{
    ALL_NAMESPACES, DFS_INGEST_NAMESPACES, NAMESPACE_ANCHOR_DAILY, NAMESPACE_BACKLINK_DAILY,
    NAMESPACE_HISTORY_DAILY, NAMESPACE_OUTBOUND_CONTEXT_DAILY, NAMESPACE_PAGE_INTERSECTION_DAILY,
    NAMESPACE_REFERRING_DOMAIN_DAILY, NAMESPACE_SITE_RUN_DAILY, NAMESPACE_SUMMARY_DAILY,
};
