name: Prepare Rust Builder
description: 'Prepare Rust Build Environment'
inputs:
  rust-version:
    description: 'version of rust to install (e.g. stable)'
    required: true
    default: 'stable'
runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      shell: bash
      run: |
        if [ "$(id -u)" = "0" ]; then
          apt-get update
          apt-get install -y protobuf-compiler cmake libcurl4-openssl-dev libssl-dev pkg-config
        else
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler cmake libcurl4-openssl-dev libssl-dev pkg-config
        fi
    - name: Setup Rust toolchain
      shell: bash
      # rustfmt is needed for the substrait build script
      run: |
        echo "Installing ${{ inputs.rust-version }}"
        rustup toolchain install ${{ inputs.rust-version }}
        rustup default ${{ inputs.rust-version }}
        rustup component add rustfmt
    - name: Install sccache
      if: env.SCCACHE_BUCKET != ''
      uses: mozilla-actions/sccache-action@v0.0.9
      with:
        version: v0.10.0
    - name: Configure sccache
      if: env.SCCACHE_BUCKET != ''
      shell: bash
      run: |
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV
        if [[ -z "${SCCACHE_ENDPOINT:-}" && -n "${R2_ACCOUNT_ID:-}" ]]; then
          echo "SCCACHE_ENDPOINT=https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" >> "$GITHUB_ENV"
        fi
        if [[ -z "${AWS_ENDPOINT_URL:-}" && -n "${R2_ACCOUNT_ID:-}" ]]; then
          echo "AWS_ENDPOINT_URL=https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" >> "$GITHUB_ENV"
        fi

    - name: Disable debuginfo generation
      # Disable full debug symbol generation to speed up CI build and keep memory down
      # "1" means line tables only, which is useful for panic tracebacks.
      shell: bash
      run: echo "RUSTFLAGS=-C debuginfo=1" >> $GITHUB_ENV
    - name: Disable incremental compilation
      # Disable incremental compilation to save diskspace (the CI doesn't recompile modified files)
      # https://github.com/apache/arrow-datafusion/issues/6676
      shell: bash
      run: echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
    - name: Enable backtraces
      shell: bash
      run: echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: v1
        env-vars: "CARGO_INCREMENTAL CARGO_TERM_COLOR RUSTFLAGS"
    - name: Fixup git permissions
      # https://github.com/actions/checkout/issues/766
      shell: bash
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"