[package]
name = "skippr-plugin-schema-sink-glue"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "skippr-plugin-schema-sink-glue"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
clap.workspace = true
skippr-core.workspace = true
skippr-runtime-sdk.workspace = true
tokio.workspace = true
skippr-plugin-data-sink-athena = { path = "../../data_sink/athena" }

[package.metadata.skippr-plugin]
kind = "SchemaSink"
plugin_name = "Glue"
supports_schema = true
