/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, final, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApproveRequest {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
}

impl ApproveRequest {
    pub fn new(v: i32, cid: String, r#type: Type, thread_id: String) -> ApproveRequest {
        ApproveRequest {
            v,
            cid,
            r#type,
            thread_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "approve")]
    Approve,
}

impl Default for Type {
    fn default() -> Type {
        Self::Approve
    }
}

