/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AskFinalPayload {
    /// Plain-text concise answer.
    #[serde(rename = "answer")]
    pub answer: String,
    /// SQL used/generated by Ask mode to produce the answer.
    #[serde(rename = "sql")]
    pub sql: String,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<models::AskFinalPayloadData>,
    #[serde(rename = "chart", skip_serializing_if = "Option::is_none")]
    pub chart: Option<models::AskFinalPayloadChart>,
}

impl AskFinalPayload {
    pub fn new(answer: String, sql: String) -> AskFinalPayload {
        AskFinalPayload {
            answer,
            sql,
            data: None,
            chart: None,
        }
    }
}

