/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AskFinalPayloadData : Optional tabular data from the last successful run_sql
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AskFinalPayloadData {
    #[serde(rename = "header")]
    pub header: Vec<String>,
    #[serde(rename = "rows")]
    pub rows: Vec<Vec<String>>,
}

impl AskFinalPayloadData {
    /// Optional tabular data from the last successful run_sql
    pub fn new(header: Vec<String>, rows: Vec<Vec<String>>) -> AskFinalPayloadData {
        AskFinalPayloadData {
            header,
            rows,
        }
    }
}

