/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CleanseTaskSnapshot {
    #[serde(rename = "taskId")]
    pub task_id: String,
    #[serde(rename = "dataset_id")]
    pub dataset_id: String,
    #[serde(rename = "expected_model_path", skip_serializing_if = "Option::is_none")]
    pub expected_model_path: Option<String>,
    #[serde(rename = "invariants", skip_serializing_if = "Option::is_none")]
    pub invariants: Option<Vec<String>>,
    #[serde(rename = "status")]
    pub status: models::PlanTaskStatus,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<String>>,
}

impl CleanseTaskSnapshot {
    pub fn new(task_id: String, dataset_id: String, status: models::PlanTaskStatus) -> CleanseTaskSnapshot {
        CleanseTaskSnapshot {
            task_id,
            dataset_id,
            expected_model_path: None,
            invariants: None,
            status,
            notes: None,
        }
    }
}

