/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ClientMessage {
    #[serde(rename="list")]
    List(models::ListRequest),
    #[serde(rename="new")]
    New(models::NewRequest),
    #[serde(rename="open")]
    Open(models::OpenRequest),
    #[serde(rename="user")]
    User(models::UserRequest),
    #[serde(rename="resume")]
    Resume(models::ResumeRequest),
    #[serde(rename="history")]
    History(models::HistoryRequest),
    #[serde(rename="seen")]
    Seen(models::SeenRequest),
    #[serde(rename="delete")]
    Delete(models::DeleteRequest),
    #[serde(rename="approve")]
    Approve(models::ApproveRequest),
    #[serde(rename="reject")]
    Reject(models::RejectRequest),
}

impl Default for ClientMessage {
    fn default() -> Self {
        Self::List(Default::default())
    }
}

/// Agent to use for this message; if differs from current, a switch_agent step is recorded.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgentType {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "cleanse")]
    Cleanse,
    #[serde(rename = "model")]
    Model,
}

impl Default for AgentType {
    fn default() -> AgentType {
        Self::Ask
    }
}

