/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Current suite for the thread (derived from thread history)
    #[serde(rename = "suiteId", skip_serializing_if = "Option::is_none")]
    pub suite_id: Option<String>,
    /// Current agent/mode for the thread (derived from thread history)
    #[serde(rename = "agentType", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<String>,
    #[serde(rename = "messages")]
    pub messages: Vec<models::HistoryResponseMessagesInner>,
    #[serde(rename = "next_before_thread_seq", skip_serializing_if = "Option::is_none")]
    pub next_before_thread_seq: Option<i32>,
}

impl HistoryResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, thread_id: String, messages: Vec<models::HistoryResponseMessagesInner>) -> HistoryResponse {
        HistoryResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            title: None,
            suite_id: None,
            agent_type: None,
            messages,
            next_before_thread_seq: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "history")]
    History,
}

impl Default for Type {
    fn default() -> Type {
        Self::History
    }
}

