/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, new, open, user. Server message types: list, final, await_user, ok, error. 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponseThreadsInner {
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "last_activity", skip_serializing_if = "Option::is_none")]
    pub last_activity: Option<String>,
    #[serde(rename = "unread_count", skip_serializing_if = "Option::is_none")]
    pub unread_count: Option<i32>,
    #[serde(rename = "last_message_preview", skip_serializing_if = "Option::is_none")]
    pub last_message_preview: Option<String>,
}

impl ListResponseThreadsInner {
    pub fn new(thread_id: String) -> ListResponseThreadsInner {
        ListResponseThreadsInner {
            thread_id,
            title: None,
            last_activity: None,
            unread_count: None,
            last_message_preview: None,
        }
    }
}

