/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelTaskSnapshot {
    #[serde(rename = "taskId")]
    pub task_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "folder", skip_serializing_if = "Option::is_none")]
    pub folder: Option<String>,
    #[serde(rename = "goal", skip_serializing_if = "Option::is_none")]
    pub goal: Option<String>,
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Vec<String>>,
    #[serde(
        rename = "expected_model_path",
        skip_serializing_if = "Option::is_none"
    )]
    pub expected_model_path: Option<String>,
    #[serde(rename = "invariants", skip_serializing_if = "Option::is_none")]
    pub invariants: Option<Vec<String>>,
    #[serde(rename = "status")]
    pub status: models::PlanTaskStatus,
    #[serde(rename = "checklist")]
    pub checklist: Vec<models::PlanChecklistItem>,
}

impl ModelTaskSnapshot {
    pub fn new(
        task_id: String,
        name: String,
        status: models::PlanTaskStatus,
        checklist: Vec<models::PlanChecklistItem>,
    ) -> ModelTaskSnapshot {
        ModelTaskSnapshot {
            task_id,
            name,
            folder: None,
            goal: None,
            inputs: None,
            expected_model_path: None,
            invariants: None,
            status,
            checklist,
        }
    }
}
