/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewRequest {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// User's question to start a new thread
    #[serde(rename = "question")]
    pub question: String,
    /// Suite id to use (e.g. data_engineer | kb)
    #[serde(rename = "suiteId")]
    pub suite_id: String,
    /// Agent/mode to use (ask | cleanse | model | kb | agent | review). Required.
    #[serde(rename = "agentType")]
    pub agent_type: AgentType,
    /// If true, stream lightweight trace frames (tool activity) while the agent runs.
    #[serde(rename = "trace", skip_serializing_if = "Option::is_none")]
    pub trace: Option<bool>,
}

impl NewRequest {
    pub fn new(v: i32, cid: String, r#type: Type, question: String, suite_id: String, agent_type: AgentType) -> NewRequest {
        NewRequest {
            v,
            cid,
            r#type,
            question,
            suite_id,
            agent_type,
            trace: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "new")]
    New,
}

impl Default for Type {
    fn default() -> Type {
        Self::New
    }
}
/// Agent/mode to use (ask | cleanse | model | kb | agent | review). Required.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgentType {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "cleanse")]
    Cleanse,
    #[serde(rename = "model")]
    Model,
    #[serde(rename = "kb")]
    Kb,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "review")]
    Review,
}

impl Default for AgentType {
    fn default() -> AgentType {
        Self::Ask
    }
}

