/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhaseRun {
    /// RFC3339 start timestamp for this run.
    #[serde(rename = "started_at")]
    pub started_at: String,
    /// RFC3339 end timestamp for this run (null if in progress).
    #[serde(rename = "ended_at", skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<String>,
    /// Duration for this run (ms), present when ended_at is present.
    #[serde(rename = "runtime_ms", skip_serializing_if = "Option::is_none")]
    pub runtime_ms: Option<i64>,
}

impl PhaseRun {
    pub fn new(started_at: String) -> PhaseRun {
        PhaseRun {
            started_at,
            ended_at: None,
            runtime_ms: None,
        }
    }
}
