/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PhaseReasonCode {
    #[serde(rename = "phase_set")]
    PhaseSet,
    #[serde(rename = "preflight_start")]
    PreflightStart,
    #[serde(rename = "preflight_ok")]
    PreflightOk,
    #[serde(rename = "plan_approved")]
    PlanApproved,
    #[serde(rename = "plan_auto_approved")]
    PlanAutoApproved,
    #[serde(rename = "plan_already_approved")]
    PlanAlreadyApproved,
    #[serde(rename = "plan_missing")]
    PlanMissing,
    #[serde(rename = "plan_not_approved")]
    PlanNotApproved,
    #[serde(rename = "plan_invalid_empty")]
    PlanInvalidEmpty,
    #[serde(rename = "plan_pruned_empty")]
    PlanPrunedEmpty,
    #[serde(rename = "plan_semantic_invalid")]
    PlanSemanticInvalid,
    #[serde(rename = "work_group_validate")]
    WorkGroupValidate,
    #[serde(rename = "plan_tasks_done")]
    PlanTasksDone,
    #[serde(rename = "no_work_all_done")]
    NoWorkAllDone,
    #[serde(rename = "authoring_complete")]
    AuthoringComplete,
    #[serde(rename = "precheck_failed")]
    PrecheckFailed,
    #[serde(rename = "validate_pass")]
    ValidatePass,
    #[serde(rename = "validate_fail")]
    ValidateFail,
    #[serde(rename = "review_proceed")]
    ReviewProceed,
    #[serde(rename = "review_patch_plan")]
    ReviewPatchPlan,
    #[serde(rename = "review_patch_impl")]
    ReviewPatchImpl,
    #[serde(rename = "review_project_summary")]
    ReviewProjectSummary,
    #[serde(rename = "review_batch")]
    ReviewBatch,
    #[serde(rename = "review_final_unify")]
    ReviewFinalUnify,
    #[serde(rename = "user_approved_publish")]
    UserApprovedPublish,
    #[serde(rename = "publish_success")]
    PublishSuccess,
    #[serde(rename = "publish_fail")]
    PublishFail,
    #[serde(rename = "publish_confirmed_success")]
    PublishConfirmedSuccess,
    #[serde(rename = "publish_confirmed_fail")]
    PublishConfirmedFail,
    #[serde(rename = "phase_blocked")]
    PhaseBlocked,
}

impl std::fmt::Display for PhaseReasonCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PhaseSet => write!(f, "phase_set"),
            Self::PreflightStart => write!(f, "preflight_start"),
            Self::PreflightOk => write!(f, "preflight_ok"),
            Self::PlanApproved => write!(f, "plan_approved"),
            Self::PlanAutoApproved => write!(f, "plan_auto_approved"),
            Self::PlanAlreadyApproved => write!(f, "plan_already_approved"),
            Self::PlanMissing => write!(f, "plan_missing"),
            Self::PlanNotApproved => write!(f, "plan_not_approved"),
            Self::PlanInvalidEmpty => write!(f, "plan_invalid_empty"),
            Self::PlanPrunedEmpty => write!(f, "plan_pruned_empty"),
            Self::PlanSemanticInvalid => write!(f, "plan_semantic_invalid"),
            Self::WorkGroupValidate => write!(f, "work_group_validate"),
            Self::PlanTasksDone => write!(f, "plan_tasks_done"),
            Self::NoWorkAllDone => write!(f, "no_work_all_done"),
            Self::AuthoringComplete => write!(f, "authoring_complete"),
            Self::PrecheckFailed => write!(f, "precheck_failed"),
            Self::ValidatePass => write!(f, "validate_pass"),
            Self::ValidateFail => write!(f, "validate_fail"),
            Self::ReviewProceed => write!(f, "review_proceed"),
            Self::ReviewPatchPlan => write!(f, "review_patch_plan"),
            Self::ReviewPatchImpl => write!(f, "review_patch_impl"),
            Self::ReviewProjectSummary => write!(f, "review_project_summary"),
            Self::ReviewBatch => write!(f, "review_batch"),
            Self::ReviewFinalUnify => write!(f, "review_final_unify"),
            Self::UserApprovedPublish => write!(f, "user_approved_publish"),
            Self::PublishSuccess => write!(f, "publish_success"),
            Self::PublishFail => write!(f, "publish_fail"),
            Self::PublishConfirmedSuccess => write!(f, "publish_confirmed_success"),
            Self::PublishConfirmedFail => write!(f, "publish_confirmed_fail"),
            Self::PhaseBlocked => write!(f, "phase_blocked"),
        }
    }
}

impl Default for PhaseReasonCode {
    fn default() -> PhaseReasonCode {
        Self::PhaseSet
    }
}
