/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhaseResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "thread_seq", skip_serializing_if = "Option::is_none")]
    pub thread_seq: Option<i32>,
    #[serde(rename = "for_cid", skip_serializing_if = "Option::is_none")]
    pub for_cid: Option<String>,
    /// Index of the backing ThreadStep::Phase in the thread log.
    #[serde(rename = "step_idx")]
    pub step_idx: i32,
    #[serde(rename = "phase")]
    pub phase: String,
    #[serde(rename = "from_phase", skip_serializing_if = "Option::is_none")]
    pub from_phase: Option<String>,
    #[serde(rename = "reason_code", skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
    #[serde(rename = "reason_detail", skip_serializing_if = "Option::is_none")]
    pub reason_detail: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// RFC3339 timestamp stored in the thread log for this phase transition.
    #[serde(rename = "ts")]
    pub ts: String,
    /// List of start/end windows for this phase across the thread lifetime. Each re-entry into the phase appends a new run. 
    #[serde(rename = "runs")]
    pub runs: Vec<models::PhaseRun>,
    /// Sum of all completed run durations for this phase (ms).
    #[serde(rename = "total_runtime_ms")]
    pub total_runtime_ms: i64,
    /// If `from_phase` is present, this is the updated run list for the phase being exited. 
    #[serde(rename = "from_phase_runs", skip_serializing_if = "Option::is_none")]
    pub from_phase_runs: Option<Vec<models::PhaseRun>>,
    /// If `from_phase` is present, sum of all completed run durations for it (ms).
    #[serde(rename = "from_phase_total_runtime_ms", skip_serializing_if = "Option::is_none")]
    pub from_phase_total_runtime_ms: Option<i64>,
}

impl PhaseResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, thread_id: String, step_idx: i32, phase: String, ts: String, runs: Vec<models::PhaseRun>, total_runtime_ms: i64) -> PhaseResponse {
        PhaseResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            thread_seq: None,
            for_cid: None,
            step_idx,
            phase,
            from_phase: None,
            reason_code: None,
            reason_detail: None,
            ts,
            runs,
            total_runtime_ms,
            from_phase_runs: None,
            from_phase_total_runtime_ms: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "phase")]
    Phase,
}

impl Default for Type {
    fn default() -> Type {
        Self::Phase
    }
}

