/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "taskKind")]
pub enum PlanTask {
    #[serde(rename="cleanse")]
    Cleanse(models::CleanseTaskSnapshot),
    #[serde(rename="model")]
    Model(models::ModelTaskSnapshot),
}

impl Default for PlanTask {
    fn default() -> Self {
        Self::Cleanse(Default::default())
    }
}


