/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanSnapshot {
    #[serde(rename = "planKind")]
    pub plan_kind: PlanKind,
    #[serde(rename = "planKey")]
    pub plan_key: String,
    #[serde(rename = "status")]
    pub status: models::PlanStatus,
    #[serde(rename = "tasks")]
    pub tasks: Vec<models::PlanTask>,
}

impl PlanSnapshot {
    pub fn new(plan_kind: PlanKind, plan_key: String, status: models::PlanStatus, tasks: Vec<models::PlanTask>) -> PlanSnapshot {
        PlanSnapshot {
            plan_kind,
            plan_key,
            status,
            tasks,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlanKind {
    #[serde(rename = "cleanse")]
    Cleanse,
    #[serde(rename = "model")]
    Model,
}

impl Default for PlanKind {
    fn default() -> PlanKind {
        Self::Cleanse
    }
}

