/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanWorkGroup {
    #[serde(rename = "groupId")]
    pub group_id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "kind")]
    pub kind: models::PlanWorkGroupKind,
    #[serde(rename = "items")]
    pub items: Vec<models::PlanWorkGroupItemRef>,
    #[serde(rename = "dependsOnGroupIds", skip_serializing_if = "Option::is_none")]
    pub depends_on_group_ids: Option<Vec<String>>,
}

impl PlanWorkGroup {
    pub fn new(
        group_id: String,
        label: String,
        kind: models::PlanWorkGroupKind,
        items: Vec<models::PlanWorkGroupItemRef>,
    ) -> PlanWorkGroup {
        PlanWorkGroup {
            group_id,
            label,
            kind,
            items,
            depends_on_group_ids: None,
        }
    }
}
