/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanSnapshot {
    #[serde(rename = "planKind")]
    pub plan_kind: models::PlanKind,
    #[serde(rename = "planKey")]
    pub plan_key: String,
    #[serde(rename = "status")]
    pub status: models::PlanStatus,
    #[serde(rename = "tasks")]
    pub tasks: Vec<models::PlanTask>,
    /// Ordered, suite-authored work groups for this plan. Each group references one or more checklist items (by taskId + checklistItemId) so clients can render a coherent work plan and the server can deterministically execute the next incomplete group. 
    #[serde(rename = "workGroups")]
    pub work_groups: Vec<models::PlanWorkGroup>,
    /// Optional, suite-owned snapshot payload for UI/debugging (e.g. batched review notes). This is an opaque JSON object; clients must treat it as best-effort and forward-compatible. 
    #[serde(rename = "projectSnapshot", skip_serializing_if = "Option::is_none")]
    pub project_snapshot: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl PlanSnapshot {
    pub fn new(plan_kind: models::PlanKind, plan_key: String, status: models::PlanStatus, tasks: Vec<models::PlanTask>, work_groups: Vec<models::PlanWorkGroup>) -> PlanSnapshot {
        PlanSnapshot {
            plan_kind,
            plan_key,
            status,
            tasks,
            work_groups,
            project_snapshot: None,
        }
    }
}

