/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewDecisionMeta {
    #[serde(rename = "decision")]
    pub decision: models::ReviewDecision,
    #[serde(rename = "tier")]
    pub tier: models::ReviewTier,
    #[serde(rename = "dataset_ids")]
    pub dataset_ids: Vec<String>,
    #[serde(rename = "review_ref", skip_serializing_if = "Option::is_none")]
    pub review_ref: Option<models::ReviewRef>,
}

impl ReviewDecisionMeta {
    pub fn new(
        decision: models::ReviewDecision,
        tier: models::ReviewTier,
        dataset_ids: Vec<String>,
    ) -> ReviewDecisionMeta {
        ReviewDecisionMeta {
            decision,
            tier,
            dataset_ids,
            review_ref: None,
        }
    }
}
