/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ServerMessage {
    #[serde(rename="list")]
    List(models::ListResponse),
    #[serde(rename="suites")]
    Suites(models::SuitesResponse),
    #[serde(rename="final")]
    Final(models::FinalResponse),
    #[serde(rename="review")]
    Review(models::ReviewResponse),
    #[serde(rename="trace")]
    Trace(models::TraceResponse),
    #[serde(rename="suite_progress")]
    SuiteProgress(models::SuiteProgressResponse),
    #[serde(rename="plan")]
    Plan(models::PlanResponse),
    #[serde(rename="plan_update")]
    PlanUpdate(models::PlanUpdateResponse),
    #[serde(rename="await_user")]
    AwaitUser(models::AwaitUserResponse),
    #[serde(rename="await_approval")]
    AwaitApproval(models::AwaitApprovalResponse),
    #[serde(rename="ok")]
    Ok(models::OkResponse),
    #[serde(rename="error")]
    Error(models::ErrorResponse),
    #[serde(rename="thread_assigned")]
    ThreadAssigned(models::ThreadAssignedResponse),
    #[serde(rename="processing")]
    Processing(models::ProcessingResponse),
    #[serde(rename="token")]
    Token(models::TokenResponse),
    #[serde(rename="history")]
    History(models::HistoryResponse),
    #[serde(rename="unread")]
    Unread(models::UnreadResponse),
}

impl Default for ServerMessage {
    fn default() -> Self {
        Self::List(Default::default())
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Stage {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "error")]
    Error,
}

impl Default for Stage {
    fn default() -> Stage {
        Self::Queued
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Step {
    #[serde(rename = "run_sql")]
    RunSql,
    #[serde(rename = "sql_schema")]
    SqlSchema,
    #[serde(rename = "sql_stats")]
    SqlStats,
    #[serde(rename = "sql_sample")]
    SqlSample,
    #[serde(rename = "vect_query")]
    VectQuery,
}

impl Default for Step {
    fn default() -> Step {
        Self::RunSql
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FinishReason {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "length")]
    Length,
    #[serde(rename = "error")]
    Error,
}

impl Default for FinishReason {
    fn default() -> FinishReason {
        Self::Stop
    }
}

