/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ServerMessage {
    #[serde(rename="list")]
    List(models::ListResponse),
    #[serde(rename="suites")]
    Suites(models::SuitesResponse),
    #[serde(rename="final")]
    Final(models::FinalResponse),
    #[serde(rename="review")]
    Review(models::ReviewResponse),
    #[serde(rename="plans")]
    Plans(models::PlansResponse),
    #[serde(rename="plans_changed")]
    PlansChanged(models::PlansChangedResponse),
    #[serde(rename="thread_state")]
    ThreadState(models::ThreadStateResponse),
    #[serde(rename="phase")]
    Phase(models::PhaseResponse),
    #[serde(rename="await_user")]
    AwaitUser(models::AwaitUserResponse),
    #[serde(rename="await_approval")]
    AwaitApproval(models::AwaitApprovalResponse),
    #[serde(rename="ok")]
    Ok(models::OkResponse),
    #[serde(rename="error")]
    Error(models::ErrorResponse),
    #[serde(rename="thread_assigned")]
    ThreadAssigned(models::ThreadAssignedResponse),
    #[serde(rename="history")]
    History(models::HistoryResponse),
    #[serde(rename="unread")]
    Unread(models::UnreadResponse),
    #[serde(rename="tool_start")]
    ToolStart(models::ToolStartResponse),
    #[serde(rename="tool_end")]
    ToolEnd(models::ToolEndResponse),
    #[serde(rename="llm_start")]
    LlmStart(models::LlmStartResponse),
    #[serde(rename="llm_end")]
    LlmEnd(models::LlmEndResponse),
}

impl Default for ServerMessage {
    fn default() -> Self {
        Self::List(Default::default())
    }
}

/// Which plan kinds changed. UI should fetch `plans` to get latest snapshots.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Changed {
    #[serde(rename = "cleanse")]
    Cleanse,
    #[serde(rename = "model")]
    Model,
}

impl Default for Changed {
    fn default() -> Changed {
        Self::Cleanse
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}

