/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuiteProgressResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "thread_seq", skip_serializing_if = "Option::is_none")]
    pub thread_seq: Option<i32>,
    #[serde(rename = "for_cid", skip_serializing_if = "Option::is_none")]
    pub for_cid: Option<String>,
    /// Suite id currently running (e.g. data_engineer)
    #[serde(rename = "suiteId")]
    pub suite_id: String,
    /// Ordered list of phases for the current suite (best-effort)
    #[serde(rename = "phases")]
    pub phases: Vec<String>,
    /// Phases considered complete (best-effort)
    #[serde(rename = "completed")]
    pub completed: Vec<String>,
    /// Current phase name
    #[serde(rename = "current")]
    pub current: String,
}

impl SuiteProgressResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, thread_id: String, suite_id: String, phases: Vec<String>, completed: Vec<String>, current: String) -> SuiteProgressResponse {
        SuiteProgressResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            thread_seq: None,
            for_cid: None,
            suite_id,
            phases,
            completed,
            current,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "suite_progress")]
    SuiteProgress,
}

impl Default for Type {
    fn default() -> Type {
        Self::SuiteProgress
    }
}

