/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, trace, final, review, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskStatusChangedChange {
    #[serde(rename = "taskId")]
    pub task_id: String,
    #[serde(rename = "from")]
    pub from: models::PlanTaskStatus,
    #[serde(rename = "to")]
    pub to: models::PlanTaskStatus,
}

impl TaskStatusChangedChange {
    pub fn new(task_id: String, from: models::PlanTaskStatus, to: models::PlanTaskStatus) -> TaskStatusChangedChange {
        TaskStatusChangedChange {
            task_id,
            from,
            to,
        }
    }
}

