/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadStateItem {
    #[serde(rename = "item_id")]
    pub item_id: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    #[serde(rename = "finished_at", skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<String>,
    #[serde(rename = "runtime_ms", skip_serializing_if = "Option::is_none")]
    pub runtime_ms: Option<i64>,
    #[serde(rename = "last_error", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<models::ThreadStateItemError>,
    /// Opaque outputs object (suite/tool specific). Keep small.
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ThreadStateItem {
    pub fn new(item_id: String, kind: String, status: String) -> ThreadStateItem {
        ThreadStateItem {
            item_id,
            kind,
            status,
            started_at: None,
            finished_at: None,
            runtime_ms: None,
            last_error: None,
            outputs: None,
        }
    }
}
