/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadEvent {
    /// Index of the backing ThreadStep in the thread log.
    #[serde(rename = "step_idx")]
    pub step_idx: i32,
    #[serde(rename = "event_kind")]
    pub event_kind: models::ThreadEventKind,
    /// RFC3339 timestamp of the event.
    #[serde(rename = "ts")]
    pub ts: String,
    #[serde(rename = "tool_id", skip_serializing_if = "Option::is_none")]
    pub tool_id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "clean_name", skip_serializing_if = "Option::is_none")]
    pub clean_name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ToolEventStatus>,
    #[serde(rename = "runtime_ms", skip_serializing_if = "Option::is_none")]
    pub runtime_ms: Option<i64>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "call_id", skip_serializing_if = "Option::is_none")]
    pub call_id: Option<i32>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(rename = "phase", skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,
    #[serde(rename = "ctx", skip_serializing_if = "Option::is_none")]
    pub ctx: Option<models::ExecutionContext>,
}

impl ThreadEvent {
    pub fn new(step_idx: i32, event_kind: models::ThreadEventKind, ts: String) -> ThreadEvent {
        ThreadEvent {
            step_idx,
            event_kind,
            ts,
            tool_id: None,
            name: None,
            clean_name: None,
            status: None,
            runtime_ms: None,
            payload: None,
            error: None,
            call_id: None,
            model: None,
            phase: None,
            ctx: None,
        }
    }
}

