/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadStateItemError {
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "tool_step_idx", skip_serializing_if = "Option::is_none")]
    pub tool_step_idx: Option<i32>,
    #[serde(rename = "step_ts", skip_serializing_if = "Option::is_none")]
    pub step_ts: Option<String>,
}

impl ThreadStateItemError {
    pub fn new(summary: String) -> ThreadStateItemError {
        ThreadStateItemError {
            summary,
            tool_step_idx: None,
            step_ts: None,
        }
    }
}
