/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadStateSnapshot {
    #[serde(rename = "thread_state_schema_version")]
    pub thread_state_schema_version: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "suiteId", skip_serializing_if = "Option::is_none")]
    pub suite_id: Option<String>,
    #[serde(rename = "agentType", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<String>,
    #[serde(rename = "currentPhase", skip_serializing_if = "Option::is_none")]
    pub current_phase: Option<String>,
    #[serde(rename = "last_materialized_step_count")]
    pub last_materialized_step_count: i32,
    #[serde(rename = "total_runtime_ms")]
    pub total_runtime_ms: i64,
    /// Ordered suite phases for the current suite+agent_type (suite-owned ordering). Clients should treat this as the authoritative phase order for rendering progress.
    #[serde(rename = "phases")]
    pub phases: Vec<String>,
    /// Subset of `phases` that are considered completed, derived from `currentPhase` and the suite's phase order. (Does not include the current in-flight phase.)
    #[serde(rename = "completedPhases")]
    pub completed_phases: Vec<String>,
    /// Recent, durable timeline events for UI. This is a bounded, best-effort list intended for \"post reconnect\" tool timelines. (Not a complete event log.)
    #[serde(rename = "events")]
    pub events: Vec<models::ThreadEvent>,
    #[serde(rename = "items")]
    pub items: Vec<models::ThreadStateItem>,
    /// Summary-only plan refs (opaque JSON by kind).
    #[serde(rename = "planSummaries", skip_serializing_if = "Option::is_none")]
    pub plan_summaries: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ThreadStateSnapshot {
    pub fn new(
        thread_state_schema_version: i32,
        thread_id: String,
        last_materialized_step_count: i32,
        total_runtime_ms: i64,
        phases: Vec<String>,
        completed_phases: Vec<String>,
        events: Vec<models::ThreadEvent>,
        items: Vec<models::ThreadStateItem>,
    ) -> ThreadStateSnapshot {
        ThreadStateSnapshot {
            thread_state_schema_version,
            thread_id,
            suite_id: None,
            agent_type: None,
            current_phase: None,
            last_materialized_step_count,
            total_runtime_ms,
            phases,
            completed_phases,
            events,
            items,
            plan_summaries: None,
        }
    }
}
