/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end. 
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadAssignedResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
}

impl ThreadAssignedResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, cid: String, thread_id: String) -> ThreadAssignedResponse {
        ThreadAssignedResponse {
            v,
            r#type,
            server_time,
            seq,
            cid,
            thread_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "thread_assigned")]
    ThreadAssigned,
}

impl Default for Type {
    fn default() -> Type {
        Self::ThreadAssigned
    }
}

