/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ThreadEventKind {
    #[serde(rename = "tool_start")]
    ToolStart,
    #[serde(rename = "tool_end")]
    ToolEnd,
    #[serde(rename = "llm_start")]
    LlmStart,
    #[serde(rename = "llm_end")]
    LlmEnd,
}

impl std::fmt::Display for ThreadEventKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ToolStart => write!(f, "tool_start"),
            Self::ToolEnd => write!(f, "tool_end"),
            Self::LlmStart => write!(f, "llm_start"),
            Self::LlmEnd => write!(f, "llm_end"),
        }
    }
}

impl Default for ThreadEventKind {
    fn default() -> ThreadEventKind {
        Self::ToolStart
    }
}
