/*
 * Skippr Ask WebSocket API
 *
 * WebSocket-based chat threads for Ask. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, resume. Server message types: list, suites, thread_assigned, processing, token, final, await_user, await_approval, unread, ok, error, history. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "thread_seq", skip_serializing_if = "Option::is_none")]
    pub thread_seq: Option<i32>,
    #[serde(rename = "for_cid", skip_serializing_if = "Option::is_none")]
    pub for_cid: Option<String>,
    #[serde(rename = "delta")]
    pub delta: String,
    #[serde(rename = "finish_reason", skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<FinishReason>,
}

impl TokenResponse {
    pub fn new(v: i32, r#type: Type, server_time: String, seq: i32, thread_id: String, delta: String) -> TokenResponse {
        TokenResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            thread_seq: None,
            for_cid: None,
            delta,
            finish_reason: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "token")]
    Token,
}

impl Default for Type {
    fn default() -> Type {
        Self::Token
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FinishReason {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "length")]
    Length,
    #[serde(rename = "error")]
    Error,
}

impl Default for FinishReason {
    fn default() -> FinishReason {
        Self::Stop
    }
}

