/*
 * ReAct WebSocket API
 *
 * WebSocket-based chat threads for the ReAct server. Clients send JSON frames and receive JSON frames. Supported client message types: list, suites, new, open, user, approve, reject, history, seen, delete, plans, thread_state. Server message types: list, suites, thread_assigned, final, review, await_user, await_approval, unread, ok, error, history, plans, plans_changed, thread_state, phase, tool_start, tool_end, llm_start, llm_end.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStartResponse {
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "server_time")]
    pub server_time: String,
    #[serde(rename = "seq")]
    pub seq: i32,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "thread_seq", skip_serializing_if = "Option::is_none")]
    pub thread_seq: Option<i32>,
    #[serde(rename = "for_cid", skip_serializing_if = "Option::is_none")]
    pub for_cid: Option<String>,
    #[serde(rename = "tool_id")]
    pub tool_id: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Human-readable, short, self-documenting label for UI (e.g. \"Read dbt_project.yml\").
    #[serde(rename = "clean_name", skip_serializing_if = "Option::is_none")]
    pub clean_name: Option<String>,
    #[serde(rename = "phase", skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,
    #[serde(rename = "status")]
    pub status: models::ToolEventStatus,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ToolStartResponse {
    pub fn new(
        v: i32,
        r#type: Type,
        server_time: String,
        seq: i32,
        thread_id: String,
        tool_id: String,
        name: String,
        status: models::ToolEventStatus,
    ) -> ToolStartResponse {
        ToolStartResponse {
            v,
            r#type,
            server_time,
            seq,
            thread_id,
            thread_seq: None,
            for_cid: None,
            tool_id,
            name,
            clean_name: None,
            phase: None,
            status,
            payload: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tool_start")]
    ToolStart,
}

impl Default for Type {
    fn default() -> Type {
        Self::ToolStart
    }
}
