[package]
name = "skippr-plugin-schema-sink-clickhouse"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "skippr-plugin-schema-sink-clickhouse"
path = "src/main.rs"

[dependencies]
clap.workspace = true
skippr-core.workspace = true
skippr-runtime-sdk.workspace = true
tokio.workspace = true
skippr-plugin-data-sink-clickhouse = { path = "../../data_sink/clickhouse" }

[package.metadata.skippr-plugin]
kind = "SchemaSink"
plugin_name = "Clickhouse"
supports_schema = true
