[package]
name = "skippr-plugin-data-sink-stdout"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "skippr-plugin-data-sink-stdout"
path = "src/main.rs"

[dependencies]
clap.workspace = true
tokio.workspace = true
skippr-runtime-sdk.workspace = true
bytes.workspace = true
hex.workspace = true
parquet.workspace = true

arrow = { version = "58.3.0", features = ["ipc_compression"] }
async-trait = "0.1.77"
datafusion.workspace = true
futures = "0.3.25"
[package.metadata.skippr-plugin]
kind = "DataSink"
plugin_name = "Stdout"

[package.metadata.skippr-plugin.sink_capability]
name = "Stdout"
guarantee_tier = "Unsupported"
can_manage_skippr_columns = false
can_maintain_tombstone_tables = false
can_compare_order_tokens = false
supports_transactions = false
retry_semantics = "NonRetryable"
grouping_support = "None"
